### ISSUE TITLE
Remove constrained viewport size

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#100]
Requires https://github.com/silverstripe/silverstripe-admin/issues/100 to be done first 
Part of Reponsive CMS issue https://github.com/silverstripe/silverstripe-framework/issues/6267

Remove constrained viewport of 720px by swapping `<meta name="viewport" content="width=720, maximum-scale=1.0" />` for `<meta name="viewport" content="width=device-width, maximum-scale=1.0" />` [~1pt]

---

Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/103

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-admin/pull/103
