### ISSUE TITLE
Random behaviour for grid field next and previous button.

### ISSUE THREAD

**Issue by roopamjain01** [silverstripe/silverstripe-admin#1006]
My Silverstripe version is 4.4 and grid field next and previous button functionality working randomly.

I have grid with 25 records. I have two pages in my grid, means item per page is 15 in the grid. 

When I click on first record on the first page in the grid, I can press next button till the 16th record and then next button is disabled on the 17th record.

But when I start from second page in the gird from 18th number record then next record should be the 19th number record but currently after 18th record I am getting 2nd number record as a next record and after that I can see next button till the 16th record and on the 17th record again next button is disabled.

In my case I expect next button should work for all the 25 records in the grid and next button should be disabled on the 25th record. But next button disabled after 17th records according to the current code in GridFieldDetailForm_ItemRequest.php at line 540($limit = $itemsPerPage + 2).

In second senario, when I click on the 15th number of record on the page 1, I can see next button only for 15th and 16th record and then again next button is disabled on the 17th record, but I think I should be able to see all the record from 15th to 25th (all 10 recods) and next button should be enabled.

Same issue with previous button as well, when I click on the 25th number record on page 2, I can see previous button till 16th record and then previous button is disabled on 15th record on page 1. But I expect previous button should work till first record in the grid. 

Please let me know If you need any other information.

**Comment by brynwhyman** [comment]
Hi @roopamjain01 thanks for raising this issue. The bugs you're experiencing have already been raised in the following issue: https://github.com/silverstripe/silverstripe-admin/issues/886

Do you mind adding your notes to that issue and closing this one? Thanks!

**Comment by roopamjain01** [comment]
Moved the issue detail in the issue #886: https://github.com/silverstripe/silverstripe-admin/issues/886
