### ISSUE TITLE
failed to parse SourceMap

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-admin#1007]
a very minor issue, but still an empty dev console is a happy console... it seems that the source map are used in the .js files but are not included in resources

```
DevTools failed to parse SourceMap: /_resources/vendor/silverstripe/admin/thirdparty/bootstrap/js/dist/collapse.js.map
DevTools failed to parse SourceMap: /_resources/vendor/silverstripe/admin/thirdparty/bootstrap/js/dist/util.js.map
```

sourcemaps don't have a big value in my opinion so in LeftAndMain instead of

        Requirements::javascript('silverstripe/admin: thirdparty/bootstrap/js/dist/util.js');
        Requirements::javascript('silverstripe/admin: thirdparty/bootstrap/js/dist/collapse.js');

we could require minified files that don't use the sourcemaps

**Comment by Cheddam** [comment]
Thanks for raising this @lekoala 🙂

**Comment by HopStudios-Development** [comment]
Is there any solution for this problem? The call of these files in LeftAndMain is made using .js but that is rendering with .map and says 404 for them. Badly stuck in this issue. Many back-end operations aren't working.

**Comment by lekoala** [comment]
@HopStudios-Development  you can run this
https://github.com/lekoala/silverstripe-base/blob/master/bin/DeleteJsMaps.php

**Comment by GuySartorelli** [comment]
PR merged, it'll be automatically patched by GitHub actions.
