### ISSUE TITLE
Icon for "Edit mode" dissapeared in 4.5.0

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-admin#1010]
Silverstripe 4.4:
<img width="181" alt="Screenshot 2020-02-12 at 13 15 13" src="https://user-images.githubusercontent.com/329880/74338328-e2e1b800-4d99-11ea-8b5d-29451138f6dc.png">

Silverstripe 4.5.0:
<img width="177" alt="image" src="https://user-images.githubusercontent.com/329880/74338309-d78e8c80-4d99-11ea-8532-6a9f2360f3cf.png">

Seems to be related to this commit: https://github.com/silverstripe/silverstripe-admin/commit/08a0811a8c410af23ecc18b7f36218e75ee446c9 @Cheddam

**Comment by sachajudd** [comment]
Whoops 😄we'll get this back in ASAP @purplespider good catch!
