### ISSUE TITLE
Toast notifications have lost their drop shadow

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#1017]
Toast notifications seem to have lost their drop shadow which means they aren't very noticeable against the background, especially when multiple notifications are stacked on top of each other. 
<img width="199" alt="Pasted_Image_4_03_20__11_06_AM" src="https://user-images.githubusercontent.com/555033/75824389-4c3c7000-5e08-11ea-8da2-699c8dba868e.png">

Refer to DSM for designs, but use the standard drop shadow variable provided in the CMS.
https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5dae8013fccf7c3293fb199d

Using the latest development branch on Chrome browser.

## PRs
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/1081

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-admin/pull/1081

**Comment by michalkleiner** [comment]
Sigh, the issue clearly should have been titled "Toast notifications have dropped their drop shadow" :-D

**Comment by kinglozzer** [comment]
https://github.com/silverstripe/silverstripe-admin/pull/1081 merged
