### ISSUE TITLE
Make LeftAndMain independent of the presence of Versioned module

### ISSUE THREAD

**Issue by alessandromarotta** [silverstripe/silverstripe-admin#1049]
LeftAndMain's _init()_ method calls two _Versioned_ methods and this makes it impossible to have the Silverstripe-admin module installed without the Versioned module.

In other parts of the Silverstripe-admin code we have the verification of the presence or absence of the Versioned class, instead in the init() method it is missing.

Please, could you also introduce in the init() method the verification of the presence of the Versioned module in order to install the administrative panel without the Versioned module?

like that, for example: 

```
/**
     * @uses LeftAndMainExtension->init()
     * @uses LeftAndMainExtension->accessedCMS()
     * @uses CMSMenu
     */
protected function init()
{
        parent::init();
        [...]
        
        if(class_exists(Versioned::class)) {
           // Set the current reading mode
           Versioned::set_stage(Versioned::DRAFT);

           // Set default reading mode to suppress ?stage=Stage querystring params in CMS
           Versioned::set_default_reading_mode(Versioned::get_reading_mode());
      }
}
```

**Comment by maxime-rainville** [comment]
Looking at `admin`'s composer file, it does require `versioned`. So we're not making a claim that admin should work without versioned installed.

From doing a quick search on the admin module, it looks like admin could work without versioned if LeftAndMain conditionally made those two Versioned call like you suggest. That's probably not a configuration we would explicitly want to test for or officially support.

But if you want to make a PR for it, I would be inclined to approve it.

**Comment by alessandromarotta** [comment]
ok, thank you!

**Comment by GuySartorelli** [comment]
Closing for now - if we choose to remove the dependency on `Versioned` in the future, we can revisit this.
