### ISSUE TITLE
4.6.0 Regression / Font icons break with cache

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-admin#1064]
### Overview
New icons to be released in CMS 4.6.0 look to break if in a funny cache state on initial load
![image](https://user-images.githubusercontent.com/15868440/86186334-efba4900-bb8c-11ea-8394-20f474be30c4.png)

Assuming it's related to caching due to the workaround.

* Left icon: form submission icon
* Right icon: restricted file icon

### To recreate
1. Build a new project: `silverstripe/recipe-cms: "4.6-dev"` & `silverstripe/userforms: "5.x-dev"`
2. Upload file to Files area
3. Set visibility of new File to 'Logged-in users'
4. See the broken icon

### Workaround
Force-refresh the page

### Versions
silverstripe/recipe-cms: "4.6-dev"
silverstripe/userforms: "5.x-dev"

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/webpack-config/pull/47
