### ISSUE TITLE
Dropdown actions don't respond to "enter" key

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#1067]
React dropdown menu items don't respond to the enter key. You can use the enter key to open the drop down menu, you can use the arrow to select a sub entry, but when you use the enter key to try to select an option, nothing happens.

The space bar works however.

Two examples where this behaviour can be observed is the asset-admin file action menu and the elemental block action menu.

https://youtu.be/iz62lgX5Rfo

### ACs
- The enter key (as well as the spacebar key) can be used to trigger the action
- Investigate whether this component is used anywhere else 
- On completion the pattern library reflects this working state

### Notes
- A quick test of the bootstrap and reactstrap components appear to work as expected but the pattern library component is not

**Comment by brynwhyman** [comment]
This has come up a few times before, see: [Can't submit "More actions" button with enter key](https://github.com/dnadesign/silverstripe-elemental/issues/754)

**Comment by emteknetnz** [comment]
We need to upgrade to reactstrap 7.0.0 from 6.5.0

We require this fix
https://github.com/reactstrap/reactstrap/commit/6b507321827f73d1e65f6953d6aa5da23d6d3996

First reported here
https://github.com/reactstrap/reactstrap/issues/1228

First attempted a fix which was incorrect here, and is in our current version 6.5.0
https://github.com/reactstrap/reactstrap/pull/1232/files

I tried fixing this on my local vendor.js and the enter key worked as expected

**Comment by brynwhyman** [comment]
Unblocking this, admin is now using Reactstrap 8

**Comment by emteknetnz** [comment]
OK cool, should just be a matter of re-testing with the upgraded reactstrap and then closing this issue

**Comment by dnsl48** [comment]
Tested locally. Appears to be resolved.
