### ISSUE TITLE
Allow smarter redirection of records not found in a ModelAdmin getList()

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-admin#1073]
It's possible to override getList() in a ModelAdmin to filter the records. This is an effective way of providing a more focused ModelAdmin - e.g. only showing records that in some state suitable for a particular activity a user is undertaking. ModelAdmin isn't phpMyAdmin, it's a tool for building business applications.

However, when you do this, it creates the possibility that you modify the record and after saving it is now excluded from that list. There's a couple of ways of dealing with this:

 * Prevent those changes that would remove it form the list (e.g if the list is filtered on status, the make the status field readonly). This is an option that app developers have, but it can't be done automatically at a framework level. It may also be overly limiting
 * The other option is to redirect to another view where the record _is_ available for editing.

So the logic when opening a detail from for a record would be:
 * If record doesn't exists in the list
 * But if you look up the raw dataClass, and can find a record `DataObject::get_by_id($dataClass, $id)`
 * And it has a CMSEditLink() method
 * Then call that method and redirect to the result.

This would let people implement `CMSEditLink()` in such a way that it defines a backup ModelAdmin where this record can be found. The technique could in principle be expanded to support records that use Versioned and have been deleted – it could link to an archive area instead.

CMSEditLink() is a method name provided by `SilverStripe\ORM\CMSPreviewable` and seems like a good default method. However, not all objects will implement the other methods of CMSPreviewable. As part of this change, it might make sense to implement a companion interface `SilverStripe\Admin\CMSLinkable` that requires only `public function CMSEditLink()`. Any object wanting to tie into this functionality can link to `SilverStripe\Admin\CMSLinkable`.

Given the scope for application-specific behaviour, responsibility for writing CMSEditLink() is left with the specific app.

**Comment by robbieaverill** [comment]
>you modify the record and after saving it is now excluded from that list

Is this something that you'd want to happen? If not, when I read this I wondered whether you could have something consistent for your data type that would keep it in the modeladmin regardless of the status you're changing, e.g. `type = pet`.

**Comment by maxime-rainville** [comment]
Don't think this is worth doing.
