### ISSUE TITLE
Referencing non-existing addTip method

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-admin#1089]
FormField doesn't have an `addTip` method as referenced from the `Tip` component
https://github.com/silverstripe/silverstripe-admin/blob/1/client/src/components/Tip/README.md#L22

**Comment by maxime-rainville** [comment]
@Cheddam Can you double check what happened to the `FormField::addTip()`?

**Comment by Cheddam** [comment]
`Tip`s are currently only supported on `TextField`s (and only render in React contexts), and they will need additional work to be supported in fields with more complex UIs.

If you'd like to expand support to another field type, you'll need to apply the [`TippableFieldInterface`](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/TippableFieldInterface.php) to it, [add the Tip schema to the output](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/TextField.php#L115), and add the Tip component to the field in React.

For now, I've raised a PR to fix the reference in the documentation.

**Comment by maxime-rainville** [comment]
I think the doc PR addressed the specific problem on this issue.
