### ISSUE TITLE
BUG Complex field descriptions render incorrectly

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-admin#1090]
### Affected versions

CMS 4.6.0+

### Description

The field description container was adjusted to use flexbox in [this PR](https://github.com/silverstripe/silverstripe-admin/pull/1042), in service of allowing icons to align with text content. Unfortunately, this had the side-effect of [breaking rendering for descriptions with other HTML content](https://github.com/silverstripe/silverstripe-admin/pull/1042#issuecomment-671009476). This likely wasn't picked up in testing because core doesn't make use of this functionality, but it's helpful and would necessitate workarounds if we chose not to support it.

![image](https://user-images.githubusercontent.com/1168676/89744422-d6e47200-db00-11ea-9e96-5780a98effbd.png)

### ACs

- [x] Revert the original change (in particular, the shift to `display: flex`)
- [x] Ensure the [specific description](https://github.com/silverstripe/silverstripe-userforms/blob/5/code/Model/EditableFormField/EditableFileField.php#L63) this change was made for still renders correctly

Thanks to @michalkleiner for identifying this problem.

### PRs
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1107 (revert in admin 1.5)
- [x] https://github.com/silverstripe/silverstripe-userforms/pull/1002 (redo in userforms 5.6)

**Comment by maxime-rainville** [comment]
@bergice Can you have a look at this when you got a sec?

**Comment by maxime-rainville** [comment]
I'm thinkinging we should probably start phasing out the ability to put raw HTML in the description. This would cause problems when more fields start getting serve as form schema in react.

**Comment by brynwhyman** [comment]
We do document how to use the description field here: https://docs.silverstripe.org/en/4/developer_guides/customising_the_admin_interface/how_tos/cms_formfield_help_text/

**Comment by brynwhyman** [comment]
Looks like another example of this happening with the Advanced Workflow module installed: ![image.png](https://images.zenhubusercontent.com/5b17319354b51e4165e1fd0b/0c946d25-1ade-4033-89ac-18645e8d3e52)

**Comment by emteknetnz** [comment]
The linked PRs have been merged, closing this issue now
