### ISSUE TITLE
Update to reactstrap 8

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1093]
We're currently on 6.5.0 according to yarn.lock

There's at least one [open issue](https://github.com/silverstripe/silverstripe-admin/issues/1067) that requires an upgrade to at least 7.0.0, though it would probably make sense to just go to 8.x.y

**Comment by maxime-rainville** [comment]
That's probably something we should consider doing. Keep in mind that this will probably require us to increment the targeted version of admin in a lot of other module, so it's not a trivial change.

**Comment by brynwhyman** [comment]
This has happened now
