### ISSUE TITLE
Undefined index: dataClass in ArchiveAdmin

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1095]
When navigating to /admin/archive, we now get the following exception thrown that looks as though it was introduced with [this PR](https://github.com/silverstripe/silverstripe-admin/pull/1072)

![image](https://user-images.githubusercontent.com/4809037/90599016-38ff4e80-e248-11ea-986e-211dddfc72d5.png)

**Comment by brynwhyman** [comment]
This was fixed in https://github.com/silverstripe/silverstripe-admin/pull/1101

Also, I believe this bug was only occurring in 1.x-dev branch of silverstripe/admin.
