### ISSUE TITLE
Used on table - row count in tab

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1099]
### Overiview

Adding a count tally to the Used on tab heading would give CMS users a quick indication of whether the file is in use and to what extent.

### Acceptance Criteria
- The count reflects the amount of rows recorded in the used on table

### Early investigation notes

Estimated points: 3

Parent investigation issue silverstripeltd/product-issues#249

![image](https://user-images.githubusercontent.com/4809037/91123629-756ff600-e6f1-11ea-85a3-be844d8de658.png)

Show a file count on the 'Used on' tab without resorting to updating cross component directly with jQuery

The used on tab and the tabs are separate components

Need to investigate how best to get components to talk to each other

The Used on table makes an XHR call to the server to get an array of file usage count data, so easy to the count from the number of rows

**Comment by emteknetnz** [comment]
I think this should be closed and will never get done.

We've implemented [lazy-loading on the used on table](https://github.com/silverstripe/silverstripe-admin/pull/1139/files#diff-fab157d2852a3c5601b52c9f24f9dfa8e248cc6d5067487be82d78eee7bab137R30) to stop the tab from loading in the background which was adding unnecessary server load and thus slowing down the frontend for a feature that wasn't being used most of the time a file was being clicked on.

What this means is that the tab count will be 0 until after you've clicked on the tab, in which time it will be able to show the correct number.  This would be very confusing for the user.

If we wanted to provide a row count, then we could do it at the top of the of the used on table itself, though that probably has pretty limited value to the end-user

**Comment by brynwhyman** [comment]
> I think this issue should now be closed as it seems unlikely to be implemented

Agreed - it seems like the effort involved wouldn't justify the feature any more. If @silverstripeux agree to close the issue, we should also have this removed from the DSM.

**Comment by sachajudd** [comment]
Happy to close this issue since technically it is not able to be implemented the way we initially imagined.
I'll update DSM. Note in the future please do not add screenshots to the issue itself, instead link off to DSM. Designs are continuously worked on and changed, making screenshots old and unreliable sources of information.
