### ISSUE TITLE
Validation icon on form tab

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-admin#1109]
### Overview
There's currently an open enhancement to add better handling to validation messages outside of a form tab that a CMS user has in focus, see: [Validation messages for hidden tabs](https://github.com/silverstripe/silverstripe-cms/issues/2081)

Some [early investigation](https://github.com/silverstripe/silverstripe-admin/pull/1108) into that enhancement has found that there's probably some regressed behaviour at play. 

This issue aims to look at a more immediate fix utilising some of the code that's appeared to regress, with the addition of the icon indicators outlined in [Validation messages for hidden tabs](https://github.com/silverstripe/silverstripe-cms/issues/2081).

### Acceptance criteria
- [x] When a validation error happens in a child tab (i.e. Content > 'Custom-tab') I can clearly identify the tab that it is contained in
- [x] Focus is retained on the form in view when the save was attempted and I am not redirected to the validation error

### Notes
- This has been raised separately from https://github.com/silverstripe/silverstripe-cms/issues/2081 assuming that it will be a quick fix and possible for inclusion in a patch release.

- [x] @sachajudd to raise a PR to add the new icon to the font set. 

- This will not address adding icon indicators in the root tabs, i.e 'Content', 'Settings', etc

### Designs

[CMS Design System - Validation errors PATCH](https://projects.invisionapp.com/dsm/silver-stripe/silverstripe-cms/nav/build/asset/componentContainers/5f629910c7f8596e2ebe93b5/tab/design?mode=preview)

### PRs
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1111

**Comment by brynwhyman** [comment]
Found this issue while looking at this: https://github.com/silverstripe/silverstripe-admin/issues/1110

**Comment by brynwhyman** [comment]
This has been raised separately from https://github.com/silverstripe/silverstripe-cms/issues/2081 assuming that it will be a quick fix and possible for inclusion in a patch release.

**Comment by Cheddam** [comment]
I tested this using the `DataObject::validate()` method, and found that it would render errors on fields, but not top-level errors / messages, and the tab icons did not render.

<details>
<summary>Sample code</summary>

```php
class HomePage extends BaseHomePage
{
    private static $db = [
        'ExampleField' => 'Varchar',
    ];
    
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        
        $fields->addFieldToTab('Root.Test', TextField::create('ExampleField', 'Example Field'));
        
        return $fields;
    }
    
    public function validate()
    {
        $validation = parent::validate();
        
        // Just return a validation error every time
        $validation->addFieldError('ExampleField', 'This field cannot exist.');
        
        return $validation;
    }
}
```

</details>
