### ISSUE TITLE
Fix icon regression + behat test for tab validation icons

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1122]
We intentionally merged https://github.com/silverstripe/silverstripe-admin/pull/1111 without adding any new behat tests because we need a [custom page type](https://github.com/silverstripe/silverstripe-admin/pull/1111#issuecomment-694613669) though we cannot use `implements TestOnly` because that only works for phpunit tests.

The current mechanism for adding custom dataobjects for behat is not a paritcularly good one, it is include [frameworktest](https://github.com/silverstripe/silverstripe-frameworktest) - so perhaps we need to include this as a dev dependency in admin - although that's not preferred.

**Update:** The aim is to put forward a suggestion to add the test fixture to a new module, see: https://github.com/silverstripe/silverstripe-framework/issues/9712

## ACs
- Add the custom dataobject referenced below to the new module (https://github.com/silverstripe/silverstripe-framework/issues/9712
)
- Finalise the behat test (referenced in this issue)
- Ensure that the new module is referenced in the travis file for silverstripe-admin

## Notes
* There is a [behat test written](https://github.com/silverstripe/silverstripe-admin/pull/1111#issuecomment-694643727) (though will need additional work) that can be used

**Comment by emteknetnz** [comment]
Update: the "new module for behat text fixtures" [had cold water poured on it](https://github.com/silverstripe/silverstripe-framework/issues/9712#issuecomment-700335955), and there's no clear way forward

For this reason I'm just going to keep the status quo and add the new fixtures to frameworktest and release a new version of that

**Comment by Cheddam** [comment]
Fixed in #1179.
