### ISSUE TITLE
Can't scroll with the scroll wheel when using  Chromebased MS Edge 

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#1173]
I can't seem to scroll in the CMS with the mouse wheel while using MS Edge on Linux. Chrome works fine.

Replicated in the CMS area, reports, preview and asset-admin.

This may just be a bug with the Linux MS Edge build.

![image](https://user-images.githubusercontent.com/1168676/106549673-587c0080-6576-11eb-9c7b-a3812261c687.png)

**Comment by emteknetnz** [comment]
Can you replicate on windows 10? (could use browserstack)

If not, this is pretty much a non-issue since the install base for edge on linux will be extremely small

**Comment by maxime-rainville** [comment]
After further investigation I concluded that this only affects our CWP 2.7.1 beta test environment. I tested the latest version of Windows Edge and that worked fine as well. I'll see if I can find a place to report bugs for Edge Linux and close this issue since it looks like a browser problem, not a CMS problem.

**Comment by maxime-rainville** [comment]
This morning it's working fine  ¯\_(ツ)_/¯
