### ISSUE TITLE
Safari is looking for a favicon.ico

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-admin#1178]
I got a strange error on a website today. It seems there is a request on ModelAdmin that looks for a favico like this:
admin/[model_admin_segment_here]/favicon.ico

This happens on Safari 13.1 

Maybe it's a new thing that safari doesn't look for favicon in the root? Not sure!

Anyway this causes error like this:
User Error: ModelAdmin::init(): Invalid Model class

I haven't got a mac at hand to test this but I guess that if I get the error in my logs, it happens. Any way to fix this ? Maybe specify
As far as i can tell, the admin doesn't specify any favicon so maybe that's the issue

**Comment by dnsl48** [comment]
Thanks for reporting that. I'm not sure if we can call it an issue with the admin module at this point.
I cannot call this a bug until we have a way to reproduce it consistently. I'll close it for now, but please feel free to reopen if any new details come up.
