### ISSUE TITLE
Broken build (1.7) - various behat - merge-up from 1.6

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1198]
Update: issue seems like it's with chrome 91

Merge up from 1.6 to 1.7 cause the following behat failures
- apply-formatting.feature
- edit-page-page.feature
- insert-a-link.feature

https://travis-ci.com/github/silverstripe/silverstripe-admin/jobs/502767053

Merge-up happens shortly after this pull-request was merged https://github.com/silverstripe/silverstripe-admin/pull/1144/files

PRs
- [x] https://github.com/silverstripe/MinkFacebookWebDriver/pull/11

**Comment by emteknetnz** [comment]
Cannot replicate locally

Tried using the composer.json that very similar travis used (have added admin and removed frameworktest)

```
{
    "name": "silverstripe/abc",
    "description": "SilverStripe admin interface",
    "type": "silverstripe-vendormodule",
    "homepage": "http://silverstripe.org",
    "license": "BSD-3-Clause",
    "keywords": [
        "silverstripe",
        "admin"
    ],
    "authors": [
        {
            "name": "SilverStripe",
            "homepage": "http://silverstripe.com"
        },
        {
            "name": "The SilverStripe Community",
            "homepage": "http://silverstripe.org"
        }
    ],
    "require": {
        "silverstripe/admin": "1.7.x-dev",
        "silverstripe/framework": "^4.5",
        "silverstripe/versioned": "^1@dev",
        "silverstripe/vendor-plugin": "^1.0",
        "php": "^7.1 || ^8",
        "silverstripe/behat-extension": "^4",
        "silverstripe/serve": "^2",
        "silverstripe/installer": "4.7.x-dev"
    },
    "require-dev": {
        "sminnee/phpunit": "^5.7",
        "squizlabs/php_codesniffer": "^3",
        "nikic/php-parser": "^3 || ^4",
        "monolog/monolog": "~1.16"
    },
    "extra": {
        "expose": [
            "client/dist",
            "client/lang",
            "thirdparty"
        ],
        "project-files-installed": [
            ".env.example",
            "app/.htaccess",
            "app/_config.php",
            "app/_config/assets.yml",
            "app/_config/mimevalidator.yml",
            "app/_config/mysite.yml",
            "app/_config/theme.yml",
            "app/src/Page.php",
            "app/src/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "assets/.gitignore",
            "assets/.htaccess",
            "assets/web.config",
            "favicon.ico",
            "index.php",
            "web.config"
        ]
    },
    "autoload": {
        "psr-4": {
            "SilverStripe\\Admin\\": "code/",
            "SilverStripe\\Admin\\Tests\\": "tests/php/",
            "SilverStripe\\Admin\\Tests\\Behat\\Context\\": "tests/behat/src/"
        }
    },
    "scripts": {
        "lint": "phpcs code/ tests/php/",
        "lint-clean": "phpcbf code/ tests/php/"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by emteknetnz** [comment]
Travis is using a beta version of chromium - 91.0.4472.27.  This is ahead of my local with is currently on 87.0.4280.88

Quite possible that there's additional security in this more recent verson preventing access to the HTML field.

**Comment by emteknetnz** [comment]
Attempted to [revert](https://github.com/silverstripe/silverstripe-admin/pull/1201) the pull-request in question.  Reverting did [not fix](https://travis-ci.com/github/silverstripe/silverstripe-admin/jobs/503572988), so seems like something else is going on

**Comment by emteknetnz** [comment]
Installed behat modules versions are the same between builds

**Green build**
behat/behat 3.8.1
behat/gherkin 4.8.0
behat/mink 1.8.1
behat/mink-extension 2.3.1
behat/transliterator 1.3.0
silverstripe/behat-extension 4.4.0

**Red build**
behat/behat 3.8.1
behat/gherkin 4.8.0
behat/mink 1.8.1
behat/mink-extension 2.3.1
behat/transliterator 1.3.0
silverstripe/behat-extension 4.4.0

**Comment by emteknetnz** [comment]
Have branched off the admin commit 037afdd which was green https://travis-ci.com/github/silverstripe/silverstripe-admin/builds/218035808

Have created a temporary branch [pulls/1.7/037afdd](https://github.com/silverstripe/silverstripe-admin/tree/pulls/1.7%2F037afdd) and pushed to the silverstripe account (no pull request via cc's account).  The idea is to create a like-for-like build to validate the issue isn't with the code in admin.  This branch can be deleted once the test is complete

**Comment by emteknetnz** [comment]
Behat / silverstripe minkfacebook webdriver will essentially do this to get the value of the textarea used for HTML content

`$x("(//html/descendant-or-self::textarea[(@class and contains(concat(' ', normalize-space(@class), ' '), ' htmleditor ')) and (@name = 'Content')])[1]")[0].value`

chrome 87
`"<h1 class="text-right">ABC</h1><p>You can fill this page out with your own content, or delete it and create your own pages.</p>"`

chrome 91
`"<h1 class=\"text-right\">ABC</h1><p>You can fill this page out with your own content, or delete it and create your own pages.</p>"`

HTML attributes are quoted, so likely we just need to account for the extra slashes

**Comment by emteknetnz** [comment]
PR has been merged and 1.1.1 tagged

Manually triggered a build on admin
https://travis-ci.com/github/silverstripe/silverstripe-admin/builds/225405754

**Comment by emteknetnz** [comment]
Retagged 1.1.1 which showed up in packagist

Rerunning https://travis-ci.com/github/silverstripe/silverstripe-admin/builds/225535445

**Comment by brynwhyman** [comment]
Noting that the exact same failures are popping up on silverstripe-cms: https://travis-ci.com/github/silverstripe/silverstripe-cms/jobs/504140630

Please check the issue covering those failures after you think this issue is resolved. See: https://github.com/silverstripe/silverstripe-cms/issues/2657
