### ISSUE TITLE
Duplicate Videos in WYSIWYG retain the size, alignment and caption of first instance

### ISSUE THREAD

**Issue by lianna-blanca** [silverstripe/silverstripe-admin#1199]
If you use the same URL twice (or more) to add videos to a WYSIWYG, even on different blocks or pages, whatever is set as the width/size, alignment and caption for the first instance will be put onto all subsequent instances.

Screenshot: Two instances of the same video. Video 1 aligned center, 100px wide (with descriptive caption), Video 2 aligned right, 400px wide, but video 2 displays exactly the same as Video 1.
![image](https://user-images.githubusercontent.com/36834115/117087786-a4705880-ada4-11eb-963b-f4712f239eb3.png)

![image](https://user-images.githubusercontent.com/36834115/117087842-cff34300-ada4-11eb-9c92-4d977b32f743.png)

When the URL is varied (e.g. by adding a query string like `?1` to the end), it is treated like a new URL and can be given new size, caption and alignment.

Side note: the caption text in the CMS editor sits over the video thumbail. 

silverstripe/recipe-cms: 4.7.*
silverstripe/admin: 1.7.3
silverstripe/asset-admin: 1.7.1
silverstripe/campaign-admin: 1.7.1
silverstripe/versioned-admin: 1.7.2

### Implementation notes
- It would be interesting to check other video service providers - is this just YouTube videos?
- Initial thoughts feel like adding an array to how the data is stored should help fix this
- There's caching in the image shortcode provider, added as part of a previous issue with youtube rate limiting, so could be related to that?
- After this fix, we should ensure that videos are still being cached

### PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/9998 << merge this first
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2672

**Comment by emteknetnz** [comment]
PR https://github.com/silverstripe/silverstripe-framework/pull/9998

**Comment by emteknetnz** [comment]
Linked PRs have been merged, closing this one

**Comment by pjayme** [comment]
Hi team, can confirm that using the exact steps above that this issue still exists in `4.8.0`

**Comment by michalkleiner** [comment]
4.8.0 recipe or 4.8.0 CMS? What version of the admin module itself, @pjayme?

**Comment by pjayme** [comment]
Apologies @michalkleiner recipe, `"silverstripe/recipe-cms": "4.8.0"`

**Comment by michalkleiner** [comment]
The merged PR isn't in the latest patch version, so you'd need to install framework from 4.x-dev and alias it to make your composer constraints happy.
