### ISSUE TITLE
Hyphens in `managed_models` keys cause errors

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-admin#1219]
According [to the docs](https://docs.silverstripe.org/en/4/developer_guides/customising_the_admin_interface/modeladmin/#defining-the-modeladmin-models) we should be able to have a `$managed_models` key like so:

```php
        'product-category' => [
            'dataClass' => Category::class,
            'title' => 'Product categories'
        ]
```

However, adding one always results in the error: `ModelAdmin::init(): Invalid Model class`

I believe this is due to the `unsanitiseClassName()` call but I'm setting out to prove it shortly.

# Pull request
- [ ] #1218

**Comment by maxime-rainville** [comment]
One of the test added by the PR is [failing the build on the kitchen sink](https://travis-ci.com/github/silverstripe/cwp-recipe-kitchen-sink/jobs/510738944).

```
1) SilverStripe\Admin\Tests\ModelAdminTest::testMultiModelAdminOpensEachTab
BadMethodCallException: No session available for this HTTPRequest
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/silverstripe/framework/src/Control/HTTPRequest.php:938
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/silverstripe/admin/code/LeftAndMain.php:1667
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/silverstripe/admin/code/LeftAndMain.php:1695
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/silverstripe/subsites/src/Extensions/LeftAndMainSubsites.php:314
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/silverstripe/framework/src/Core/Extensible.php:468
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/silverstripe/framework/src/Control/Controller.php:123
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/silverstripe/admin/tests/php/ModelAdminTest.php:48
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/sminnee/phpunit/phpunit:52
```

**Comment by emteknetnz** [comment]
@max - re-run did not fix issue https://travis-ci.com/github/silverstripe/cwp-recipe-kitchen-sink/jobs/512232011

**Comment by maxime-rainville** [comment]
Third time is the charm https://github.com/silverstripe/silverstripe-admin/pull/1228
