### ISSUE TITLE
Refactor HeaderField to be a functional component

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1227]
Issue to track https://github.com/silverstripe/silverstripe-admin/pull/1223

**Comment by maxime-rainville** [comment]
I've merged the PR ... I'll leave this issue open for a bit so we can make sure the pattern lib rebuilds as expected.

**Comment by maxime-rainville** [comment]
The pattern library got rebuilt. The commit still appear under my name ... maybe it's just because I'm the last one who has committed to the GH action.

Ultimately, I don't think it's a problem.
