### ISSUE TITLE
document data-graphql-legacy

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-admin#1231]
## Affected Version

4.8

## Description

I recently upgraded a website to 4.8. In this website, I have an iframe on a screen and I get this very strange error

/admin.types.graphql 404 (Not Found)

that is triggered by this bit of code

```
return regeneratorRuntime.wrap(function(e) {
                    for (; ; )
                        switch (e.prev = e.next) {
                        case 0:
                            return n = !!document.body.getAttribute("data-graphql-legacy"),
                            o = [t + "assets/admin.types.graphql", t + "admin/graphql/types"],
                            l = void 0,
                            c = void 0,
                            n ? (p || o.reverse(),
                            l = o[0],
                            c = o[1]) : (l = t + "admin.types.graphql",
                            c = null),
                            u = {
                                method: "GET",
                                headers: {
                                    "Content-Type": "application/json"
                                },
                                uri: "" + t,
                                credentials: "same-origin"
                            },
                            d = function() {
                                var e = r(regeneratorRuntime.mark(function e(t) {
                                    return regeneratorRuntime.wrap(function(e) {
```

so I scratched my head a little, it's not big deal since this error does not have any side effect, but it's still really ugly. I then try to add data-graphql-legacy="true" to the body of my iframe: error is gone.

The thing is : what does this do? this seems to enable a legacy behaviour... which does not load types ?
Why with the default behaviour do I get this strange url that is not even scoped in the admin module? (it should be doing t + assets/... but clearly, it doesn't).

Any help is welcome to understand how I should properly use iframes in the cms with the default settings.

**Comment by emteknetnz** [comment]
what version of graphql are you running?

i.e.
`composer show | grep graph`

**Comment by lekoala** [comment]
i get this

```
$ composer show | grep graph
silverstripe/graphql                           3.5.0
webonyx/graphql-php                            v0.12.6
```

i know there is a new graphql module, i need to look into it :) still, a bit like in https://github.com/silverstripe/silverstripe-framework/issues/9978, since this is the default, it should be working already

for a bit of context, i have created this module https://github.com/lekoala/silverstripe-pure-modal which allows creating modals that can contain iframes. Initially, I was using the CMSDialog template and it was working fine but now it isn't anymore. No big deal since i created another template but... I'd like to understand what's happening instead of just make errors go away by chance ;-)

**Comment by emteknetnz** [comment]
graphql-legacy means graphql ^3

Going forward, silverstripe will switch to using graphql ^4 by default at some point

Silverstripe 4.8 added support for both graphql ^3.5 and graphql ^4

If you look at https://github.com/silverstripe/silverstripe-admin/tree/1.8 you'll see there's not a folder `_legacy/GraphQL` which is where the graphql ^3 specific code was moved to.

You can the `data-graphql-legacy` attribute also being used here as part of a commit to add graphql 4 supported https://github.com/silverstripe/silverstripe-admin/commit/6bd63f835b67de8dcb7e7a174f84db2d486d96f9#diff-3a541a572b3a2ac6ac256d4787b20e92879498569ccb4e43de982452f3ba208cR10

Since there's no bug being reported here I'll close this issue

Hope this helps

**Comment by lekoala** [comment]
@emteknetnz i think there is an issue anyway because the error should not happen regardless. At least it should throw some kind of error message or not attempt reaching  /admin.types.graphql
I've also created the following PR that fixes the issue for me
https://github.com/silverstripe/silverstripe-admin/pull/1235
