### ISSUE TITLE
No error handling for non-existient CMS section

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#1232]
If you try to access a CMS section that doesn't exist, you get an unstyled error page. e.g.: Try to access `/admin/boom` in the CMS 

![image](https://user-images.githubusercontent.com/1168676/123539531-59fcce00-d78e-11eb-9f04-f77a501eb8ca.png)

Presuming you are logged in, I would expect to see the left navigation so you can choose a section that does exist and some useful error messages.

## PRs
- https://github.com/silverstripe/silverstripe-errorpage/pull/67
- https://github.com/silverstripe/silverstripe-admin/pull/1317

**Comment by GuySartorelli** [comment]
Closing in favor of https://github.com/silverstripe/silverstripe-cms/issues/2669 as it's effectively a subset of the same problem.
