### ISSUE TITLE
CMS preview doesn't work inside ItemEditForm

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1251]
silverstripe/silverstripe-framework includes a separate form in `GridFieldDetailForm_ItemRequest`'s `ItemEditForm` which `LeftAndMain` doesn't add the necessary components to form CMS previews (`cms-previewable` ExtraClass and `SilverStripeNavigator` field).

I think an extension class should be included as a part of this module which takes advantage of the `updateItemEditForm` extension point of `GridFieldDetailForm_ItemRequest` to add these.

Edit: The following pull requests all ultimately relate to this:
- silverstripe/silverstripe-framework#10112
- #1250
- #1252
- silverstripe/silverstripe-cms#2692
- #1258 
- silverstripe/silverstripe-framework#10124
- silverstripe/silverstripe-admin#1285
- silverstripe/silverstripe-userhelp-content#171

And, as an extension of all of this:
- silverstripe/silverstripe-elemental#936

**Comment by michalkleiner** [comment]
@GuySartorelli moved the issue from the CMS repo. You can relink it in your PR description if you want since it changed its URL/reference now.

**Comment by GuySartorelli** [comment]
Thanks!

**Comment by GuySartorelli** [comment]
> @brynwhyman Let's maybe bring this in sprint.

@maxime-rainville Let me know if there's anything you need from me in that regard.
For now I think I've done all I can until there's some feedback on the PRs.

**Comment by GuySartorelli** [comment]
@emteknetnz It might be worth keeping this ticket open while the other PRs mentioned in the description are still pending - especially docs.

**Comment by emteknetnz** [comment]
Sorry yes intend to keep open, GitHub auto-closed it due to closing a linked PR

**Comment by emteknetnz** [comment]
All PRs have been merged.

Thank you once again @GuySartorelli this was a significant contribution

**Comment by GuySartorelli** [comment]
Thanks for working with me to get it in!
