### ISSUE TITLE
Add multi-select shortcuts for dragging files ("lasso" selection)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#127]
The drag-drop functionality of files is intuitive for single images but when it comes to dragging multiple items it isn't as intuitive. 
Currently you need to check multiple items to drag them, it would be good to be able to select multiple items by dragging an invisible box around items to select them and to be able to use keyboard keys which are native to PC or Mac (eg. shift key and command key for Mac)

## Related

 * [Improvements to select/dragging of files](https://github.com/silverstripe/silverstripe-asset-admin/issues/424)

**Comment by chillu** [comment]
That's already implemented in kickassets, even as a reuseable React component: https://github.com/unclecheese/react-selectable :)

**Comment by chillu** [comment]
Nice to have, but not essential for stable.

**Comment by newleeland** [comment]
@unclecheese has already implemented this selecting option during hackday.

**Comment by chillu** [comment]
Good catch!

**Comment by clarkepaul** [comment]
The lasso work has been done but not the keyboard shortcuts as yet, I know @scott1702 started on it on a hackday so I'll separate that work out into another issue.

**Comment by chillu** [comment]
@clarkepaul Have you created another issue in the meantime? If so, can you link it here please?

**Comment by clarkepaul** [comment]
Related issue for keyboard shortcuts is included in the following issue but could be separated out https://github.com/silverstripe/silverstripe-asset-admin/issues/424
