### ISSUE TITLE
Toast notification CSS regression - 4.10.0-beta1

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1270]
Probably a result of upgrading front-end dependencies

Tested in Firefox

A) Toast notification wrong size
![image](https://user-images.githubusercontent.com/4809037/144518582-b148bd6a-511a-4977-a157-d448a7ef0d09.png)

B) Draft/modified labels in site-tree look different? top right padding more than bottom left, and font may be different?
![image](https://user-images.githubusercontent.com/4809037/144518827-9dca7655-bece-4405-97a1-952ae7374ccc.png)

C) Disabled date field - File manager details 'First uploaded' disabled field looks different, heaps of spacing in time
![image](https://user-images.githubusercontent.com/4809037/144518855-01880d93-aa09-4817-93b1-6c6780bd6797.png)

D) Viewer groups - adding a viewer group e.g. 'Administrators' in File Permission has too much bottom padding
![image](https://user-images.githubusercontent.com/4809037/144518892-57ad7250-1de8-4899-801f-18b99ee8e42f.png)

E) Publish button 'publishing state' 'glow' goes over save button
![image](https://user-images.githubusercontent.com/4809037/144518931-c44f4451-9a0f-4c9c-a9a5-c91bed937091.png)

### Acceptance Criteria
- [ ] Toast padding is restored to what it was in prior version
- [ ] Draft/Modified label padding in CMS sitetree is restored to what it was in prior version

### Notes
- The other points are secondary

### PRs
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1275

**Comment by emteknetnz** [comment]
The Draft/modified label padding and disabled date field formatting are both Firefox 94 specific.  I tried using an earlier version of Firefox (92) and neither regressions were present.  Given they're not particularly bad, and because Firefox has low end-user usage compared to chrome, I'm thinking we just leave them for now, due to the risk of causing regressions in other browsers

**Comment by maxime-rainville** [comment]
I don't think the problem is firefox specific. The label changes when you are editing a page.

![image](https://user-images.githubusercontent.com/1168676/145123011-56753d09-bef6-4190-b5f2-9742ea80b8ff.png)

**Comment by emteknetnz** [comment]
Ah right, however I justed tested that's also present in 4.9.x-dev, so not a beta regression

**Comment by maxime-rainville** [comment]
"A" has been fixed. Split B into a separate issue. https://github.com/silverstripe/silverstripe-cms/issues/2713
