### ISSUE TITLE
Version number gets truncated on 4.10.0-beta1

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#1274]
With `4.10`, we need to display an extra character in that help menu version number. This is getting truncated right now.

![image](https://user-images.githubusercontent.com/1168676/144919055-58c6d228-8f71-458a-9780-32797ee31f08.png)

# Acceptance criteria
- [ ] Any combination of `4.XX` can be displayed in the menu without being truncated.
- [x] The CWP specific logic is removed/deprecated.

# Stretch Goal 
- Update wording to "Silverstripe CMS"

# Related issue
- https://github.com/silverstripe/silverstripe-admin/issues/1256

# PRs
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1276
- [x] https://github.com/silverstripe/cwp-core/pull/105

**Comment by michalkleiner** [comment]
@maxime-rainville https://github.com/silverstripe/silverstripe-admin/pull/1273
You can review and merge it if you're happy with it.

**Comment by clarkepaul** [comment]
If we can lower the middle S of Silverstripe that would be a good addition, don't worry about adding "CMS" to it as it goes over a double line and doesn't look good. Would need to drop the font-size to 11px and thats way too small.

**Comment by maxime-rainville** [comment]
All PRs have been merged.
