### ISSUE TITLE
Pin npm colors to 1.1.2

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1277]
The colors npm module had some malicous commit added to it by the maintainer - https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

Most Silverstripe modules that run yarn build have `colors` in the yarn.lock file for the following deps:
cli-table3 - colors ^1.1.2
svgo: colors ~1.1.2

Currently running `run yarn.lock && yarn install` will add `colors` to `node_modules/colors` version 1.4.2, and `node_modules/svgo/node_modules/colors` version 1.1.2

Pin to `1.1.2` to ensure we don't accidentally upgrade to a malicious version on `yarn upgrade`.  While this is a downgrade to cli-table3, it's still meets its version constraint, so presumably it doesn't make use of the new features in newer versions anyway.  I don't think there's a clean way to get 1.4.0 and 1.1.2 to both install like it does now.

End result is that `node_modules/colors` should install 1.1.2 and there should no longer be a `node_modules/svgo/node_modules/colors` version

Notes:
- the current version in yarn.lock is 1.4.0 i.e. running `yarn install` without any PRs will install 1.4.0
- currently running `yarn upgrade` will upgrade to 1.4.2 (which I believe includes the malicious commit)
- as far as I can tell we don't use the faker module

### PRs
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1278
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1246
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/217
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2715
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/98
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/227
- [x] https://github.com/silverstripe/silverstripe-elemental/pull/952
- [x] https://github.com/silverstripe/silverstripe-login-forms/pull/107

**Comment by maxime-rainville** [comment]
All merged
