### ISSUE TITLE
Calling enablePreview() on the preview panel no longer hides the overlay.

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1292]
Affected version: 1.10

#1086 removed `this.find('.cms-preview-overlay').hide();` in `_unblock()` and `this.find('.cms-preview-overlay').show();` from `_block()` in `client/src/legacy/LeftAndMain.Preview.js` - which was necessary to correctly display the overlay (`.cms-preview-overlay`) when loading the edit form of a page that has no preview, but causes issues when calling `enablePreview()` manually in a non-standard preview situation where a custom project has implemented changes to allow arbitrary `DataObject`s to be previewable.

The problem I'm encountering is that the overlay doesn't get hidden, which results in _not_ displaying the actual preview content.

This is likely to not be an issue in 1.11 with the new preview PRs, but I haven't had a chance to check that yet.

**Comment by emteknetnz** [comment]
Does this cause any issues on a base install of silverstripe/installer 4.10? or do you need to customise the cms in some way for this issue to show up?

**Comment by GuySartorelli** [comment]
A base install won't have an issue, this is only for projects (which will be very few in 4.10) which have customised the CMS to allow non-versioned `DataObject`s to be previewed in a custom `ModelAdmin`.
I mostly raised it in case it has some carry-over effect to the new functionality that will be in 4.11 but now that I look at the date of the PR I can see that won't be the case - probably safe to just close this.
