### ISSUE TITLE
GridField. Remove the message "You are about to lose your changes warning" when navigating away from filtered list

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-admin#1313]
### Description
Get ride of the annoying "You are about to lose your changes warning" when navigating away from filtered list

### Replicate the issue

1. Open page with GridField list of items.
2. Click search button (magnify glass).
3. Click on button to open dropdown menu to open advanced search.
4. Type a keyword.
5. Click search button
6. After search should return a filtered list.
7. Select one of the item
8. Message "Are you sure you want to navigate away from this page? ... " appears. 
 
### AC's
- [ ] "You are about to lose your changes warning" message removed

### SPIKE
- [ ] https://app.zenhub.com/workspaces/cms-squad-5d12de441659a92b9fa61677/issues/silverstripeltd/product-issues/254

### PR 
 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/10384
 - [ ] https://github.com/silverstripe/silverstripe-frameworktest/pull/111
 - [ ] https://github.com/silverstripe/silverstripe-admin/pull/1320

**Comment by GuySartorelli** [comment]
PRs merged, no outstanding tasks. Closing.
