### ISSUE TITLE
GridField. Create Unique URLs for Gridfield state.

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-admin#1314]
### Description
At the moment, there are few issues with navigation in the GridField.

- There is a problem with the "Back" button on the GridField child page in the header. When working with children of a filtered, sorted GridField, or when you are on a specific page, the back control button in the child's header navigates to the first page of an unfiltered, unsorted GridField.

- There is also a problem that it is not possible to create a link to the results of a filtered and sorted GridField list, as well as use the "Back" / "Forward" button in the browser.

### SPIKE 
- https://app.zenhub.com/workspaces/cms-squad-5d12de441659a92b9fa61677/issues/silverstripeltd/product-issues/254

### AC's
- [x] Keep all state in URL via an hash reference that maps to a state store either in the session or local storage.
- [x] URL keeps user's search / sort / pagination parameters.
- [x] Search parameters are stored either an hash mapping to a server side grid state or in session storage.
- [x] Optimise URL to keep long search parameters as well as work with many tabs with different GridFields. 
- [x] When you perform an action in the gridfield, it updates the URL.
- [x] The browser history is hijacked so that the back/next button can be use to navigate your gridfield state.
- [x] Directly accessing a gridfield URL with a state hash restore hydrates that gridfield with that state for the user with a given session.

### Notes
- Need to validate if it's OK to change the URL on every state change and if changing the URL should affect the back button behaviour.
  - e.g.: If you change the sort order 15 times, should it create 15 entries in your history anh require you to click the back button 15 times to get back to your original state.

### PR's
- silverstripe/silverstripe-framework#10331
- https://github.com/silverstripe/silverstripe-admin/pull/1326

**Comment by GuySartorelli** [comment]
PRs merged, no outstanding tasks. Closing.
