### ISSUE TITLE
$ExtraClass in LeftAndMain_ViewModeSelector.ss causing CMS preview button to render full width

### ISSUE THREAD

**Issue by rspcactucker** [silverstripe/silverstripe-admin#1324]
I believe this [PR](https://github.com/silverstripe/silverstripe-admin/pull/1285) has created a problem by introducing `$ExtraClass` in `LeftAndMain_ViewModeSelector.ss`.

Because `$ExtraClass` is not always being passed in via include statements, the template parser will then look further up in scope and obtain `$ExtraClass` from parent objects.  `CMSMain_EditForm.ss` is doing this from `silverstripe/cms`, and as such, the view mode selector receives the `flexbox-area-grow` class.

This has the following result in the CMS:

Before PR merge:

![image](https://user-images.githubusercontent.com/54301657/177912677-1d06663e-94a8-4686-9369-4bfa905f4dc6.png)

After PR merge:

![image](https://user-images.githubusercontent.com/54301657/177912693-c8e1eb19-d3d1-45ef-883f-93bb2f710710.png)

Looks a bit naff. :wink: 

## PRs
- https://github.com/silverstripe/silverstripe-cms/pull/2782
- https://github.com/silverstripe/silverstripe-cms/pull/2787

**Comment by GuySartorelli** [comment]
Fixed by https://github.com/silverstripe/silverstripe-cms/pull/2787
