### ISSUE TITLE
CMSPreviewable objects aren't actually previewable without silverstripe/cms

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1339]
There are several classes that the preview functionality relies on which are in `silverstripe/cms` (namely `SilverStripeNavigator`, `SilverStripeNagivatorItem`, and its subclasses) which are required for the preview functionality.

These classes should be moved into their appropriate modules so that the preview functionality can be used with a project that includes `silverstripe/admin` but does not include `silverstripe/cms`.

## Acceptance criteria
- [x] All documented preview functionality can work without including `silverstripe/cms` (unless the documentation explicitly refers to `SiteTree` or other CMS-specific classes which belong in the cms module).
- [x] Using `$SilverStripeNavigator` in a front-end template still works exactly like it did beforehand
- [x] Breaking changes have been documented on the upgrade docs page
- [x] Changes in functionality or class names are reflected in the appropriate documentation

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1340
- https://github.com/silverstripe/silverstripe-assets/pull/504
- https://github.com/silverstripe/silverstripe-cms/pull/2761
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/253
- https://github.com/silverstripe/developer-docs/pull/60

**Comment by sabina-talipova** [comment]
Previewable successfully has been migrated from silverstripe-cms to silverstripe-admin module
