### ISSUE TITLE
HtmlEditorField changetracker

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-admin#134]
We are getting false-positives for HtmlEditorFields which have extraneous `&nbsp;` characters in their Content, which gets mangled by TinyMCE and turns into blank spaces. This results in the popup "Are you sure you want to leave these unsaved changes?" dialog from appearing even though no changes has been made.

This could prove to impact false-negatives, as users are known to use `&nbsp;` to pad/indent the text on their page. This would mean that if users were only padding/indenting their text without other "meaningful" changes, the popup "Are you sure..." dialog will not appear if the user attempts to browse away, and they will lose their changes without warning.

We'll need to investigate how much of an edge case this could be

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/159

**Comment by dhensby** [comment]
What events are we currently relying on for change tracking or are we self-computing?

[TinyMCE's change event](https://www.tinymce.com/docs/advanced/events/#change) would probably be the best way to tell if there's been a change.

If binding to internal events of the editor isn't a pattern we want to use, then we can use the [`isDirty`](https://www.tinymce.com/docs/api/tinymce/tinymce.editor/#isdirty) state.

**Comment by flamerohr** [comment]
it's a generic field values comparison change tracker https://github.com/silverstripe/silverstripe-admin/blob/master/thirdparty/jquery-changetracker/lib/jquery.changetracker.js#L64

We might revisit this and utilise the isDirty state that tinymce provides :)
the "cleanup" that tinymce does to the html is turning into a lot of friction.
