### ISSUE TITLE
Tidy up array syntax

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1347]
For some reason there are a _lot_ of instances of `array()` instead of `[]` in this module.

## Acceptance criteria
- [x] All instances of `array()` are replaced with `[]`
- [x] phpcs config is updated to check for this.

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1348

**Comment by maxime-rainville** [comment]
Done.
