### ISSUE TITLE
Left-menu icons broken on model admins

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-admin#135]
If you don't specify a specific icon for a model admin, the left-hand menu gets this styling error:

![vapourtape - data linkages 2017-07-04 10-11-07](https://user-images.githubusercontent.com/59968/27809137-2c5c4f9c-60a1-11e7-93e1-e28f834a4d29.png)

Here's a relevant HTML snippet:
![2017-07-04 10-14-10](https://user-images.githubusercontent.com/59968/27809197-92a2469e-60a1-11e7-825c-199f8a6f1f99.png)

**Comment by chillu** [comment]
Given how frequently authors will see this, I'm prioritising a fix

**Comment by phalkunz** [comment]
Pull request: https://github.com/silverstripe/silverstripe-admin/pull/141
