### ISSUE TITLE
SecurityAdmin should extend ModelAdmin

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#1350]
SecurityAdmin while being functionally equivalent in practically every way to a standard ModelAdmin doesn't extend ModelAdmin.

This adds extra technical debt because any fix or new feature we apply to the regular ModelAdmin needs to be replicated in SecurityAdmin.

In CMS5, we should aim to refactor SecurityAdmin to extend ModelAdmin.

## Acceptance criteria
- [x] SecurityAdmin is refactored to extend ModelAdmin and remove redundant logic in CMS5
- [x] It is still possible to import Group and Members
- [x] Review where the warning came from. Remove the "Caution: Removing members from this list will remove them from all groups and the database" warning or talk to Design team to find a better solution.

## Related
- https://github.com/silverstripe/silverstripe-admin/pull/963
- https://github.com/silverstripe/silverstripe-admin/pull/1359
- https://github.com/silverstripe/developer-docs/pull/80
- https://github.com/silverstripe/silverstripe-admin/issues/1302

**Comment by emteknetnz** [comment]
I don't know if we'll even the background to the warning "Caution: Removing members from this list will remove them from all groups and the database" - it was added 11 years ago in Silverstripe 2.4 - https://github.com/silverstripe/silverstripe-cms/commit/033d27ac3f8d4ccae2578774d46fdf445299698f

I think it should just be removed and we do not need any design input here. It seems completely obvious that, yes, when you click the delete button on a record from the thing that manages records, that the record is then deleted :-)

**Comment by GuySartorelli** [comment]
All ACs met and PRs merged.
