### ISSUE TITLE
Deprecate and remove $subitem_class

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1358]
## ACs
- [x] So a string search in silverstripe/recipe-kitchen-sink for `subitem_class`
- [ ] If unused, removed config.  If used, decided what to do with it.
 
Unused config

```php
    private static $subitem_class = Member::class;
```

https://github.com/silverstripe/silverstripe-admin/blob/1/code/SecurityAdmin.php#L45
https://github.com/silverstripe/silverstripe-cms/blob/4/code/Controllers/CMSMain.php#L108

Deprecate in 1/4, remove in 2/5
 
## Pull request
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2817 (CMS4)
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1440 (CMS4)
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2821 (CMS5)
- [ ] https://github.com/silverstripe/developer-docs/pull/134

**Comment by maxime-rainville** [comment]
Did a global search on the vendor folder of the sink and didn't find anything using this `subitem_class` config option.

**Comment by emteknetnz** [comment]
@maxime-rainville Have merged the two deprecation PRs - remember to create CMS 5 PRs to remove the config

**Comment by maxime-rainville** [comment]
There's nothing to do for admin. `subitem_class` was removed when refactoring SecurityAdmin. https://github.com/silverstripe/silverstripe-admin/commit/48108c1b31952b250f1d8c3192e49c05cfc6fa48

**Comment by emteknetnz** [comment]
Linked PRs have been merged
