### ISSUE TITLE
Create tinymce6 skin to match the old tinymce4 one

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1366]
The tinymce4 skin we are using is not at all compatible with tinymce6 and needs to be effectively remade from scratch.
There are instructions here for doing so: https://www.tiny.cloud/docs/tinymce/6/creating-a-skin/#creating-a-skin
Unfortunately the tool mentioned on that page isn't available for timymce6 so it has to be done manually.

## Acceptance criteria
- [x] The tinymce6 editor looks close enough to the how the tinymce4 one did

## Notes:
- It does not need to look identical - people will know it's two majors ahead, so some change in appearance (different icons, etc) is to be expected
- The main goal is that it fits in seemlessly into the general content author experience and doesn't look out of place

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1371

**Comment by sabina-talipova** [comment]
TinyMCE 6 works and looks perfect!
