### ISSUE TITLE
CMS 4.12: Archive admin is broken

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1379]
Archive admin doesn't load, because it overrides `getManagedModels()` and doesn't include a `dataClass` key.
There are likely other `ModelAdmin` subclasses that do this to, so instead of just patching archive admin, we should make `ModelAdmin` not assume that key will always be there.

## Acceptance criteria
- [x] Archive Admin works again.

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1380

## Notes:
It's probably worth spinning off a card for CMS 5 to officially require `'dataClass'` being a key in the array.

**Comment by michalkleiner** [comment]
@GuySartorelli PR approved and merged, did you want to do a patch release?

**Comment by GuySartorelli** [comment]
Awesome, thank you.
A patch release wouldn't be appropriate in this case - the problem was only present in the `4` branch (aka 4.12) which hasn't had a stable release yet.

Closing as this has been merged.
