### ISSUE TITLE
Current member name is always truncated on desktop 

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-admin#139]
Not a fan of the current logged in member's name always being truncated on desktop:

![](http://spdr.me/oBvDTJ+)

Ideally ellipsis truncation should be for edge cases only, such as odd screen sizes or very long names, but currently, most names will get truncated on standard desktop screens.

Maybe only display first name if space is restricted?

(Introduced in #105)

**Comment by dhensby** [comment]
I think using firstname only is reasonable, especially given the casual salutation.
