### ISSUE TITLE
Allow telephone (tel:) links in TinyMCE

### ISSUE THREAD

**Issue by scott1702** [silverstripe/silverstripe-admin#1390]
In the same way that we allow users to link to [email addresses](https://github.com/silverstripe/silverstripe-admin/blob/d3fc48cde0aef36518d0b7efd11dd5711bef6be4/client/src/legacy/TinyMCE_sslink-email.js) in TinyMCE, we should also allow users to add telephone links i.e. `tel:123123123`

**Comment by lozcalver** [comment]
Just in case you’re not aware, this does exist as a module :smile: https://github.com/firebrandhq/silverstripe-phonelink

**Comment by GuySartorelli** [comment]
This isn't something we're likely to implement and support out of the box at this stage - especially given there is a community module which provides this functionality.
