### ISSUE TITLE
4.12 regression: Search bar's filter button takes all half the with in some context

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#1398]
We recently introduce an option to spell out the full "Search options". The problem is that when in a constrain space (e.g. like the page search), that takes half of the available width

![image.png](https://images.zenhubusercontent.com/5ac42fb74b5806bc2bcd8e13/b6abd5e5-06b3-4e96-9edf-7f48d008882a)

## Acceptance criteria
- [ ] If the Search bar is less than 640px, the Search options button displays only has a down arrow.

## Note
- Maxime did a magical ResizeAware component that detects how width the search bar is and will allow you to resize elements accordingly.

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1407

**Comment by GuySartorelli** [comment]
PR merged
