### ISSUE TITLE
CMS 5: React context no longer has "You have unsaved changes" confirm dialog

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1409]
https://github.com/silverstripe/silverstripe-admin/issues/1312 results in some regressions which we've decided to handle as separate issues. This is one of those.

React contexts (such as asset-admin and possibly campaign-admin) used to have a "You have unsaved changes" confirm dialog which would be triggered if you tried to navigate away without saving your changes. This was part of react-router, but that functionality is not included with react-router 6.x - so we need to implement it another way.

## Acceptance criteria
- [x] When a user has unsaved changes and tries to navigate in a react context, a confirm dialog is presented asking if they way to navigate away or not
- [x] If the user selects "no" or "cancel" they do not navigate away and can save their changes
- [x] If the user selects "yes" or "ok" they are navigated away and lose their changes

## Notes
- ~~react-router uses [history](https://github.com/remix-run/history) under the hood. We may be able to utilise its [blocking transitions](https://github.com/remix-run/history/blob/dev/docs/blocking-transitions.md) functionality.~~ It looks like despite _saying_ they use this under the hood, they don't _actually_ use this.
- ~~[react-beforeunload](https://www.npmjs.com/package/react-beforeunload) is another possible way to implement this~~ This might be useful _in addition_ to any solution we come up with, but it doesn't actually handle routing _within_ the app, only _out_ of it.
- There is a lot of discussion about this along with other potential solutions in [this issue thread](https://github.com/remix-run/react-router/issues/8139) which is where the above options came from
    - Seems like [they've added support for this](https://github.com/remix-run/react-router/blob/3a44ce30353f89d57386b75e90e05a79b18b2525/decisions/0001-use-blocker.md) in 6.7 which wasn't available when I did the original upgrade. Lets go with that.
    - Docs are still being written so the only thing we have to go on is [this limited example](https://github.com/remix-run/react-router/blob/main/examples/navigation-blocking/src/app.tsx) and [the source code](https://github.com/remix-run/react-router/blob/2b843a6739c6807e683de9097e20909e78f0a1bd/packages/react-router/lib/hooks.tsx#L842)
- Yes we can technically downgrade to the previous version, however while that version is still maintained for now it doesn't get the same attention as v6. It's better for us to keep the upgrade if we can.

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1458
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1335
- https://github.com/silverstripe/developer-docs/pull/168

**Comment by emteknetnz** [comment]
Linked PRs have been merged
