### ISSUE TITLE
CMS 5: Still using various deprecated lifecycle events which should be avoided

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1414]
https://github.com/silverstripe/silverstripe-admin/issues/1312 results in some regressions which we've decided to handle as separate issues. This is one of those.

Many of our react components implement a `componentWillReceiveProps` method. This results in a console warning that this method is deprecated. We should refactor our components to not use this method to avoid upgrade pains in the future.
There may be other deprecated lifecycle events in use as well.

## Acceptance Criteria
- [ ] None of the react components in supported modules use `componentWillReceiveProps`
- [ ] No other deprecated lifecycle events are used in supported modules

## Notes
- see [this blog post](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) which includes more information and suggestions for alternative solutions for the problems this method typically solves.
- If it comes to a point where it's just too hard to refactor, we can use `npx react-codemod rename-unsafe-lifecycles` to suppress console warnings - but that should be a last resort (we'll have to remove them eventually)

## PRs
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/280
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1343
- https://github.com/silverstripe/silverstripe-admin/pull/1490

**Comment by maxime-rainville** [comment]
Sadly we will not get to this in CMS5.

**Comment by GuySartorelli** [comment]
Reopening - we could happily do this in a minor and it does need to be done eventually.

**Comment by emteknetnz** [comment]
As far as I can tell we've overestimated the amount of work required in this issue, I could only find a single relevant component that needed updating. 

All the other components were updated as part of https://github.com/silverstripe/silverstripe-admin/issues/1312

I search searched sink 5.0 for the following strings that would mean the deprecated lifecycle methods are actually being called:
- "componentWillMount("
- "componentWillReceiveProps("
- "componentWillUpdate("

It only matched bundle.js style files + the 2x files included in the PRs above

**Comment by GuySartorelli** [comment]
The following still need to be updated:
- a comment in asset-admin `client/src/containers/Gallery/Gallery.js` that mentions `componentWillReceiveProps`
- a test in asset-admin `client/src/components/UploadField/tests/UploadField-test.js` that mentions `componentWillReceiveProps`

**Comment by GuySartorelli** [comment]
PRs merged
