### ISSUE TITLE
CMS 5: Fix broken JavaScript tests

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1421]
In some modules, javascript tests are broken after https://github.com/silverstripe/silverstripe-admin/issues/1312
For those modules, I removed the `yarn test` command from `yarn build` so that the resources can be built.

The tests must be fixed and passing, then `yarn test` must be added back into the `yarn build` command.
Use https://github.com/silverstripe/silverstripe-admin/pull/1389 as an example of some changes you may need and acceptable workarounds (e.g. resorting to react 16 for tests, for now)

## Acceptance Criteria
- [x] `yarn test` runs without failures on all modules
- [x] `yarn test` is added back into the `yarn build` command

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1456
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1330
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/256
- https://github.com/silverstripe/silverstripe-cms/pull/2834
- https://github.com/silverstripe/silverstripe-session-manager/pull/128
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/274

**Comment by GuySartorelli** [comment]
Should the following be added?
- silverstripe/campaign-admin
- silverstripe/errorpage
- silverstripe/reports

**Comment by emteknetnz** [comment]
Linked PRs have been merged
