### ISSUE TITLE
ul.ui-autocomplete placement is broken with 1.12

### ISSUE THREAD

**Issue by lerni** [silverstripe/silverstripe-admin#1423]
Updating form 1.11.3 to 1.12.0 broke placement of dropdown-suggestions from `GridFieldAddExistingAutocompleter`. With 1.12 they are in the upper left corner of the admin interface or viewport you could say.

### Installer CI run
- https://github.com/emteknetnz/silverstripe-installer/actions/runs/3898125750

### PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1424
- https://github.com/silverstripe/silverstripe-cms/pull/2815

**Comment by GuySartorelli** [comment]
Released as [1.12.1](https://github.com/silverstripe/silverstripe-admin/releases/tag/1.12.1)
@lerni Thanks for reporting this.
