### ISSUE TITLE
Revisit JS linting

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1433]
It was decided to suppress new JS linting issues before the CMS 5 beta in [this issue](https://github.com/silverstripe/silverstripe-admin/issues/1411) as it was causing CI failures when PR's were otherwise fine

We should work out what new rules we wish to keep and re-enable them. See the PRs linked from the above issue for the rules which were suppressed.

## Acceptance criteria
- [ ] Each disabled linting rules have been reviewed and a concious decision has been made about whether to keep them or not.
- [ ] JS modules have been updated to pass all linting rules.

## When deciding if a rule should be enabled consider
- Does the rule avoid common pitfalls that are likely to introduce errors in the code?
- Can the rule be fix with automated linting tools?
- Is the rule mostly stylistic and would require a lot of manual work to fix?

#### ESLint config
- https://github.com/silverstripe/eslint-config/pull/17
- https://github.com/silverstripe/eslint-config/pull/18

#### Fixed modules
- https://github.com/silverstripe/silverstripe-admin/pull/1532
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1371
- https://github.com/silverstripe/silverstripe-blog/pull/714
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/271
- https://github.com/silverstripe/silverstripe-cms/pull/2865
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/114
- https://github.com/silverstripe/silverstripe-mfa/pull/501
- https://github.com/silverstripe/silverstripe-realme/pull/114
- https://github.com/silverstripe/silverstripe-session-manager/pull/157
- https://github.com/silverstripe/silverstripe-tagfield/pull/248
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/125
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/297
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/145
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/198
- https://github.com/silverstripe/cwp-agencyextensions/pull/97
- https://github.com/silverstripe/silverstripe-elemental/pull/1070
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/497

## Update eslint version
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/200
- https://github.com/silverstripe/cwp-agencyextensions/pull/98
- https://github.com/silverstripe/silverstripe-elemental/pull/1075
- https://github.com/silverstripe/silverstripe-admin/pull/1535
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1373
- https://github.com/silverstripe/silverstripe-blog/pull/716
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/273
- https://github.com/silverstripe/silverstripe-cms/pull/2868
- https://github.com/silverstripe/silverstripe-contentreview/pull/205
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/118
- https://github.com/silverstripe/silverstripe-externallinks/pull/104
- https://github.com/silverstripe/silverstripe-frameworktest/pull/145
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/84
- https://github.com/silverstripe/silverstripe-login-forms/pull/143
- https://github.com/silverstripe/silverstripe-lumberjack/pull/124
- https://github.com/silverstripe/silverstripe-mfa/pull/503
- https://github.com/silverstripe/silverstripe-realme/pull/115
- https://github.com/silverstripe/silverstripe-segment-field/pull/83
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/67
- https://github.com/silverstripe/silverstripe-subsites/pull/530
- https://github.com/silverstripe/silverstripe-tagfield/pull/250
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/128
- https://github.com/silverstripe/silverstripe-userforms/pull/1222
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/299
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/147
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/498
- https://github.com/symbiote/silverstripe-multivaluefield/pull/97

**Comment by GuySartorelli** [comment]
Related: https://github.com/silverstripe/silverstripe-admin/issues/1437

**Comment by sabina-talipova** [comment]
List of [eslint rules](https://docs.google.com/spreadsheets/d/1YNNP8sM-Ir6NcsJcfZzVYASZa5IGM9RmgKOdDF4NhdA/edit?usp=sharing) that using in CMS5.

**Comment by sabina-talipova** [comment]
As a solution you can use the [Prettier](https://prettier.io/docs/en/index.html) to fix some minor eslint issues.

**Comment by emteknetnz** [comment]
@sabina-talipova looks like you've gone outside the bounds of the issue description which was to look at the linting rules that were disabled as part as the airbnb rules npm package being upgraded which happened during the webpack upgrade for CMS 5.

Looking at these PRs there are a large number of trailing commas that were added - looks like this was the `comma-dangle` rules which wasn't one of the rules that were originally disabled as part of the CMS 5 upgrade.  I have a pretty strong dislike for this change, particularly when it's done inside a method call so would like this reverted.

I also dislike the assignment by deconstruction so would like to see this also reverted.

Also - I would have expected more changes given the large number of rules that were re-enabled - did you copy paste the updated eslint config to every supported moudle that uses javascript and run yarn lint?

**Comment by sabina-talipova** [comment]
> Also - I would have expected more changes given the large number of rules that were re-enabled - did you copy paste the updated eslint config to every supported moudle that uses javascript and run yarn lint?

@emteknetnz, I fixed each module that use `@silverstripe\eslint-config`.  I copied edited `.eslintrc.js` file into each module. Some of them passed eslint testing, so there were not any changes to do, so I didn't created PR for them.

> Looking at these PRs there are a large number of trailing commas that were added - looks like this was the comma-dangle rules which wasn't one of the rules that were originally disabled as part of the CMS 5 upgrade. I have a pretty strong dislike for this change, particularly when it's done inside a method call so would like this reverted.

> I also dislike the assignment by deconstruction so would like to see this also reverted. 

Could you please finish your review and I'll fix all together.
You could start with this [PR](https://github.com/silverstripe/eslint-config/pull/17), I appended the links to the rules, so it will be easy for you to define which one we should use.

**Comment by emteknetnz** [comment]
I'm not sure what rules are necessary to turn off, you've probably got a much better understanding from me?

I'd rather not have to peer review each file individually, this applies too all of them
- Please remove all the new trailing commas and associated rule(s)
- Please remove the assignment by deconstruction and associated rules(s)
- I've seen several instances of rules being disabled being added e.g. `/* eslint-disable func-names */` - seems like we shouldn't be doing this and instead just not disable the rule globally

**Comment by emteknetnz** [comment]
@sabina-talipova I've published `@silverstripe/eslint-config` 1.1.0

Could you please do the following:
- Merge this new [pull-request](https://github.com/silverstripe/eslint-config/pull/18) which updates the version in package.json
- Create new pull-requests where you run `yarn upgrade` on the `5` branches that were updated so that they have new yarn.lock files that include the updated `.eslintrc`.  You may as well also run `yarn build` while you're at.  Give these PR's a `DEP` prefix
