### ISSUE TITLE
CMS 5: Final js build when we go RC

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1436]
Currently we are using alpha builds of https://www.npmjs.com/package/@silverstripe/webpack-config and https://www.npmjs.com/package/@silverstripe/eslint-config in our modules.
This is locked in the `yarn.lock` files.

When we are gearing up for a RC, we should release _stable_ versions of the NPM packages, then do a final `yarn upgrade @silverstripe/webpack-config @silverstripe/eslint-config` and `yarn build` in all of the modules. This will ensure that all modules are using the correct versions of those libraries and avoid running into issues with them post-stable.

## Acceptance Criteria
- We tag stable relesaes of @silverstripe/webpack-config and @silverstripe/eslint-config
- All CMS5 modules that rely on webpack config and eslint config use latest version

## PRs
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/194
- https://github.com/silverstripe/cwp-agencyextensions/pull/89
- https://github.com/silverstripe/silverstripe-elemental/pull/1050
- https://github.com/silverstripe/silverstripe-admin/pull/1493
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1347
- https://github.com/silverstripe/silverstripe-blog/pull/706
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/262
- https://github.com/silverstripe/silverstripe-ckan-registry/pull/289
- https://github.com/silverstripe/silverstripe-cms/pull/2847
- https://github.com/silverstripe/silverstripe-comments/pull/367
- https://github.com/silverstripe/silverstripe-contentreview/pull/194
- https://github.com/silverstripe/silverstripe-documentconverter/pull/43
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/105
- https://github.com/silverstripe/silverstripe-externallinks/pull/99
- https://github.com/silverstripe/silverstripe-frameworktest/pull/139
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/75
- https://github.com/silverstripe/silverstripe-login-forms/pull/137
- https://github.com/silverstripe/silverstripe-lumberjack/pull/120
- https://github.com/silverstripe/silverstripe-mfa/pull/493
- https://github.com/silverstripe/silverstripe-realme/pull/98
- https://github.com/silverstripe/silverstripe-segment-field/pull/79
- https://github.com/silverstripe/silverstripe-session-manager/pull/141
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/192
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/63
- https://github.com/silverstripe/silverstripe-subsites/pull/520
- https://github.com/silverstripe/silverstripe-tagfield/pull/238
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/117
- https://github.com/silverstripe/silverstripe-userforms/pull/1202
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/282
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/134
- https://github.com/silverstripe/silverstripe-widgets/pull/199
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/486
- https://github.com/symbiote/silverstripe-multivaluefield/pull/94
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/791

**Comment by maxime-rainville** [comment]
All PRs have been merged.
