### ISSUE TITLE
Make javascript non-minified when running yarn dev

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1439]
In webpack-config for CMS 5 only, javascript is being minified when running `yarn dev`.  It's not minified in CMS 4 which makes debugging far easier.

### ACs
- Javascript is not minified when running `yarn dev`
- Javascript is minified when running `yarn build`

### PRs
- https://github.com/silverstripe/webpack-config/pull/58

**Comment by GuySartorelli** [comment]
Merged. Assigning to @emteknetnz to publish to npm
