### ISSUE TITLE
Bad data used to build default importers map

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-admin#1448]
https://github.com/silverstripe/silverstripe-admin/blob/cd1271f86ba890a6d6378794bb58fd320751d29f/code/ModelAdmin.php#L616

The default importer fetch function supposes that the key for each managed model definition is the `dataClass`, but this is normlised to be in the `dataClass` key. The key from getManagedModels could be a URL Slug for which to load the managed model under, and not be valid class name at all. This results in an error when attempting to import data as the key is undefined when referenced in `import()`

**Comment by GuySartorelli** [comment]
This has been fixed in other issues

**Comment by NightJar** [comment]
Are you sure? Because the code looks exactly the same.
$k is still set as $k in the managed models normalisation, not $v as the comment alludes to.
https://github.com/silverstripe/silverstripe-admin/blob/d86471ce61974cc8140cd1b652a14882d6097440/code/ModelAdmin.php#L487 (current branch `2` HEAD)

**Comment by GuySartorelli** [comment]
We have a unit test confirming that the correct model importer is used based on the model tab or class, whichever is appropriate for that config setup.
https://github.com/silverstripe/silverstripe-admin/blob/d86471ce61974cc8140cd1b652a14882d6097440/tests/php/ModelAdminTest.php#L166-L174

Unless you can show that this isn't working as expected in practice, I have no reason to think it isn't working as expected.

**Comment by NightJar** [comment]
OK.

>The key from getManagedModels could be a URL Slug [...] results in an error when attempting to import data
