### ISSUE TITLE
CMS 5 - Popper in not a constructor

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1452]
Mousing over the bottom left hand of the admin triggers the following javascript error

![image](https://user-images.githubusercontent.com/4809037/215887122-0d8b5996-d0a8-47d8-9562-da897f633b05.png)

### PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1487

**Comment by GuySartorelli** [comment]
Merged
