### ISSUE TITLE
CMS5: Model Admin has doubled search button

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#1478]
CMS 5 has doubled the Search button on Gridfield.

![image.png](https://images.zenhubusercontent.com/5ac42fb74b5806bc2bcd8e13/3da9ad62-4110-4d70-90b9-c2e5ad23ff05)

## Acceptance criteria
- Only the top button remains.
- Plain Gridfield search still works.

## Notes
- ~~Might be related to https://github.com/silverstripe/silverstripe-framework/pull/10733, but not sure.~~
- I've only seen it in CMS5, but didn't test it in the most up-to-date version of CMS4

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10736

**Comment by GuySartorelli** [comment]
Merged and confirmed it only affected CMS 5
