### ISSUE TITLE
4.12 Member login without CMS access still displays CMS

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-admin#1479]
As of Silverstripe 4.12 (4.11 and 5.0 do not have this issue), when a member without CMS access tries to log into `/admin`, rather than receiving the frontend error message of `I'm sorry, but you can't access that part of the CMS. If you want to log in as someone else, do so below.` they are directed to the CMS displaying a message `Sorry, it seems the action you were trying to perform is forbidden.`

Expected result:

![Expected](https://user-images.githubusercontent.com/1463435/227399855-ed3992ff-1349-4c7d-a9e4-ed98f97120f2.png)

Current result (Silverstripe 4.12):

![Current](https://user-images.githubusercontent.com/1463435/227399887-82c68f3a-7f89-442b-a2f9-d7a48fa22a0c.png)

Am I missing something, or is this a bug?

**Comment by michalkleiner** [comment]
@axllent this has been fixed and released in https://github.com/silverstripe/silverstripe-admin/releases/tag/1.12.3, can you check you've updated to the latest version of the admin module?

**Comment by axllent** [comment]
@michalkleiner Oh how silly of me, I didn't check the latest patch releases of 4.12 (I was testing on 1.12.2)! You are absolutely correct, this has been fixed. My apologies, and thank you.
