### ISSUE TITLE
Linked tabs 404 when Silverstripe 5 is installed in a subfolder

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-admin#1495]
This maybe more a framework issue but noting here because it's being experienced in the admin area. It looks like Silverstripe 5 is being too aggressive at stripping segments from linked tabs such as other model admin tabs or settings & history on pages. For example given Silverstripe 5 is installed in a subfolder of the www root (for example `/ss_clients/silverstripe5`), clicking on a model admin tab (or settings, history, or content on pages) results in a 404.

The url that is requested by the JavaScript is `http://localhost/ss_clients/admin/pages/settings/show/1` rather than the expected `http://localhost/ss_clients/silverstripe5/admin/pages/settings/show/1`. Interestingly the link on the tab is correct, if you right click on the tab and open the link that way (i.e without the JS request) it works fine. The same thing happens in model admin.

composer.json:
```json
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": "^8.1",
        "silverstripe/recipe-plugin": "^2",
        "silverstripe/vendor-plugin": "~2.0.0@stable",
        "silverstripe/recipe-cms": "~5.0.0@rc",
        "silverstripe-themes/simple": "~3.2.0",
        "silverstripe/login-forms": "~5.0.0@rc"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5"
    },
    "extra": {
        "project-files-installed": [
            ".htaccess",
            "app/.htaccess",
            "app/_config.php",
            "app/_config/mimevalidator.yml",
            "app/_config/mysite.yml",
            "app/src/Page.php",
            "app/src/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600,
        "allow-plugins": {
            "composer/installers": true,
            "silverstripe/recipe-plugin": true,
            "silverstripe/vendor-plugin": true
        }
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}
```

Note: hosting platform is Windows 10, with Apache and PHP 8.2.

## Acceptance criteria
- Tab link works when site is installed in a sub folder
- Common CMS functionally is reviewed when installed in a sub folder

## Related
- https://github.com/silverstripe/silverstripe-admin/issues/1494

## PR
- https://github.com/silverstripe/silverstripe-admin/pull/1499

**Comment by michalkleiner** [comment]
Might be relevant to removing the base tag from the admin template and not correctly passing the path to the JS instead. I can't find the issue where that's been done to reference it here, but there's one.

**Comment by GuySartorelli** [comment]
> For example given Silverstripe 5 is installed in a subfolder of the www root (for example /ss_clients/silverstripe5)

Can you please provide the configuration you use to set up this scenario? That will make it a lot easier to reproduce.

**Comment by maxime-rainville** [comment]
This is a blocker for CMS5 stable release

**Comment by UndefinedOffset** [comment]
@GuySartorelli For simplicity sake for you to reproduce I was able to reproduce this issue on a Ubuntu Server 22.04 default install in a VM with PHP 8.1. Only adding a few PHP dependencies for Silverstripe that are not included in the default install of Ubuntu Server. Then I just installed Silverstripe into `/var/www/html/silverstripe5` using `composer create-project silverstripe/installer@5.0.0-rc1 silverstripe5`. Note on a default Ubuntu Server 22.04 install `/var/www/html` is the web root.

**Comment by GuySartorelli** [comment]
@UndefinedOffset Are you saying you didn't add any configuration to tell Silverstripe CMS that it's running in a subfolder?

**Comment by UndefinedOffset** [comment]
@GuySartorelli I've set the `SS_BASE_URL` and it has the same affect as mentioned in the opening comment and in #1494. There's no change in behavior.

**Comment by sabina-talipova** [comment]
Issue has been solved. Close issue.
