### ISSUE TITLE
Regression: Allow help links to be disabled in user code

### ISSUE THREAD

**Issue by nathanbrauer** [silverstripe/silverstripe-admin#1536]
As requested in https://github.com/silverstripe/silverstripe-cms/issues/1020, #156 added the ability to disable the `help_link`.

In the upgrade from `help_link` to `help_links`, #615 seems to have inadvertently removed this.

The following are expected to work, but now result in `[Warning] foreach() argument must be of type array|object, bool given`:
```yaml
SilverStripe\Admin\LeftAndMain:
  help_links: false
```
```yaml
SilverStripe\Admin\LeftAndMain:
  help_links: null
```

For good measure, I did try the following and it is not effective:
```yaml
SilverStripe\Admin\LeftAndMain:
  help_links: []
```

### PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1572

**Comment by GuySartorelli** [comment]
PR merged
