### ISSUE TITLE
`CMSProfileController` should use `required_permission_codes`

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1537]
Currently there's no way to modify the permissions required for accessing `CMSProfileController`.

There are limited use cases for this - but we shouldn't prohibit people from doing this when they do want to do it.

## Acceptance criteria
- Default permissions are the current required permissions
- The same mechanism that other `LeftAndMain` use to validate permissions is used for `CMSProfileController`
- Permissions required to access `CMSProfileController` can be changed with yaml config

## PR
- https://github.com/silverstripe/silverstripe-admin/pull/1027

**Comment by GuySartorelli** [comment]
PR merged.

**Comment by emteknetnz** [comment]
Unfortunately we'll need to revert this one, it caused some regressions. https://github.com/silverstripe/silverstripe-admin/pull/1555

**Comment by GuySartorelli** [comment]
Turns out we're (probably) not reverting this, as the regression is actually caused by incomplete permission checks in the subsites module.
I'll close this issue for now and we can re-re-open if the subsites thing doesn't pan out.
