### ISSUE TITLE
CMS 5: Cannot link an image in TinyMCE

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-admin#1548]
## Description
As of Silverstripe 5 it is not possible to link just an image within TinyMCE.

### Steps to reproduce:
1. Insert image into editor
2. Select image, click link (any of "Page on this site", file, external URL etc)
3. Add/select link, click "Insert link" button

All attempts fail because of `Link text is required.`. If you fill in any link text (which you shouldn't have to anyway), that text replaces the image.

## Behat tests
This fix involves multiple related pull requests - I have run a CI run with silverstripe/installer with all of the pull requests included to show that they work when they're all installed.
- **CMS 4:** https://github.com/creative-commoners/silverstripe-installer/actions/runs/6091324603
- **CMS 5:** https://github.com/creative-commoners/silverstripe-installer/actions/runs/6105659894

## PR
**CMS 4**
- https://github.com/silverstripe/silverstripe-admin/pull/1570
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1393
- https://github.com/silverstripe/silverstripe-admin/pull/1571
- https://github.com/silverstripe/silverstripe-cms/pull/2880
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1394
- https://github.com/silverstripe/silverstripe-behat-extension/pull/248
- https://github.com/silverstripe/silverstripe-admin/pull/1577
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1397
- https://github.com/silverstripe/silverstripe-cms/pull/2883

**CMS 5**
- https://github.com/silverstripe/silverstripe-admin/pull/1579
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1398
- https://github.com/silverstripe/silverstripe-cms/pull/2884
- https://github.com/silverstripe/silverstripe-behat-extension/pull/249

**Comment by maxime-rainville** [comment]
I'm getting the same behaviour on CMS 4.

Interestingly, it works if you are trying to link to a file in CMS 4. In CMS5, it lets you create the link, but doesn't seem to save it.

**Comment by emteknetnz** [comment]
Linked PRs have been merged

**Comment by GuySartorelli** [comment]
Reopening to make sure the fix works for CMS 5 on merge up since tinyMCE changed a lot between majors

**Comment by emteknetnz** [comment]
Linked PRs have been merged
