### ISSUE TITLE
Source Code view in HTML Editor only shows two line of text

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#1560]
![image](https://github.com/silverstripe/silverstripe-admin/assets/1168676/ae7e421e-4e0c-449a-850e-a0f5376bbedc)

This only affects CMS 5.x-dev. 5.0.x-dev looks fine.

Something has changed in TinMCE. So imply applying a new CSS rule might not be the most appropriate solution.

## PRs
 - https://github.com/silverstripe/silverstripe-admin/pull/1561
 - https://github.com/silverstripe/silverstripe-admin/pull/1566

**Comment by emteknetnz** [comment]
Old working
![image](https://github.com/silverstripe/silverstripe-admin/assets/4809037/93109ab7-4461-4f11-9c9b-2fc5e1fbb37f)

New broken
![image](https://github.com/silverstripe/silverstripe-admin/assets/4809037/a995029a-d773-4a4f-bc66-5ce9b2470683)

Requires ?flush=1 to be run after changing commits for breaking/fixing to show up

first breaks in 383740a

Is still broken after updating js in https://github.com/silverstripe/silverstripe-admin/pull/1558

`tox-textarea-wrap` doesn't exist in a search of the code base of the last working version da1bddc, though it exists in 383740a in my instances under the client/dist/tinymce directory.  So I guess the regression got introduced after updating to a newer version of the tinymce library

**Comment by emteknetnz** [comment]
Is still broken after updating js in https://github.com/silverstripe/silverstripe-admin/pull/1558

**Comment by GuySartorelli** [comment]
PR merged
