### ISSUE TITLE
First field doesn't get focus when user opens "Search options" block.

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-admin#1565]
## Description
The first field that the query `form.querySelector('input')` receives in the "Search options" is of type hidden and we cannot get focus on it, so we must exclude this field from the filter
## PR
- https://github.com/silverstripe/silverstripe-admin/pull/1567
- https://github.com/silverstripe/silverstripe-admin/pull/1568

**Comment by GuySartorelli** [comment]
PR merged. Will be automatically tagged when CI finished running on the branch.
