### ISSUE TITLE
GridField filter doesn't reset the GridField state for pagination links

### ISSUE THREAD

**Issue by rasstislav** [silverstripe/silverstripe-admin#1573]
Hello,

I think this is bug. 

### Description

After canceling the term from the search, the term remains remembered and I cannot reset it.

### Steps to reproduce:

1. Enter the search term and press Enter.
2. Cancel the search term (eg by clicking the X).
3. Go to the next page in pagination.

**BUG: The search term is returned back.**

I am attaching short video.

https://github.com/silverstripe/silverstripe-admin/assets/9253113/0464946b-9321-4d21-acd9-36bcddd12823

## Acceptance criteria
- When the search criteria is cleared, you are returned to the first page.
- When any search criteria is altered, you are returned to the first page.
- Sorting is unaffected by changing the search term

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1580

**Comment by GuySartorelli** [comment]
Yup, definitely a bug. Looks like the gridfield state is still retained after you clear the filters and passed through the pagination links. It's almost certainly related to the changes in https://github.com/silverstripe/silverstripe-framework/pull/10331
Would you like to take a crack at submitting a PR to fix this?

**Comment by sabina-talipova** [comment]
PRs merged. It will be automatically tagged. Close issue.
