### ISSUE TITLE
yarn build bundle.js is randomly different between runs

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1582]
The order of client/dist/js/bundle.js is sometimes randomly changes in 1.13 between subsequent runs on `yarn build` between despite no changes in the client/src

This was noticed during this [PR](https://github.com/silverstripe/silverstripe-admin/pull/1580)

I'm believe this only affects CMS 4 which uses webpack 3.  I was unable to replicate on CMS 5 using webpack 5 using the code code changes in GridField.js that the linked PR above has

I did try adding ` && rm -rf client/dist/*` to the `yarn build` command in `package.json` for CMS 4, just CMS 5 has, though it did not fix the issue

Doing a text-compare of the first 1,000 lines of bundle.js adding line breaks of every semicolon:

![image_720](https://github.com/silverstripe/silverstripe-admin/assets/4809037/455d3304-4363-44a3-a052-a37009f2bf00)

![image](https://github.com/silverstripe/silverstripe-admin/assets/4809037/a71297ad-9fe8-47ca-aef6-a758f84d9a9f)

## PRs
- https://github.com/silverstripe/gha-run-tests/pull/19

**Comment by GuySartorelli** [comment]
Is this a duplicate of https://github.com/silverstripe/gha-run-tests/issues/11?

**Comment by emteknetnz** [comment]
I don't know, we didn't isolate the cause of the issue on the one you linked.  The symptom looks the same (modified bundle.js file) thought the cause may be different

**Comment by emteknetnz** [comment]
Re-ran github actions build a copy of time post merging the PR that outputs the sha1sum, it changes between runs on github actions as well so it's not isolated to local environments

github actions run A
4fe821cac444d5fd2d17f09740730fc1dbc4c2c4  client/dist/js/bundle.js

github actions run B (haven't changed code, just clicked re-run button)
a76c9557b1fb415eb4439a20d3376ce4273a7a9b  client/dist/js/bundle.js

**Comment by emteknetnz** [comment]
Look to have resolved by running `yarn upgrade webpack`
