### ISSUE TITLE
SPIKE Identify options for a comprehensive way of creating API endpoints in the CMS

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#1591]
Parent issue: https://github.com/silverstripe/silverstripe-admin/issues/1589

## Context

Before going to far down with https://github.com/silverstripe/silverstripe-admin/issues/1589, we want to better understand our options, so we can split up the card in sensible ways.

## Acceptance criteria
- We've identified several options/approaches to implementing API endpoints in the CMS.
- For each options we have pros and cons.

**Comment by emteknetnz** [comment]
I've done a deep dive and created a [spreadsheet](https://docs.google.com/spreadsheets/d/1eDIYISJbQP4R1J0WggW_5k4uv4gDjJJKApEQwvLCyhY/edit#gid=0) comparing the following API solutions:
- Adhoc controllers
- RestfulServer
- GraphQL
- REST-API ([new module](https://github.com/emteknetnz/silverstripe-rest-api/) I've been working on)

**Comment by GuySartorelli** [comment]
I've added a few comments but on the whole this looks good as-is. Probably no changes are required as a result of my comments, which are mostly opinions, but reassigned to Steve to make that determination.
Also assigned to Max to take a look as this will likely guide the direction of various epics.

**Comment by maxime-rainville** [comment]
I only had a passing glance. So this is still very preliminary in my mind.

Honestly, it's not exactly what I had in mind. I was thinking more along the lines of "let's define a convenient place to park REST endpoints in the CMS" ... something like a slightly more evolved version of "Adhoc Controllers".

Maybe have some controller that maps to `/admin/api` where you can register end points. Your endpoints could be glorified extensions or some slightly more sophisticated class that implement some common pattern.

I'll have a deeper look over the next few days, but I suspect one of the outcome will be "explore a 5th or a 6th option" along what I just describe.

**Comment by GuySartorelli** [comment]
What you're describing sounds a lot like what Steve built.

**Comment by maxime-rainville** [comment]
We've reviewed the options and have a path forward.
