### ISSUE TITLE
TODO: GridFieldTable Component refactoring

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-admin#1597]
## Description
You should analyze the `GridFieldTable Component` and determine whether this component requires `props.data`. If not, then we should remove this value from the component.
See: 
- https://github.com/silverstripe/silverstripe-admin/blob/0f18b3d40972d421f2756b6b90b55283dfc6fea2/client/src/components/GridField/GridFieldTable.js#L39
- https://github.com/silverstripe/silverstripe-admin/blob/0f18b3d40972d421f2756b6b90b55283dfc6fea2/client/src/components/GridField/GridFieldTable.js#L19

**Comment by GuySartorelli** [comment]
Closing as I don't think we need the additional generation logic but it's also not worth our time right now to remove the unused prop.
