### ISSUE TITLE
Validation on fields are visually attached to the fields (requires gap)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#160]
There should be a gap between validation messages and the field. We are using Bootstrap defaults as far as I'm aware so referring to that might help.
![image](https://user-images.githubusercontent.com/555033/28401185-665b6ed0-6d6c-11e7-8e31-a995e0b09087.png)

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/234
~https://github.com/silverstripe/silverstripe-framework/pull/7354~

**Comment by clarkepaul** [comment]
It seems we are no longer using Bootstrap messages for fields, we should re-align ourselves with Bootstrap 4 methods and classes (ie. use .is-invalid and .is-valid) as demonstrated here https://getbootstrap.com/docs/4.0/components/forms/#validation

**Comment by chillu** [comment]
See https://github.com/silverstripe/silverstripe-framework/issues/6223 for a wider task for agreeing on an error message style
