### ISSUE TITLE
TODO: FormBuilderLoader.getMessages - define standard message type

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-admin#1602]
## Description
Define in FormBuilderLoader.getMessages() function message type as standard "success", "info", "warning" and "danger".
See: https://github.com/silverstripe/silverstripe-admin/blob/0f18b3d40972d421f2756b6b90b55283dfc6fea2/client/src/containers/FormBuilderLoader/FormBuilderLoader.js#L69

**Comment by GuySartorelli** [comment]
Closing as that would be detrimental to any custom types defined in project code
