### ISSUE TITLE
TODO: LeftAndMain entwine enhancement 

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-admin#1603]
## Description
- [ ] Automatically switch to the tab/position of the first error. (see LeftAndMain.submitForm()). [See](https://github.com/silverstripe/silverstripe-admin/blob/0f18b3d40972d421f2756b6b90b55283dfc6fea2/client/src/legacy/LeftAndMain.js#L475)
- [ ] Replaces trailing slashes added by History after locale (e.g. admin/?locale=en/). (see LeftAndMain.submitForm()). [See](https://github.com/silverstripe/silverstripe-admin/blob/0f18b3d40972d421f2756b6b90b55283dfc6fea2/client/src/legacy/LeftAndMain.js#L487)

**Comment by GuySartorelli** [comment]
Closing as neither of these seem particularly beneficial - most likely if we do end up doing the first one it'll be part of a larger work on improving validation UX and not because of this issue specifically.
