### ISSUE TITLE
TODO: injectGraphql.js - investigate converting context to a callback.

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-admin#1607]
## Description
Investigate converting context to a callback which returns context, performance may be an issue.
See https://github.com/silverstripe/silverstripe-admin/blob/0f18b3d40972d421f2756b6b90b55283dfc6fea2/client/src/lib/dependency-injection/injectGraphql.js#L8

**Comment by GuySartorelli** [comment]
Closing, doesn't seem useful and as noted it may be detrimental to performance.
