### ISSUE TITLE
Performance implications caused by deprecation system on tree load

### ISSUE THREAD

**Issue by AljosaB** [silverstripe/silverstripe-admin#1622]
## Description
We have noticed lately when upgrading our bigger projects to latest v4 and v5 versions that /admin performance gets seriously degraded. After long investigation I found the problem to be related to Deprecation class and loading of tree view (/admin/pages/treeview). It only stands out when there is a larger amount of pages in DB. It doesn't matter if those pages are child pages of some other page deeper in the structure or hidden by for example Lumberjack module.

## Steps to Reproduce
- install latest SS
- open admin + browser dev tools and monitor the time it takes to load /admin/pages/treeview (it takes around 2 seconds in my case)
- run the FillDBTask provided below to add 300k of pages to DB (under home page)
- refresh the /admin to measure treeview load again (in my case it goes to a whopping ~50s)

**/app/src/FillDBTask.php**
```php
<?php

namespace Innovatif\Tasks;

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Dev\BuildTask;
use SilverStripe\ORM\DB;

class FillDBTask extends BuildTask
{
    protected $title = 'Fill DB task';
    protected $description = 'Fill DB with pages';

    public function run($request)
    {
        $date = date('Y-m-d H:i:s.000');
        $parentID = 1;
        
        for ($x = 1; $x < 30; $x++) {
            $existingRecords = DB::query('SELECT max(ID) FROM SiteTree')->value();
            $sort = SiteTree::get()->filter('ParentID', $parentID)->count() + 1;
            
            if (DB::get_conn()->supportsTransactions()) {
                DB::get_conn()->transactionStart();
            }
                
            for ($i = 1; $i < 10000; $i++) {
                $recordID = $i + $existingRecords;
                $url = "test-page-$recordID";
                $title = "Test page $recordID";
    
                DB::query("INSERT INTO SiteTree (ID, ClassName, LastEdited, Created, CanViewType, CanEditType, Version, URLSegment, Title, MenuTitle, Content, MetaDescription, ExtraMeta, ShowInMenus, ShowInSearch, Sort, HasBrokenFile, HasBrokenLink, ReportClass, ParentID) VALUES($recordID, 'Page', '$date', '$date', 'Inherit', 'Inherit', 2, '$url', '$title', NULL, '<p>Test</p>', NULL, NULL, 1, 1, $sort, 0, 0, NULL, $parentID);");
                DB::query("INSERT INTO SiteTree_Live (ID, ClassName, LastEdited, Created, CanViewType, CanEditType, Version, URLSegment, Title, MenuTitle, Content, MetaDescription, ExtraMeta, ShowInMenus, ShowInSearch, Sort, HasBrokenFile, HasBrokenLink, ReportClass, ParentID) VALUES($recordID, 'Page', '$date', '$date', 'Inherit', 'Inherit', 2, '$url', '$title', NULL, '<p>Test</p>', NULL, NULL, 1, 1, $sort, 0, 0, NULL, $parentID)");
                DB::query("INSERT INTO SiteTree_Versions (ID, RecordID, Version, WasPublished, WasDeleted, WasDraft, AuthorID, PublisherID, ClassName, LastEdited, Created, CanViewType, CanEditType, URLSegment, Title, MenuTitle, Content, MetaDescription, ExtraMeta, ShowInMenus, ShowInSearch, Sort, HasBrokenFile, HasBrokenLink, ReportClass, ParentID) VALUES(" . ((($existingRecords + $i) * 2) - 1) . ", $recordID, 1, 0, 0, 1, 0, 0, 'Page', '$date', '$date', 'Inherit', 'Inherit', '$url', '$title', NULL, '<p>Test</p>', NULL, NULL, 0, 0, $sort, 0, 0, NULL, $parentID);");
                DB::query("INSERT INTO SiteTree_Versions (ID, RecordID, Version, WasPublished, WasDeleted, WasDraft, AuthorID, PublisherID, ClassName, LastEdited, Created, CanViewType, CanEditType, URLSegment, Title, MenuTitle, Content, MetaDescription, ExtraMeta, ShowInMenus, ShowInSearch, Sort, HasBrokenFile, HasBrokenLink, ReportClass, ParentID) VALUES(" . (($existingRecords + $i) * 2) . ", $recordID, 2, 1, 0, 1, 0, 0, 'Page', '$date', '$date', 'Inherit', 'Inherit', '$url', '$title', NULL, '<p>Test</p>', NULL, NULL, 0, 0, $sort, 0, 0, NULL, $parentID);");
                
                $sort++;
            }
            
            if (DB::get_conn()->supportsTransactions()) {
                DB::get_conn()->transactionEnd();
            }
        }        
    }
}
```

## The problem
I don't know when the Deprecation system has been added, but after some profiling I found out that Deprecation::isEnabled() function gets called **a lot** and consequently calls Director::isDev() which is the real time consumer. Commenting out Director::isDev() as demonstrated below changes loading time of treeview from 50s -> 10s which is an enormous boost.

**/vendor/silverstripe/framework/src/Dev/Deprecation.php**
```php
    public static function isEnabled(): bool
    {
        /*
        if (!Director::isDev()) {
            return false;
        }
        */

        if (Environment::hasEnv('SS_DEPRECATION_ENABLED')) {
            $envVar = Environment::getEnv('SS_DEPRECATION_ENABLED');
            return self::varAsBoolean($envVar);
        }
        return static::$currentlyEnabled;
    }
```

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11053

**Comment by lozcalver** [comment]
I can’t reproduce this locally with DDEV, after running the population task `/admin/pages/treeview` takes ~750ms to load, commenting out the `Director::isDev()` check doesn’t seem to make any difference to that figure. I’m not sure why commenting out that check would make such a huge difference for you - do you see the same difference if you replace that call with `Environment::getEnv('SS_ENVIRONMENT_TYPE') !== 'dev'`?

**Comment by lozcalver** [comment]
Actually I suspect the reason I’m not seeing any difference is that I don’t have any code that triggers `Deprecation::notice()` in my project - are you able to investigate why that’s being called?

**Comment by AljosaB** [comment]
Thank you for fast response!

**My environment**
SS 4.13
PHP 7.4
MariaDB

**Measurements**
![1](https://github.com/silverstripe/silverstripe-admin/assets/1818329/9f305ddb-8102-46ce-b137-8b58c69c9110)

![2](https://github.com/silverstripe/silverstripe-admin/assets/1818329/e9e3cf31-3869-45f7-9344-0198d14d5a80)


Replacing `Director::isDev()` with `Environment::getEnv('SS_ENVIRONMENT_TYPE') !== 'dev'` fixes the problem and I get 10s load time for treeview (big improvement!). My guess would be `Director::isDev()` is calling `Director::get_environment_type()` which is calls `Injector::inst()` that takes up most time somehow.

Why all these deprecations are triggered is a good question as I'm using the default install. Most calls seems to be from BaseKernel and Query classes. Any ideas?

**Comment by lozcalver** [comment]
Ah so the problem is actually in SS4, not SS5? I think the only way we could fix this in SS4 would be to identify any _core_ code that’s triggering a deprecation notice and fix/update that (if possible).

Based on your screenshot above, I’m guessing most of the calls are coming from here: 

https://github.com/silverstripe/silverstripe-framework/blob/4c76ec6102063ddebc151e228d76d8e2b2189a92/src/Core/BaseKernel.php#L300-L309

There’s no obvious fix here, as there’s no API in `Deprecation` to only trigger a warning once. We could hack in a class property, or an inline `static $hasTriggeredDeprecation = false;` inside the method, to track whether the notice has been triggered previously, but those are both code smells. Given that `sessionEnvironment()` has been removed for SS5 _maybe_ that’s okay?

**Comment by AljosaB** [comment]
I've upgraded SS to v5 and used the same DB and I can confirm that the problem doesn't exist anymore, the loading time even fell to 2s.

Most calls come from Kernel and Query classes indeed. As we still have plenty of 4.x projects, any kind of fix is welcome, the best one would be the option to completely disable the deprecation system.

**Comment by GuySartorelli** [comment]
You've mentioned the deprecation system as being the reason it's slow, but that looks like a red herring. The `Deprecation::notice()` method [exits early](https://github.com/silverstripe/silverstripe-framework/blob/4c76ec6102063ddebc151e228d76d8e2b2189a92/src/Dev/Deprecation.php#L368-L371) if deprecations are disabled, and `Deprecation::withNoReplacement()` won't add much overhead. I think it's just that the deprecated way of fetching the environment type from the session is slow (which is likely part of the reason it was deprecated in the first place).

**Comment by AljosaB** [comment]
@GuySartorelli you are indeed correct, fetching environment type is indeed what adds the time, but on the other side it's the deprecation system that triggers it 2 million times in this case.

I understand the problems don't exist in v5 and focus is not on v4 anymore, but we still have many projects running on v4 and are not expected to be ported to v5 in the near future, so any kind of fix would be greatly appreciated.

**Comment by lozcalver** [comment]
@AljosaB as a workaround, calling this in `_config.php` _might_ help (untested), as it should then hit the early-return in [`BaseKernel::getEnvironment()`](https://github.com/silverstripe/silverstripe-framework/blob/4c76ec6102063ddebc151e228d76d8e2b2189a92/src/Core/BaseKernel.php#L273-L276):

```php
$kernel = Injector::inst()->get(Kernel::class);
$kernel->setEnvironment(Environment::getEnv('SS_ENVIRONMENT_TYPE'));
```

I’m not sure we really _can_ fix this in SS4 without A) removing the session environment lookup, which would break backward compatibility, or B) removing the deprecation warning, which would cause upgrade headaches because people won't know they're using deprecated code.

**Comment by AljosaB** [comment]
Thank you for the suggestion!

I tested the provided suggestion which improved the loading speed from 50s -> 22s. Although it's a nice improvement, it's still 22s :thinking: 

Suggestion - checking if deprecation is enabled first instead of checking for env mode in `Deprecation::isEnabled()` shouldn't break anything and gives me 10s total. (code below)

```php
    public static function isEnabled(): bool
    {
        if (!Director::isDev()) {
            return false;
        }

        if (Environment::hasEnv('SS_DEPRECATION_ENABLED')) {
            $envVar = Environment::getEnv('SS_DEPRECATION_ENABLED');
            return self::varAsBoolean($envVar);
        }
        return static::$currentlyEnabled;
    }
```

to

```php
    public static function isEnabled(): bool
    {
        if (Environment::hasEnv('SS_DEPRECATION_ENABLED')) {
            $envVar = Environment::getEnv('SS_DEPRECATION_ENABLED');
            return self::varAsBoolean($envVar);
        }

        if (!Director::isDev()) {
            return false;
        }

        return static::$currentlyEnabled;
    }
```

Not sure, but maybe v5 could benefit also?

**Comment by GuySartorelli** [comment]
Nice one, that's easy to apply and has no chance of regression that I can see. A PR is up.

**Comment by GuySartorelli** [comment]
This has now been fixed and will be automatically tagged in silverstripe/framework by GitHub Actions.
@AljosaB After it's been tagged, if you still have problems with it, let me know and we can reopen this issue and discuss further.

Edit: https://github.com/silverstripe/silverstripe-framework/releases/tag/4.13.33

**Comment by GuySartorelli** [comment]
FYI @AljosaB https://github.com/silverstripe/silverstripe-framework/issues/11054
