### ISSUE TITLE
Toast and escape characters in utf8

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-admin#1639]
### Module version(s) affected

2.1.5

### Description

This is related to https://github.com/silverstripe/silverstripe-framework/issues/11089

Currently, toast messages are escaped using Convert::raw2xml. This means that characters like ' are escaped to their utf8 equivalent (eg: X-Status: Saved Viewing "test event&#039;s ...)
But the js itself doesn't do anything to display this properly

See here the status message handler

https://github.com/silverstripe/silverstripe-admin/blob/ef1385a7fe015890e56bf0fc652dca01678efb71/client/src/legacy/LeftAndMain.js#L1511-L1514

On top of that, the method used to escape the characters (that should already be safe, but still) is not optimal (see https://stackoverflow.com/questions/1147359/how-to-decode-html-entities-using-jquery/) since adding this in a div could still execute malicious code. Ideally, that should be a standard way to escape strings across the framework without having custom bits of code like this.

### How to reproduce

- Go to model admin to a record with a ' in the name
- Click save
- Discover the utf8 encoded ' that is not displayed properly in the toast message

<img width="509" alt="image" src="https://github.com/silverstripe/silverstripe-admin/assets/250762/8109cb41-5cbe-4ea4-ac8d-8aba0f9c7f63">

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11105
- https://github.com/silverstripe/silverstripe-admin/pull/1640
- https://github.com/silverstripe/silverstripe-versioned/pull/438
- https://github.com/silverstripe/silverstripe-versioned/pull/440

**Comment by lekoala** [comment]
WIP

Using this works for the single quote

```js
function decodeEntities(encodedString) {
  var textArea = document.createElement('textarea');
  textArea.innerHTML = encodedString;
  return textArea.value;
}
```

but doesn't help with ö so there is more to it that it seems

**Comment by lekoala** [comment]
Two pr to fix this

https://github.com/silverstripe/silverstripe-framework/pull/11105
https://github.com/silverstripe/silverstripe-admin/pull/1640

**Comment by GuySartorelli** [comment]
This is mostly fixed now - but `&` is still being escaped to `&amp;`

**Comment by GuySartorelli** [comment]
All PRs now merged. Anything that hasn't yet been tagged will be automagically tagged by GitHub Actions.
