### ISSUE TITLE
jQuery missing

### ISSUE THREAD

**Issue by seppzzz** [silverstripe/silverstripe-admin#1641]
### Module version(s) affected

4.13

### Description

the directory thirdparty / jquery is missing

This is used eg by https://github.com/symbiote
/
[silverstripe-memberprofiles](https://github.com/symbiote/silverstripe-memberprofiles)

so its throwing an error

### How to reproduce

missing directory

### Possible Solution

add directory

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by lozcalver** [comment]
This needs to be fixed in the module itself: https://github.com/symbiote/silverstripe-memberprofiles/issues/184
