### ISSUE TITLE
Order of insert link options keeps changing

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#165]
I'm not sure what triggers the link order to change, but I tested over a ten-minute time frame, might have happened after navigating away to the page preview and back (can't always replicate this pattern though).  This was originally noted by through user testing.

Over a ten minute time frame:
![image](https://user-images.githubusercontent.com/555033/28498672-b22d7fb0-6ff6-11e7-956e-3acf3436360e.png)
![image](https://user-images.githubusercontent.com/555033/28498674-b97c6718-6ff6-11e7-91ce-fee20eea5d37.png)

Be good if we could fix this order. We group links to internal and external together and "add a link to a file" at the bottom, as its the second easiest location to reach (least cognitive load). i.e.

"Page on this site"
"Link to external URL"
"Link to email address"
"Link to a file"

## AC's
As a user, I want the links dropdown options to be in the same area so that I don't need to keep figuring out where the options are.

**Task**
Fix the order of the dropdown options to the following order:
"Page on this site"
"Link to external URL"
"Link to email address"
"Link to a file"

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/196
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1924

**Comment by newleeland** [comment]
Could we fix this order. We group links to internal and external together, and add link to a file at the bottom, as its the second most easiest location to reach (least cognitive load).

"Page on this site"
"Link to external URL"
"Link to email address"
"Link to a file"
