### ISSUE TITLE
Submitting a FormBuilder form submits all FormBuilder forms

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1662]
If there are multiple FormBuilder forms at once, submitting one will submit all of them

This bug was worked around on the following PRs:
- https://github.com/silverstripe/silverstripe-linkfield/pull/190
- https://github.com/silverstripe/silverstripe-elemental/pull/1133

We should:
- Work out a way to prevent this from happening
- Remove the workaround code in the two PRs above

## Acceptance criteria
- When submitting a nested form builder form, only the form attached to the action that triggered the submission gets submitted.
- Hack working around this bug are removed.

## Related
- https://github.com/silverstripe/silverstripe-admin/pull/1631

## INSTALLER CI RUN
This CI run shows the PRs working nicely together.
- https://github.com/creative-commoners/silverstripe-installer/actions/runs/8058908144

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1694
- https://github.com/silverstripe/silverstripe-elemental/pull/1151
- https://github.com/silverstripe/silverstripe-linkfield/pull/239
- https://github.com/silverstripe/silverstripe-behat-extension/pull/266

**Comment by maxime-rainville** [comment]
Just to clarify, is the problem only for nested form builders. Or if you have two form builders next to each other without one containing the other, will one form submit the other?

**Comment by emteknetnz** [comment]
I'm not sure if the asset-admin form builder that was getting submitted in the first example was even technically nested, it just an a human user level it appears to be nested.

I don't know if it makes a different if they're nested or not, it felt very much like there was some sort of 'submit event' being broadcast that was the was being subscribed to

**Comment by sabina-talipova** [comment]
PRs have been merged. Task is completed.
