### ISSUE TITLE
Refactor FormBuliderModal to seperate the FormSchema concern from the Modal concern

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#1677]
The FormBuilderModal component displays a FormSchema in a Modal.

The current implementation mixes those two concerns in class component that makes it difficult to figure out what is going on.

The attached PRs do the following:
- Move the modal logic to a dedicated Modal component including some test coverage.
- Convert what's left of FormBuilderModal to be a functional component
- Add Modal to our webpack-config so it can be used in other context.

The signature for the FormBuilderModal is identical so anything that was using the modal prior to this should still work.

## Pull request
- https://github.com/silverstripe/silverstripe-admin/pull/1631
- https://github.com/silverstripe/webpack-config/pull/66

**Comment by emteknetnz** [comment]
I'll sort out publishing on NPM on this issue https://github.com/silverstripe/webpack-config/issues/67
