### ISSUE TITLE
Can’t import a CSV into security users or groups

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#168]
Tested on SS4 Beta1 UAT and local master, import CSV fails even before selecting a file most of the time but it has allowed the selection of a file another time which also failed.
![image](https://user-images.githubusercontent.com/555033/28520917-969fd1b0-70c5-11e7-8b7b-04d9244298a4.png)

**Comment by clarkepaul** [comment]
Might be same issue https://github.com/silverstripe/silverstripe-framework/issues/7162

**Comment by chillu** [comment]
Yep, closing as a duplicate
