### ISSUE TITLE
"Undefined index" error when accessing some model admins

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1686]
### Module version(s) affected

4.13.x

### Description

Some model admins get this error when you try to access them:

``` text
[Notice] Undefined index: dataClass
GET /admin/registry/
Line 626 in /var/www/html/vendor/silverstripe/admin/code/ModelAdmin.php
```

The `isset()` is checking for the wrong thing.

### How to reproduce

Install [frameworktest](https://github.com/silverstripe/silverstripe-frameworktest), then go to the `registry` admin. It should blow up immediately.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1687

**Comment by emteknetnz** [comment]
Linked PR has been merged, it will auto-tag shortly
