### ISSUE TITLE
`SearchableDropdownField` doesn't work in form modal

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1690]
### Module version(s) affected

5.x-dev (unreleased feature for 5.2)

### Description

In an upload field, if you select "choose existing" and then click on a file, the "permissions" tab of the form on the right doesn't show the "viewer groups" and "editor groups" fields. These are `SearchableDropdownField` in 5.x-dev.

With `yarn dev` in silverstripe/admin, you get the following console output:

```text
Uncaught exception TypeError: schema is undefined
    onmatch SearchableDropdownFieldEntwine.js:16
```

When you insert the file, you get this console output:
```text
Uncaught exception TypeError: Root is undefined
    onunmatch SearchableDropdownFieldEntwine.js:27
```

### How to reproduce

1. In any upload field, click "choose existing"
1. Click on a file, but don't insert it yet
1. Look in the "permissions" tab in the form on the right.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PR
- https://github.com/silverstripe/silverstripe-admin/pull/1698
- https://github.com/silverstripe/silverstripe-admin/pull/1699

**Comment by GuySartorelli** [comment]
PR merged.

As per https://github.com/silverstripe/silverstripe-admin/pull/1699#issuecomment-1979549915 I'll leave it up to you to decide whether to close this issue and raise a separate one about `TreeDropdownField` not displaying, or whether you want to work on that as part of the existing issue.

**Comment by sabina-talipova** [comment]
New issue for TreeDropdownField was open. https://github.com/silverstripe/silverstripe-admin/issues/1701
Close this ticket.
