### ISSUE TITLE
DateField requires fallback/shiv for unsupported browsers

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-admin#17]
Issues found (morning of 1 May)

* [x] the following js modules should be exposed imported as an external library
  * [x] moment
  * [x] modernizr
* [x] Date format seems to hold as placeholder <img width="424" alt="screen shot 2017-05-01 at 11 30 14 am" src="https://cloud.githubusercontent.com/assets/1064889/25568981/95958cac-2e61-11e7-8c6e-a176fcb871a8.png">

## Pull Requests
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/47

<details>
The value for a date field in react is taken literally, when it's expected to receive a iso8601 formatted date...

![screen shot 2017-04-06 at 11 04 11 am](https://cloud.githubusercontent.com/assets/1064889/24730648/f2254924-1ab8-11e7-9554-7c915a7731cc.png)

![screen shot 2017-04-06 at 11 07 37 am](https://cloud.githubusercontent.com/assets/1064889/24730701/42d86932-1ab9-11e7-8101-57aeddd2b4da.png)

Related to https://github.com/silverstripe/silverstripe-framework/issues/6140
</details>

**Comment by phalkunz** [comment]
This will be fixed by https://github.com/silverstripe/silverstripe-framework/issues/6140.

**Comment by sminnee** [comment]
Moving this to peer review for testing on Monday as it's allegedly fixed now.

**Comment by tractorcow** [comment]
Placeholders issue fixed with https://github.com/silverstripe/silverstripe-admin/pull/48
