### ISSUE TITLE
"Manage roles" link in CMS returns Invalid Model Class

### ISSUE THREAD

**Issue by mandrew** [silverstripe/silverstripe-admin#1700]
### Module version(s) affected

5.0.4

### Description

When clicking on the "manage roles" link inside of groups > roles, the redirect returns the error below.

SilverStripe log error:
`Uncaught Exception RuntimeException: "ModelAdmin::init(): Invalid Model class show" at /var/www/html/vendor/silverstripe/admin/code/ModelAdmin.php line 164 {"exception":"[object] (RuntimeException(code: 0): ModelAdmin::init(): Invalid Model class show at /var/www/html/vendor/silverstripe/admin/code/ModelAdmin.php:164)"} []`

### How to reproduce

- Within CMS, select Security
- Select "Groups" tab
- Select "Administrators"
- Go to "Roles" tab
- Select "Manage Roles" link .. observe error: 
![error](https://github.com/silverstripe/silverstripe-admin/assets/343938/bcab7d5a-7d57-48f7-9bef-1d9878088a3d)

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## Acceptance criteria
- Clicking tho "manage roles" link takes you to the "Roles" tab in the root of Security Admin
- Our behat test suite is reviewed to make sure that it covers the Role feature. Minimally the following scenarios should be covered:
  - You can create a new role
  - You can add permission to a role
  - You can assigned a role to a group
  - You can click the "Manage Roles" link
- Cuccumber studio includes at least one test case with Roles (Testing team will add this)
 
## Notes
- Testing team might have opinion on what the write for cuccumber studio, so it give a heads up tot hem that we are adding this test.
- This works in CMS 4
- We'll create a follow up crad about reviewing that UI for CMS 6

## PRs
[installer CI run](https://github.com/creative-commoners/silverstripe-installer/actions/runs/8350845011)
- https://github.com/silverstripe/silverstripe-framework/pull/11178
- https://github.com/silverstripe/silverstripe-behat-extension/pull/267
- https://github.com/silverstripe/silverstripe-admin/pull/1712

**Comment by maxime-rainville** [comment]
That's a CMS 5 only bug. CMS 4 is fine.

We re-factored Security Admin to be plain ModelAdmin in CMS 5. That's probably when this thing got broken.

Honestly, I didn't even know this tab could exists on the Group form ... it only shows if you have at least one role define.

**Comment by maxime-rainville** [comment]
The UI for this features is just weird. 

- Why have a dedicated tab for this if you are going to use a drop down to manage roles?
- If you're going to have a dedicated tab, why not simply use a plain gridfield then?
- And why hide it if no roles are available?

**Comment by emteknetnz** [comment]
Linked PRs have been merged, they will be automatically tagged shortly - note they target CMS 5.1 not 5.0 which was the version originally reported, so you may need to upgrade
