### ISSUE TITLE
Security warning is gone

### ISSUE THREAD

**Issue by ssmarco** [silverstripe/silverstripe-admin#1703]
### Module version(s) affected

5.0.0

### Description

The security warning that says, "Caution: Removing members from this list will remove them from all groups and the database". Is this something that be added back? See screenshot below.

![image](https://github.com/silverstripe/silverstripe-admin/assets/26287674/b48bf728-f7c0-44f4-8a2a-c966adc224a0)

### How to reproduce

To reproduce, please login to the CMS and go to the Security section. From there, no warning is shown on the top of the list of users.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
Looks like an oversight from when `SecurityAdmin` was converted to be a `ModelAdmin`.
If you'd like to make a PR to add it back I'd be happy to review it, but the CMS Squad won't be prioritising this.

**Comment by GuySartorelli** [comment]
As there hasn't been a PR raised for this, I'm going to close it. I think the nature of how deleting records in the CMS works is well established by this point, so we don't really need to warn people that deleting a user will delete the user.
