### ISSUE TITLE
Email not validating when insert an email link via WYSIWYG.

### ISSUE THREAD

**Issue by Jianbinzhu** [silverstripe/silverstripe-admin#1707]
### Module version(s) affected

2.1.1

### Description

When adding an email link via the WYSIWYG, it doesn't not validate or throw an error when a non-email is inputted.

<img width="604" alt="Screenshot 2024-03-12 at 4 38 09 PM" src="https://github.com/silverstripe/silverstripe-admin/assets/11606683/3b81a446-e383-4cf0-95d6-e9a6948c6ffa">

On the front-end, the `<a>` tag is still being added
<img width="239" alt="Screenshot 2024-03-12 at 4 39 54 PM" src="https://github.com/silverstripe/silverstripe-admin/assets/11606683/b2569e8c-fcb0-4765-9943-164102c91c93">

### How to reproduce

Go to any WYSIWYG, and insert an email link

<img width="613" alt="Screenshot 2024-03-12 at 4 46 54 PM" src="https://github.com/silverstripe/silverstripe-admin/assets/11606683/ca1ad842-e8c3-4d1d-9fa3-8a434528c918">

### Additional Context

I can see that it is being regex checked on 
https://github.com/silverstripe/silverstripe-admin/blob/2/client/src/legacy/TinyMCE_sslink-email.js#L96, but it simply just removes the value.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1710

**Comment by emteknetnz** [comment]
Linked PR has been merged, it will be automatically tagged shortly for CMS 4. It will be automatically tagged for CMS 5 in within the next week. Ping me if you need it sooner than that and I'll do it manually for you.
