### ISSUE TITLE
Refactor formschema logic from `LeftAndMain` into its own abstract class

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1762]
Currently `LeftAndMain` is bloated with logic for setting up formschema, but that isn't needed by most of its subclasses. This should be moved into its own class so the logic is only available where it's needed, and to make `LeftAndMain` easier to maintain.

## Related
- https://github.com/silverstripe/silverstripe-cms/issues/2933

## Notes
- The exact name of the class isn't important - if you think of a better name, feel free.

## Acceptance Criteria
- A new abstract `FormSchemaController` class is created, and is a subclass of `AdminRouteController` (see https://github.com/silverstripe/silverstripe-admin/issues/1761)
- Methods, properties, and configuration required for formschema functionality are moved from `LeftAndMain` to the new class (see [this comment](https://github.com/silverstripe/silverstripe-cms/issues/2933#issuecomment-2111557980) for recommendations about this)
- `ModalController` is a subclass of the new controller
- `ModalController` handles the routes which currently require creating a singleton of `LeftAndMain` for formschemas
- Any controller in supported modules that currently subclasses `LeftAndMain` but only needs the formschema logic is made to subclass the new class instead (e.g. `LinkFieldController`)
- Documentation is updated to indicate best practice for form schema controllers

### CMS 5 PRs

- https://github.com/silverstripe/silverstripe-admin/pull/1851
- https://github.com/silverstripe/silverstripe-subsites/pull/613
- https://github.com/silverstripe/developer-docs/pull/629

After merging reassign to Guy so they can merge up and rebase the CMS 6 PRs

### CMS 6 PRs

[**Kitchen sink CI**](https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/11904419675)

- https://github.com/silverstripe/silverstripe-admin/pull/1850
- https://github.com/silverstripe/silverstripe-subsites/pull/611
- https://github.com/silverstripe/silverstripe-linkfield/pull/348
- https://github.com/silverstripe/silverstripe-mfa/pull/573
- https://github.com/silverstripe/silverstripe-userforms/pull/1348
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/369
- https://github.com/silverstripe/silverstripe-elemental/pull/1273
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1509
- https://github.com/silverstripe/silverstripe-contentreview/pull/267
- https://github.com/silverstripe/silverstripe-framework/pull/11463
- https://github.com/silverstripe/silverstripe-cms/pull/3024
- https://github.com/silverstripe/silverstripe-versioned/pull/481
- https://github.com/silverstripe/developer-docs/pull/628

**Comment by emteknetnz** [comment]
@GuySartorelli Thinks are looking good, could you just do a final updated kitchen sink run just to make sure everything integrated correctly

**Comment by GuySartorelli** [comment]
That's massive overkill considering the scope of the changes since the last run:
- some docs
- some comments
- subsites specifically got rebased on top of some innocuous changes

I'll do it just to avoid ping pong, but it's really not necessary here.
