### ISSUE TITLE
Refactor logic for sections that deal with only a single record out of `LeftAndMain` into its own class

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1764]
Most subclasses of `LeftAndMain` deal with more than one record at a time - be it `ModelAdmin` which handles multiple records in a `GridField`, or `CMSMain` which deals with multiple records in a hierarchical structure.

The logic in `LeftAndMain` which is intended for sections that only edit a single record should be abstracted out into its own abstract class.

## Related
- https://github.com/silverstripe/silverstripe-cms/issues/2933

## Notes
- The exact name of the class isn't important - if you think of a better name, feel free.
- Refer to https://github.com/silverstripe/silverstripe-cms/issues/2933#issuecomment-2111603655 for recommendations on some implementation details

## Acceptance criteria
- [x] A new abstract `SingleRecordAdmin` class is created, which is a subclass of `LeftAndMain`
- ~~`AdminRootController` checks for (non-abstract) subclasses of the new class instead of subclasses of `LeftAndMain` to set up routing rules~~ - already handled by https://github.com/silverstripe/silverstripe-admin/issues/1761
- [x] Methods, properties, and configuration used only for editing single records are moved from `LeftAndMain` to the new class
- [x] `CMSProfileController`, `SiteConfigLeftAndMain`, and any other controllers in supported modules which only edit a single record are made subclasses of this new class
- [x] Functionality that's reimplemented in `CMSProfileController`, `SiteConfigLeftAndMain`, etc are made generic and are implemented in the new class directly

### CMS 5 PRs

- https://github.com/silverstripe/silverstripe-admin/pull/1844
- https://github.com/silverstripe/silverstripe-siteconfig/pull/181
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/339
- https://github.com/silverstripe/silverstripe-reports/pull/201
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1506
- https://github.com/silverstripe/silverstripe-cms/pull/3021
- https://github.com/silverstripe/developer-docs/pull/616

### CMS 6 PRs

**[kitchen sink ci](https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/11695642970)**

- https://github.com/silverstripe/silverstripe-admin/pull/1842
- https://github.com/silverstripe/silverstripe-siteconfig/pull/179
- https://github.com/silverstripe/silverstripe-cms/pull/3019
- https://github.com/silverstripe/silverstripe-subsites/pull/606
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/337
- https://github.com/silverstripe/silverstripe-reports/pull/200
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1504
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/902
- https://github.com/silverstripe/developer-docs/pull/609

**Comment by emteknetnz** [comment]
@GuySartorelli even though it's draft, I've started by reviewing the CMS 6 framework PR first as that could change the CMS 5 PRs

**Comment by GuySartorelli** [comment]
Reopening. There's an unmerged pr there.
