### ISSUE TITLE
Lazyloaded SearchableDropdownField does not work in elemental

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1778]
Lazyloaded SearchableDropdownField does not function correctly when using in elemental.  Selecting a value does not visually update the field, though when you save the value is saved.  I tested using an autoscaffolded field, meaning I had over 100 DataObject which I create via requireDefaultFields(). When setting ->setIsClearable(true) on DBForeignKey.php, when I clicked the clear button I got console warnings (I had run yarn dev in admin)

Discovered when implementing https://github.com/silverstripe/silverstripe-framework/pull/11273

Note this isn't an issue when using a SearchableDropdownField in a regular form

Test setup:

You'll need dnadesign/silverstripe-elemental installed

**MyBlock.php**
```php
<?php

use DNADesign\Elemental\Models\BaseElement;

class MyBlock extends BaseElement
{
    private static $db = [
        'MyField' => 'Varchar',
    ];

    private static $has_one = [
        'MySubDataObject' => MySubDataObject::class,
    ];
    private static $table_name = 'MyBlock';

    private static $singular_name = 'My Block';

    private static $plural_name = 'My Blocks';

    private static $description = 'This is my block';

    private static $icon = 'font-icon-block-content';

    public function getType()
    {
        return 'My Block';
    }
}
```

**MySubDataObject.php**
```php
<?php

use SilverStripe\ORM\DataObject;

class MySubDataObject extends DataObject
{
    private static $table_name = 'MySubDataObject';

    private static $db = [
        'Title' => 'Varchar'
    ];

    private static $has_many = [
        'MyBlock' => MyBlock::class,
    ];

    public function requireDefaultRecords()
    {
        parent::requireDefaultRecords();
        if (self::get()->count() < 110) {
            for ($i = 0; $i < 110; $i++) {
                $record = self::create();
                $record->Title = 'MySubDataObject ' . $i;
                $record->write();
            }
        }
    }
}
```

## New issues created
- https://github.com/silverstripe/silverstripe-admin/issues/1791

## Shared CI run
- https://github.com/emteknetnz/silverstripe-installer/actions/runs/9589272730

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1786
- https://github.com/silverstripe/silverstripe-frameworktest/pull/188
- https://github.com/silverstripe/silverstripe-elemental/pull/1209

**Comment by GuySartorelli** [comment]
PRs merged
