### ISSUE TITLE
Console warning when opening elemental block after running yarn dev

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-admin#1782]
When running yarn dev in silverstripe/admin and opening an elemental block, you get the following console warning which makes javascript development much more annoying then it needs to be

![image](https://github.com/silverstripe/silverstripe-admin/assets/4809037/d4ae939e-0b06-40d0-a30a-3968e0c1abad)

## PRs
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/347

**Comment by GuySartorelli** [comment]
PR merged
