### ISSUE TITLE
IMPROVEMENT: LeftAndMain subclasses must have url_segment

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-admin#179]
It will be great if u will make this message more informative. It's hard to find out which subclass missing it. Just add static::class to the message.

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is intended to be used for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.
