### ISSUE TITLE
SS4 (beta2): Mispositioned "Expand panel" icon

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-admin#183]
When the left-hand menus in the CMS are collapsed, the "Expand panel" icon is mispositioned to the right of the column. When editing any page in the SiteTree the mispositioned icon isn't visible due to the overlay.

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/185

**Mispositioned**
![screen shot 2017-08-09 at 10 39 24-fullpage](https://user-images.githubusercontent.com/1463435/29098554-11d9ff38-7cf4-11e7-85d7-2001dc94c311.png)

**Not visible**
![screen shot 2017-08-09 at 10 40 03-fullpage](https://user-images.githubusercontent.com/1463435/29098528-f8687598-7cf3-11e7-8ff3-5bbab4f3f933.png)

**Comment by tractorcow** [comment]
Should be easy fix. :)

3.6 looks like this:

![image](https://user-images.githubusercontent.com/936064/29147381-b5572a5c-7dba-11e7-923c-4496676b527f.png)

A slightly older 4.x looks like this

![image](https://user-images.githubusercontent.com/936064/29147404-dd348bc8-7dba-11e7-90d4-b6de02c3aaf2.png)

**Comment by flamerohr** [comment]
Yup, some padding was added... I think it was when we fixed icon sizes and made this left panel responsive
