### ISSUE TITLE
ignore_menuitem is not documented because is not declared

### ISSUE THREAD

**Issue by catharsisjelly** [silverstripe/silverstripe-admin#1845]
### Description

This is already implemented but not documented in the API `CMSMenu` references a var that can be used called `ignore_menuitem` which is a boolean field. This var is not declared in `LeftAndMain` and therefore not documented. This was implemented by #211 but there is no documentation on it which has been confusing for me

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1846

**Comment by GuySartorelli** [comment]
PR closed
