### ISSUE TITLE
Save button loading state is missing

### ISSUE THREAD

**Issue by hitaishi19** [silverstripe/silverstripe-admin#1865]
### Module version(s) affected

2.3

### Description

There is a delay in the "loading" of the Save button when clicked.

### How to reproduce

1. Edit the existing text block on a page
2. Click the page’s “Save” button

**Expected:**
The “Save” button is loading/processing

**Actual:**
No change to the "Save" button after it is clicked multiple times.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1866

**Comment by GuySartorelli** [comment]
PR merged. This will be automatically tagged by GitHub Actions
