### ISSUE TITLE
Breadcrumb title position if there is an empty list item

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#22]
When there is an empty list item in the breadcrumb the page title (last breadcrumb item) gets pushed down.

![image](https://cloud.githubusercontent.com/assets/555033/24742794/d0a9114e-1aff-11e7-90bf-87f8f6a318fb.png)

Adding a quick CSS fix for this but keeping in mind for the refactor of Pages breadcrumbs (will open separate issue).

## Pull requests

https://github.com/silverstripe/silverstripe-admin/pull/24

**Comment by phalkunz** [comment]
Reviewed the pull request, looks good.
