### ISSUE TITLE
ss 4.0 - IE Browser issues list

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-admin#228]
Broken icons placement on buttons:
 
![image](https://user-images.githubusercontent.com/936064/30144730-1d809578-93e1-11e7-9594-9cca4b6c4611.png)

Breadcrumbs icon alignment:

![image](https://user-images.githubusercontent.com/936064/30144756-4a398c8c-93e1-11e7-9610-0cb869320880.png)

Asset search buttons:

![image](https://user-images.githubusercontent.com/936064/30144804-9a3ed700-93e1-11e7-8701-95fcb745c503.png)

**Comment by phalkunz** [comment]
A few more that I've found: 

![asset action icons](https://user-images.githubusercontent.com/318116/30145041-eb675dc2-93e2-11e7-902b-68121d9cce3d.png)

![dashboard](https://user-images.githubusercontent.com/318116/30145042-eb6a3506-93e2-11e7-8807-6b5c40803242.png)

**Comment by tractorcow** [comment]
Breadcrumbs icons

![image](https://user-images.githubusercontent.com/936064/30145448-676392a4-93e5-11e7-900e-61cb97e89655.png)

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-admin/pull/230
