### ISSUE TITLE
Breadcrumbs and north toolbar inconsistent markup and styles across CMS

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#23]
In SSv4 we must have about four different structures of the north toolbar across different modeladmins, Pages, Files area, Campaigns. I think a decent refactor to clean things up might save time in the long run as it is heavily used in a lot of different formats.

**Comment by dhensby** [comment]
still a problem?

**Comment by clarkepaul** [comment]
Yup still a problem, AssetAdmin and Campaigns are similar but the rest are unique and are one of the reasons the breadcrumbs and search icon keep breaking.

**Comment by clarkepaul** [comment]
Closing this issue as there is another one the same https://github.com/silverstripe/silverstripe-admin/issues/614
