### ISSUE TITLE
Tree dropdown field colours differ from other fields

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#231]
Focus colour and options selected/hover colours not consistent with other form fields.
As part of this issue ensure a designer specifies the best colours (should hopefully be existing variables) which can be used.
Standard field focus:
![image](https://user-images.githubusercontent.com/555033/30187854-9f705f16-947f-11e7-8521-fa4e4156b638.png)

Treedropdown focused:
![image](https://user-images.githubusercontent.com/555033/30187872-c1f2a06c-947f-11e7-81f5-4a9e59f85d60.png)

**Comment by jamessilverstripe** [comment]
- Focus state to have no blue haze (shadow)
- Focus border to be #29ABE2
- Focus border to be present around all dropdown box when actice
- Remove auto-hover state on first item in list
- Hover background colour to be #EDF2F5
- Selected item background colour to be #0071c4 with white text and border-top colour of rgba (0,0,0,0.2)
- Deeper arrow buttons to have white backgrounds
- Deeper arrow buttons on selected items to have a background of #0071c4 and border of #29ABE2, with a white arrow
- Deeper arrow buttons on selected items to have a hover background of rgba (0,0,0,0.2)
- When in next level view, back chevron needs to be white

**Comment by jamessilverstripe** [comment]
<img width="336" alt="treedropdownfield-confirmed-styles" src="https://user-images.githubusercontent.com/29618750/30571476-29232ee0-9d3c-11e7-8a6a-59b1c657c4e9.png">

**Comment by clarkepaul** [comment]
I think we might have forgotten about the back arrow being white, we should update the design with this.

**Comment by clarkepaul** [comment]
![image](https://user-images.githubusercontent.com/555033/30793094-fcbe5e76-a21b-11e7-929d-a69b2f012321.png)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-admin/pull/310

**Comment by clarkepaul** [comment]
Seems some of the styles were missed so we'll open a new issue with the remaining changes and we've got a couple more as well.

**Comment by clarkepaul** [comment]
@newleeland are you able to see what was missed and move them to a new issue.
