### ISSUE TITLE
Frontend Javascript i18n support

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#253]
In SS3, when you call `Requirements:add_i18n_javascript('...')` it will naturally add the i18n.js class to the requirements as well to support the translation.

In SS4 this has been removed. We can still use `import i18n from 'i18n'` in webpack to support the use of i18n in pre-compiled Javascript, but when adding Javascript translations to the frontend the browser console complains:

```
external "i18n":1 Uncaught ReferenceError: i18n is not defined
    at Object.module.exports (external "i18n":1)
    at __webpack_require__ (bootstrap ed53e59f1b0d72d969ce:19)
    at Object.defineProperty.value (bootstrap ed53e59f1b0d72d969ce:65)
    at __webpack_require__ (bootstrap ed53e59f1b0d72d969ce:19)
    at Object.module.exports (userforms.js?m=1505338009:612)
    at __webpack_require__ (bootstrap ed53e59f1b0d72d969ce:19)
    at bootstrap ed53e59f1b0d72d969ce:65
    at bootstrap ed53e59f1b0d72d969ce:65
module.exports @ external "i18n":1
__webpack_require__ @ bootstrap ed53e59f1b0d72d969ce:19
Object.defineProperty.value @ bootstrap ed53e59f1b0d72d969ce:65
__webpack_require__ @ bootstrap ed53e59f1b0d72d969ce:19
module.exports @ userforms.js?m=1505338009:612
__webpack_require__ @ bootstrap ed53e59f1b0d72d969ce:19
(anonymous) @ bootstrap ed53e59f1b0d72d969ce:65
(anonymous) @ bootstrap ed53e59f1b0d72d969ce:65

en.js?m=1505338001:5 Class ss.i18n not defined
(anonymous) @ en.js?m=1505338001:5

en_US.js?m=1503289829:5 Class ss.i18n not defined
(anonymous) @ en_US.js?m=1503289829:5
```

Translation files need `ss.i18n` to be available in the global scope, perhaps we need to add separate i18n bundle for users to opt in, and/or revert back to pushing i18n.js to requirements by default on calls to `::add_i18n_javascript`

**Comment by tractorcow** [comment]
PRS:

 - [ ] https://github.com/silverstripe/silverstripe-admin/pull/273
 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7400

**Comment by robbieaverill** [comment]
Thanks!!

**Comment by robbieaverill** [comment]
The only problem with this is that no you have to have the admin module to use i18n on the frontend. Maybe it needs to be moved back to framework
