### ISSUE TITLE
Enable skin_url option for TinyMCEConfig to allow user defined skins

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-admin#265]
We should also be able to adjust the default colours of TinyMCE slightly in the silverstripe-admin module to ensure consistency with the SS4 CMS user interface colours. Adding support for `skin_url` would allow us to add our own stylesheet for it, as well as let users define their own in their projects.

Reference: https://github.com/silverstripe/silverstripe-admin/issues/83

**Comment by sachajudd** [comment]
https://github.com/silverstripe/silverstripe-admin/pull/425

**Comment by sachajudd** [comment]
https://github.com/silverstripe/silverstripe-admin/issues/265

**Comment by clarkepaul** [comment]
@sachajudd I think you mean the PR is here: https://github.com/silverstripe/silverstripe-admin/pull/425

**Comment by sachajudd** [comment]
😂  shame

**Comment by clarkepaul** [comment]
Closing this as there is a PR already in place #425 and this is just covering the specifics of https://github.com/silverstripe/silverstripe-admin/issues/83
