### ISSUE TITLE
When logging out of the admin interface and back in again, user should be taken back to admin

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#268]
In SS3 if you log out of the admin interface then log back in again immediately, you are taken back to admin again.

In SS4 you log back in then get shown the default logged in screen telling you who you're logged in as.

**Comment by bergice** [comment]
This looks resolved. When logging out you get redirected to `/Security/login?BackURL=%2Fadmin%2Fpages%2F`
