### ISSUE TITLE
Consistency of use of icons in popup panels

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#274]
I would prefer if we used icons for all available actions within the action popup panels. I can understand that this might not be as easy for custom actions to be added if a suitable supporting icon was not available. As part of this issue, I would like to either be consistent in having icons for all actions or failing that then remove all icons so at least there is consistency.

<img width="198" alt="pasted_image_26_09_17__11_07_am" src="https://user-images.githubusercontent.com/555033/30834466-b54bdbf6-a2af-11e7-9e27-192701e04a5f.png">

# PR

 - [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/679

**Comment by newleeland** [comment]
Here are some of the options we can go down:
Add to campaign (new icon needed)
Publish (rocket)
Publish and archive < This might be hard to do.
Archive (trashcan icon)
Cancel draft changes (X icon)

Personally, I'm not sure about the adding in icons, as developers adding on to the default actions may not create custom icons for their new actions, and would make the CMS to look broken

**Comment by clarkepaul** [comment]
How did you get "publish and archive" @newleeland ?

**Comment by tractorcow** [comment]
PR https://github.com/silverstripe/silverstripe-asset-admin/pull/679
