### ISSUE TITLE
SS4: radio / checkbox .form-check-input styling issue

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-admin#284]
Radio & checkbox elements are currently positioned absolute with a right margin of 6px in SilverStripe4 (beta-3). Whilst the margin-right currently works in Chrome (it probably shouldn't because it has `position:absolute`), it doesn't work in Firefox.

![screen shot 2017-10-04 at 09 26 01-fullpage](https://user-images.githubusercontent.com/1463435/31147595-d53fd826-a8e6-11e7-99f9-1dda2a9424e3.png)

**Comment by chillu** [comment]
Fixed in latest 4.x already, here's a screenshot from Firefox 56.0

![image](https://user-images.githubusercontent.com/111025/31277834-c11ed4d6-aa9a-11e7-9466-a811755c375b.png)
