### ISSUE TITLE
RFC Solution for thirdparty-module context

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-admin#29]
Third party modules often add additional context to the CMS, often requiring these to be stored in session. E.g.
 - Translatable or Fluent locale
 - Subsite ID
 
It may be wiser to add a standard "context" registration in LeftAndMain that these modules can access. These context arguments would be added to all links via querystring get parameters, along with a fixed config whitelist.

See https://github.com/silverstripe/silverstripe-admin/pull/19#issuecomment-293146700

**Comment by GuySartorelli** [comment]
We're seeing already a lot of problems with doing basically this with just gridfield - adding more things to get params will just exacerbate the problem. Closing.
