### ISSUE TITLE
Rounded corners missing off Page name field

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#292]
Rounded corners missing from the filed because of a hidden button which follows the field and the following CSS
<img width="221" alt="pasted_image_9_10_17__12_37_pm" src="https://user-images.githubusercontent.com/555033/31322148-aefeaad2-acee-11e7-9239-fe4cf2cf2dc5.png">

<img width="454" alt="pasted_image_9_10_17__10_57_am" src="https://user-images.githubusercontent.com/555033/31321316-bc7745f6-ace0-11e7-8615-3338cc9fadba.png">

**Comment by Cheddam** [comment]
Tested in 4.4.x-dev, this issue no longer occurs (the input-group class is only present when the button is visible)
