### ISSUE TITLE
TinyMCE bar at the bottom is too big, can we reduce size...

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#294]
The bottom bar used to hold meaningful info about where your cursor was placed within the HTML, now you don't get this info but you get a larger empty space. This might need some investigation to find out if any of the following is possible.
<img width="567" alt="pasted_image_9_10_17__2_16_pm" src="https://user-images.githubusercontent.com/555033/31322990-2d274a5a-acfd-11e7-9a36-f816a30de880.png">
* Can we remove the "Powered by TinyMCE" tab?
* Can we remove (or reduce the height) the bottom grey area
* Do we have the option to show info about where your cursor is placed eg. SS3 
![image](https://user-images.githubusercontent.com/555033/31322988-26fe87e2-acfd-11e7-82df-56146c1adb45.png)

# PR

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7536

**Comment by dhensby** [comment]
You can hide the status bar: https://www.tinymce.com/docs/get-started/customize-ui/#hidingthestatusbar

Removing "powered by TnyMCE" it appears to be setting `branding` to `false` from what I could see.

**Comment by newleeland** [comment]
![screen shot 2017-10-26 at 3 15 06 pm](https://user-images.githubusercontent.com/8085295/32031907-a7484e68-ba60-11e7-8e38-5d94c2eb0eb6.png)
![screen shot 2017-10-26 at 3 14 48 pm](https://user-images.githubusercontent.com/8085295/32031909-a99e00ae-ba60-11e7-8953-319bd56df779.png)

**Comment by clarkepaul** [comment]
So let's disable the branding.
If we can disable the element path (including its surrounding div) and only display it when the editor has focus would be good if possible.
