### ISSUE TITLE
Icons no longer loading

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-admin#299]
They reference the vendor folder, which means they're inaccessible
![screen shot 2017-10-10 at 2 59 59 pm](https://user-images.githubusercontent.com/1064889/31366117-ed5685ec-adcb-11e7-997a-fd0646d7ffa3.png)

Also page-type icons may be affected

# PRs:

- [x] https://github.com/silverstripe/silverstripe-assets/pull/85
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7461
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/661
- [x] https://github.com/silverstripe/silverstripe-admin/pull/300
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1987
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/70

**Comment by tractorcow** [comment]
Ok fixed with the above PRs.

Framework may need to get merged first due to the i18n lang changes.

**Comment by kinglozzer** [comment]
All PRs merged, and icons are back :D
