### ISSUE TITLE
SS4-beta4: Defined $menu_icon not being applied to LeftAndMain

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-admin#303]
Icons defined via `private static $menu_icon` are not being rendered in the CMS for classes extending LeftAndMain (ie: main icons down the left-hand-side).

The CSS is being generated and included `Requirements::customCSS()`, however the `.menu__icon` element  itself doesn't contain a relating class to apply that style.

**Comment by flamerohr** [comment]
Hi @axllent, would you be able to confirm if https://github.com/silverstripe/silverstripe-admin/pull/311 would fix your issue?

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-admin/pull/311

@axllent if this doesn't fix your issue please ping me and I'll re-open. :)

**Comment by axllent** [comment]
@flamerohr @tractorcow - Confirmed, the patch fixes the issue and $menu_icon works as expected again. Thanks guys!
