### ISSUE TITLE
Tabs slightly out

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#320]
The border below the selected tabs should overlap the 1px border at the bottom of the north toolbar and the text within the tab should be vertically centered. The overall height of the tab should equate to 53px and the border under the selected tab should be 3px.

Before:
<img width="209" alt="pasted_image_24_10_17__5_49_pm" src="https://user-images.githubusercontent.com/555033/31925310-52df8008-b8e4-11e7-8817-7343e36e9628.png">

This could be updated by adjusting padding top and bottom to be the same:
<img width="182" alt="pasted_image_24_10_17__5_33_pm" src="https://user-images.githubusercontent.com/555033/31925121-0d8c4d0c-b8e3-11e7-87b9-2b7bcd8f28a5.png">

Or by using flexbox with something like (try not use pixel height though):
![image](https://user-images.githubusercontent.com/555033/31925282-26174a38-b8e4-11e7-9303-0080e16201f2.png)

**Comment by Cheddam** [comment]
Seems to have been resolved at some point:

![image.png](https://images.zenhubusercontent.com/58ce3d9c51aa2c305778db1b/7cfa12d4-3b19-441a-81be-45cb02aa9a1d)
