### ISSUE TITLE
Allow PopoverField icon size to be configurable

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#323]
**SS: 4.0.0-rc1**

Currently the PopoverField component adds `btn--icon-xl` to all PopoverField instances.

It would be nice to be able to control the size of the meatballs icon it adds either via class properties or a public API method of some sort. We wanted to use `btn--icon-md` in one instance of this component, but weren't able to modify this.

Code:

https://github.com/silverstripe/silverstripe-admin/blob/1.0.0-rc1/client/src/components/PopoverField/PopoverField.js#L56

**Comment by chillu** [comment]
@robbieaverill We won't get around this in rc2 unless you send us a PR to review :)

**Comment by robbieaverill** [comment]
@chillu if you're happy for this to make it into rc2 then I'm happy to make a PR :)

**Comment by robbieaverill** [comment]
PR at #325

**Comment by chillu** [comment]
Re-added to rc2 ;)
