### ISSUE TITLE
no language files present in tinymce

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-admin#329]
I set my cms interface to Dutch and this results in Tinymce fails to load plugin ../tinymce/langs/nl.js
Simply because no js files are present in resources/silverstripe/admin/thirdparty/tinymce/langs

<img width="689" alt="schermafbeelding 2017-10-30 om 09 16 20" src="https://user-images.githubusercontent.com/3098809/32160825-b6d8f04e-bd53-11e7-9155-c08fea3ff8c4.png">

# PR

 - [ ] https://github.com/silverstripe/silverstripe-admin/pull/331

**Comment by dhensby** [comment]
I  was sure someone has already raised this but I can't find the issue.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-admin/pull/331
