### ISSUE TITLE
Not providing a third parameter to inject HOC triggers errors with updated components.

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-admin#392]
If a component uses the `inject` HOC to inject (sub-)components as props like this:

```
export default inject(
  ['UploadFieldItem', 'AssetDropzone', 'InsertMediaModal']
)(UploadField);
```

then there will be a JS error raised at [`MiddlewareRegistry.js`](https://github.com/silverstripe/silverstripe-admin/blob/master/client/src/lib/dependency-injection/MiddlewareRegistry.js#L195), whenever a custom component was injected into one of these props. (The error being that `context` is `null`)

So if you then do this:

```
Injector.transform(
  'enhance-uploadfield',
  (updater) => {
    updater.component('UploadFieldItem', CustomUploadFieldItem);
  }
);

```
The error will occur at runtime.

The issue is caused whenever `inject` was called without the third parameter (`getContext`). So this implementation here will not break:

```
export default inject(
  ['PopoverField'],
  (PopoverField) => ({ PopoverField }),
  () => 'BulkActions' // <- This seems to be a requirement
)(BulkActionsWithState);

```
while this will:

`export default inject(['FieldGroup'])(ProportionConstraintField);`

The way the parameters are ordered and how `inject` was implemented leads me to believe that the `getContext` should actually be optional. Maybe there could also be a default implementation for it, the same as for `mapDependenciesToProps`?

As previously stated, this error will only appear, once you injected a custom component via `Injector.transform`.

**Comment by flamerohr** [comment]
Have created https://github.com/silverstripe/silverstripe-admin/pull/394 to address this (with `defaultContext`
Had a few other points listed on the pull request to address improving extensibility

**Comment by flamerohr** [comment]
Fixed with the above pull request and merged
