### ISSUE TITLE
BUG Prevent GridField sorting and filtering from triggering change tracker

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-admin#393]
When `GridField` uses `GridFieldSortableHeader` or `GridFieldFilterHeader` and user sorts items by any column or filters items by any value the `change` event is triggered. This is unwanted because filtering and sorting actually don't change data.

## PRs
- [x] https://github.com/silverstripe/silverstripe-admin/pull/598
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8315

**Comment by lukereative** [comment]
Ugh, I changed something at the end and forgot to add a check back in for the sort buttons – it's back and working. now

**Comment by unclecheese** [comment]
Almost there. Sorting and pagination working. Filtering still doesn't. (per: https://github.com/silverstripe/silverstripe-framework/issues/7327)

**Comment by unclecheese** [comment]
@dhensby Why did this get closed? Were you not able to replicate the above issue?

**Comment by unclecheese** [comment]
@lukereative The above issue is still present. Can you have a look?

**Comment by lukereative** [comment]
It was a combination of different event handling, I was testing with submit not button click for filter and through the arrows on pagination not changing the number and pressing enter. I've done all the little changes and tested all those methods with submit/enter and button clicking so hopefully that catches all those various paths.

**Comment by lukereative** [comment]
Fixed by https://github.com/silverstripe/silverstripe-admin/pull/625
