### ISSUE TITLE
Upgrade to latest version of Bootstrap

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-admin#395]
We're currently using bootstrap v4.0.0-beta, the latest release is v4.0.0-beta.3. They've mentioned there are breaking changes between each release, so probably best to be updated once it is in stable as they are hoping to move quickly into a final [release](https://github.com/twbs/bootstrap/projects/12).

**Comment by flamerohr** [comment]
funny @sachajudd a few days after your issue was raised, bootstrap4 went `stable` 🎉 
https://blog.getbootstrap.com/2018/01/18/bootstrap-4/

**Comment by robbieaverill** [comment]
Duplicated by https://github.com/silverstripe/silverstripe-admin/issues/395 but it has better info, closing this one
