### ISSUE TITLE
Unaltered date-field in asset-admin requires value (fails validation).

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-admin#396]
When I add a date-field to asset-admin (eg. by decorating `FileFormFactory`), I can no longer save the record, unless I enter a valid date.

![screen shot 2018-01-17 at 21 27 20](https://user-images.githubusercontent.com/1006185/35065323-3d55ca5e-fbcd-11e7-9fb3-f36e39eb6017.png)

With the empty default value, validation will always fail with the message: **&lt;Fieldname&gt; is not a proper date format.**

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-admin/pull/404
