### ISSUE TITLE
ModelAdmin search broken in 4.0.2

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-admin#409]
Introduced in SilverStripe 4.0.2 - The ModelAdmin search seems to have an issue whereby if multiple words are searched, spaces after the second word are substituted with a "+".

So searching for `game of thrones` results in `game of+thrones` (which leads to no results as the + is taken as part of the search string). 

Another example: `this is my search` results in `this is+my+search`

**Comment by unclecheese** [comment]
Have confirmed this is resolved by https://github.com/silverstripe/silverstripe-admin/pull/435
