### ISSUE TITLE
updateClientConfig fails to load anything

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-admin#422]
framework 4.0.2 + silverstripe/admin 1.0.x-dev + php 7.1

I'm trying to add a custom form to the "Insert Link" TinyMCE toolbar. I can see my desired custom text in the "Insert Link" dropdown, and all the other links work fine but when my custom one is selected, it causes a JS error: "Uncaught TypeError: Cannot read property 'schemaUrl' of undefined". I believe this means that the "schemaUrl" key of the JSX snippet in the the custom JS file (copied and modded from "TinyMCE_sslink-external.js") isn't being dynamically collected from server side logic.

* If I put some debug logic into `LeftAndMain::getClientConfig()` with the extension applied, my custom key is not dumped.
* If I add debug logic to the extension, it _is_ dumped (meaning the extension is obviously being called via `$this->extend('updateClientConfig', $clientConfig);`
* If I hack `LeftAndMain::getClientConfig()` and put my custom key in there, the _JS error goes away_, and everything works.

FYI I declare my `LeftAndMain` extension in the usual manner and have attached the custom JS file (minified into bundle.min.js for my custom module using webpack and node 8.4.0)

```yml
SilverStripe\Admin\LeftAndMain:
  extensions:
    - My\Project\Controller\CustomLeftAndMainExtension
```

```php
    public function updateClientConfig($clientConfig)
    {
        $clientConfig['form']['EditorCustomLink'] = [
            'schemaUrl' => $this->getOwner()->Link('methodSchema/Modals/EditorCustomLink')
        ];
    }
```
[TinyMCE_sslink-custom.js.txt](https://github.com/silverstripe/silverstripe-admin/files/1693266/TinyMCE_sslink-custom.js.txt)

**Comment by phptek** [comment]
OK, so it appears I needed to prepend the parameter with an ampersand. But you don't usually need to do this to get extension-bound `updateXXX()` methods to work? Is this an API change I've missed?

**Comment by kinglozzer** [comment]
AFAIK this is just PHP behaviour - objects are always “passed by reference” (not technically passed by ref, rather a pointer so properties can still be modified) and arrays aren’t, so the `&$clientConfig` syntax is required.

There is an RFC about explicitly marking this kind of thing on the call side which would go some way to tidying up the confusion: https://wiki.php.net/rfc/explicit_send_by_ref. Otherwise this is probably more a docs issue I think

**Comment by phptek** [comment]
Disagree. While I'm not on front of a pooter, as I said above, calls to updateCMSFields() elsewhere work without the amowrsand. I've never needed to add it before and have logic in this project that doesn't use it, yet that still works.

**Comment by robbieaverill** [comment]
Objects in PHP 5.5(?) and above are always passed by reference. I’m supremely interested in seeing a unit test battle though!

**Comment by bummzack** [comment]
An array is not an object and will be copied when not passed by reference. That's the fundamental difference between passing an array or an object instance, such as a `FieldList`.

To quote http://php.net/manual/en/language.types.array.php
> Array assignment always involves value copying. Use the reference operator to copy an array by reference.

**Comment by phptek** [comment]
Ok, I'm super confused by this. @kinglozzer sorry, don't mean to be confrontational :-)  I spent well over an hour looking at this, and at the very least there is an inconsistency. If updateCMSFields() works with and without the pass-by-ref syntax, but LeftAndMainExtension subclasses don't, then there's more than a docs issue aye?

**Comment by phptek** [comment]
@bummzack good point. Usually you're dealing with `FieldList` objects, here we're dealing with arrays....

**Comment by bummzack** [comment]
Yeah, you'd have to add an ampersand to all "value-types", if you modify them in your extension. So basically everything that's not an object instance.

**Comment by phptek** [comment]
I'm going with @bummzack and closing this. My logic works now that I'm _explicitly_ passing by ref. But sometimes you need to open a ticket to really get to the bottom of things.

**Comment by phptek** [comment]
Hmmm. Is there a case for passing `$clientConfig` as a `FieldList` here?
