### ISSUE TITLE
Prev, Next and Create buttons on detail GridField forms

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#436]
# Overview

It's often cumbersome to move through a list of items by clicking into the detail view, hitting the "back" button, and clicking into the next item. The [betterbuttons](https://github.com/unclecheese/silverstripe-gridfield-betterbuttons) module solved this for 3.x, and there's a good case for making it a core feature. @sachajudd and @clarkepaul have designed a solution as part of a [Save and add new button](https://github.com/silverstripe/silverstripe-cms/issues/2047#issuecomment-365811496) design.

# Acceptance Criteria

 - [x] I can add a new record from a record detail form
 - [x] If choosing to add a new record or navigate to the previous/next record on a record detail form with unsaved edits, I get a prompt and stay on the same screen until I've saved the record explicitly. 
 - [x] I can navigate to the previous and next records of a list when viewing a record detail form
 - [x] If there is no more previous or next records, the button is disabled
 - [x] The new buttons don't compromise more important buttons on small screens
 - [x] The functionality works in ModelAdmin and any other GridField
 - [x] Sorting and filtering is retained
 - [x] Does not double up when betterbuttons is installed (might need a patch to that module?) (UPDATE: BetterButtons already takes priority and overrides all the actions)
 - [x] Should work in default configurations, but can be opted out of
 - [x] Behat Tests written
 - [x] Update documentation
 - [x] Excludes choosing the type of record to create (that's a thing in some GridField modules)
 - [x] Excludes any "save and close" or "publish and close" logic

# Designs

[Styleguide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5b5e610563c7ad0012bc21fb)

# Notes

 * Some historical context and discussion in a [duplicate card](https://github.com/silverstripe/silverstripe-cms/issues/2047)

# Pull Requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8569
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/744
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/8619

**Comment by bummzack** [comment]
Yes, this would be an awesome addition!

Please also consider the case where different classes can be added to a relation. Meaning that the "add new" button should turn into a flyout where you can select the class to create (the gridfield equivalent of this is the [`GridFieldAddNewMultiClass`](https://github.com/symbiote/silverstripe-gridfieldextensions/blob/master/src/GridFieldAddNewMultiClass.php) component added via gridfieldextensions). The elemental-module makes use of this to add the different block-types to a page.

It doesn't have to be in core, but it should be possible to add this via extensions or similar.

**Comment by Rhym** [comment]
4.1.1 here we gooooo!

**Comment by chillu** [comment]
Separated out one AC to https://github.com/silverstripe/silverstripe-admin/issues/486

**Comment by chillu** [comment]
@sachajudd [commented](https://github.com/silverstripe/silverstripe-cms/issues/2047#issuecomment-365483979) on the duplicate card:

> We should have a warning indicating to the user that they have unsaved changes before they navigate away. We thought the "save/publish and create new" action was better suited in the drop-down area.

I've changed the AC accordingly. So the "plus" button would *only create* a new record, not also save the existing one.

**Comment by patricknelson** [comment]
>  Excludes any "save and close" or "publish and close" logic

So, I think this means that the extra imputed functionality necessary for maintaining `Version`'ed `DataObject`'s managed in `GridField` instances will _still_ reside **entirely** in the `betterbuttons` module, is this correct? That is, the special `BetterButton_SaveDraft` and `BetterButton_Publish` buttons incorporated by the module right now ("Saved" and "Save & publish") and the associated "stage" level DB persistence abstraction interfacing with the `Versioned::` API.

If that's not the case,  could someone point me in the direction where this will eventually live long term for SS 4+ and onward (if not in `betterbuttons` module or in `silverstripe-admin`)?

**Comment by bergice** [comment]
@patricknelson that's correct. This is only porting the `Previous`, `Next` and `Add` buttons on the edit form.

**Comment by unclecheese** [comment]
@patricknelson It's an MVP at this point. We need to satisfy the squeakiest wheel, and that's prev/next and add. That's most of the reason why users are installing betterbuttons. Further down the track, I see this API expanding to support additional prebaked and custom actions, and may even do so in 4.4, as this PR isn't going to make it into 4.3 anyway.

**Comment by Rhym** [comment]
@unclecheese I'll give you $5 if it goes into 4.3. *rubs hands*

**Comment by normann** [comment]
Just wondering when this bit can be released to a stable?

**Comment by chillu** [comment]
It's already in the latest 4.x stable

**Comment by Rhym** [comment]
@chillu As in the current stable release? How would we activate/view this?

**Comment by chillu** [comment]
Can't recall, but I've just checked and it's in the admin/security section.
The intent was that you don't need to configure this stuff, maybe the
implementation has forgotten about this?

**Comment by ScopeyNZ** [comment]
It's slated for release in 4.4. Not yet tagged.

**Comment by Rhym** [comment]
@ScopeyNZ Do we have a rough estimate for 4.4? this button would help a lot with a client's data entry.

**Comment by ScopeyNZ** [comment]
4.4 should be within the next couple of months. I _think_ there's a tentative schedule to have an RC on the week beginning 6th of May.

**Comment by Rhym** [comment]
Excellent, looking forward to this addition :)

**Comment by Rhym** [comment]
It may have taken half a decade, but it's finally here! I used the buttons today, and they made me very happy. Thanks for all your work, team! 🎉🎉🎉

**Comment by ssimo3lsuhsc** [comment]
Where do I leave a comment to say that it doesn't work the way it should? Sometimes the Next button is greyed out on a non-final record, and sometimes the Previous button is inactive on a non-first record. I should add that the affected records are ALMOST NEVER page-initial or page-final in the current page of the query.

**Comment by andreaslindahl** [comment]
I have the same problem. The buttons are often disabled, when they shouldn't be.

**Comment by ScopeyNZ** [comment]
Please feel free to raise an issue with the problem. Preferably with some accurate steps to reproduce.

**Comment by chillu** [comment]
Note that I don't think prev/next takes filtered/ordered GridFields into account - @unclecheese you're working on persisting search parameters in the GridField URL state, do you think this might be overlapping?

**Comment by unclecheese** [comment]
My guess is that the issue here is non-deterministic sort. Make sure your dataobject has a default_sort defined, or explicitly sort the datalist you’re passing to the grid. 

The fact that it happens unpredictably is a good indication that your result set isn’t predictable itself.

**Comment by unclecheese** [comment]
It’s exactly one out of every five?

So the steps to reproduce are:
* Edit record
* Go back to grid
* Repeat five times
* On the fifth time, the prev/next buttons are incorrect

**Comment by ssimo3lsuhsc** [comment]
It just seems like one of every five. I'm not sure even which records and steps are producing it anymore.

**Comment by ssimo3lsuhsc** [comment]
It may be several problems masquerading as one.

One possibly related problem is that when a new record is created, the buttons appear as though the record is at the beginning of the set. To test that this particular behavior is deterministic, I created a record with a page_number of 100 (my default_sort is page_number ASC). The number 100 is much higher than any number I had previously put in that field. So the record should have been at the end when the default_sort was applied. Yet the buttons show it is still at the beginning.

**Comment by patricknelson** [comment]
For those of us who were using `unclecheese/betterbuttons`, what's the upgrade path to SS4 and beyond? Just remove the package and any direct hooks into that package? I imagine there are probably some configuration-specific changes to look out for too.

Just wondering if there's any existing documentation out there someone can point me to. 🙂
