### ISSUE TITLE
GridFieldAddExistingAutocompleter does not autocomplete, or add existing...

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-admin#442]
The control widget for this GridFieldComponent allows one to enter a search term in order to select a result from a list matching that search query.

The issue I am experiencing is that although I can see the request go off and return successfully (with a valid list of items), nothing is drawn to allow me to select these items. As this is the only way of adding things to my relationship this renders the entire gridfield (and relationship) unusable.
The use case here is [related pages](https://github.com/silverstripe/cwp/blob/master/src/PageTypes/BasePage.php#L97).

![capture](https://user-images.githubusercontent.com/778003/36402090-d50f405e-1640-11e8-9e55-4b7e842d05cf.PNG)

**Comment by robbieaverill** [comment]
This is in a CWP context, right? Can you add the core module versions you're using? I suspect this might be an error in the CWP implementation rather than in the core class.

See Members/Groups in Security for an example of this GridField component working.

**Comment by NightJar** [comment]
Oh yes sorry, I forgot 😟 

```
silverstripe/admin                        1.1.x-dev cb9c61b
silverstripe/asset-admin                  1.1.x-dev 40778c4
silverstripe/assets                       1.1.x-dev b030495
silverstripe/campaign-admin               1.1.x-dev ce283d1
silverstripe/cms                          4.1.x-dev 319a460
silverstripe/config                       1.0.x-dev 65cc33e
silverstripe/errorpage                    1.1.x-dev a670e41
silverstripe/framework                    4.1.x-dev b0c742b
silverstripe/recipe-cms                   1.1.x-dev c2b64c0
silverstripe/recipe-core                  1.1.x-dev 4b6b6d0
silverstripe/recipe-plugin                1.1.0
silverstripe/reports                      4.1.x-dev ac23686
silverstripe/siteconfig                   4.1.x-dev 8c88911
silverstripe/vendor-plugin                1.3.1
silverstripe/versioned                    1.1.x-dev bdbcb8f
```

**Comment by NightJar** [comment]
Hmm, so I've since been able to both recreate and not-recreate this issue. Maybe it's an integration thing.

**Comment by NightJar** [comment]
Hmm, maybe it got fixed somewhere.
Maybe it just needed a flush D:
Cannot reproduce.

**Comment by unclecheese** [comment]
Have tested this on a vanilla SS4 install, as well as a `cwp/cwp-recipe-cms` install, and I cannot replicate the error. Tested it with @NightJar on his machine, and it's working. Assuming unknown implementation issue. Closing.
