### ISSUE TITLE
Gridfield "Link existing" records broken

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#451]
The UI element for linking existing records to gridfields is broken in Windows 10, Firefox (could also be like this in other browsers too?). Icon positioning needs fixing, screenshot is from @Firesphere 
![img_4040](https://user-images.githubusercontent.com/555033/36819585-eff7e514-1d4e-11e8-844e-a0ed3241888d.JPG)

**Comment by clarkepaul** [comment]
Yes I can confirm, functionally this doesn't work in SS4 with other browsers too. Visually it looks okay but in chrome but functionally doesn't work.

**Comment by katieelks** [comment]
Also seeing this issue in all browsers. Will attach a (better) screenshot.
![link-existing_bug](https://user-images.githubusercontent.com/38870753/39851102-3c251668-5469-11e8-96a5-c40253ef5647.png)

**Comment by dhensby** [comment]
UI defect is already reported here https://github.com/silverstripe/silverstripe-admin/issues/327

**Comment by maxime-rainville** [comment]
PR has been merged.
