### ISSUE TITLE
Add "copy" or "duplicate" icon

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-admin#455]
Please can we add a duplicate or copy icon to the SS font icons set as this is a pretty handy icon to have specifically for the https://github.com/unisolutions/silverstripe-copybutton module

**Comment by newleeland** [comment]
I've added a clone icon to fontastic. 

This is the CSS mapping:
![Screen Shot 2019-12-17 at 4 46 31 PM](https://user-images.githubusercontent.com/8085295/70963472-68741f00-20ed-11ea-8ed9-29ef995ef525.png)

This is the character mapping:
![Screen Shot 2019-12-17 at 4 51 23 PM](https://user-images.githubusercontent.com/8085295/70963499-83469380-20ed-11ea-826f-f3dcb4bb1b65.png)

**Comment by sachajudd** [comment]
Cool this will have to be updated in admin e.g https://github.com/silverstripe/silverstripe-admin/pull/633 
I'll be adding a new block icon set early next year so can do this at the same time.

**Comment by sachajudd** [comment]
Clone icon added here: https://github.com/silverstripe/silverstripe-admin/pull/1003
