### ISSUE TITLE
Pattern Library not working on Windows10/git-bash

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-admin#465]
I installed SS4.1.0 stable and tried out the pattern library. It didn't work.

npm is V 6.11.0

> $ yarn pattern-lib
> yarn pattern-lib v0.23.2
> $ yarn && start-storybook -p 6006
> yarn install v0.23.2
> [1/4] Resolving packages...
> success Already up-to-date.
> Done in 1.27s.
> @storybook/react v3.2.16
>
> => Loading custom addons config.
> => Loading custom webpack config (full-control mode).
> webpack built 2e1dfff828d023ac7bec in 21335ms
> Hash: 2e1dfff828d023ac7bec
> Version: webpack 3.9.1
> Time: 21335ms
>                                   Asset     Size  Chunks                    Chunk Names
>       images/empty-campaign-preview.png  34.9 kB          [emitted]
>    images/sitetree_ss_default_icons.png  21.6 kB          [emitted]
>              images/sprite-btn-icon.png  23.2 kB          [emitted]
>         images/sprite-sprites-32x32.png  21.8 kB          [emitted]
>           images/cms_content_header.png  14.6 kB          [emitted]
> images/sitetree_ss_default_icons@2x.png  51.4 kB          [emitted]
>                 images/silverstripe.svg  66.5 kB          [emitted]
>                 images/intro-banner.png  10.2 kB          [emitted]
>                static/preview.bundle.js   6.5 MB       0  [emitted]  [big]  preview
>                static/manager.bundle.js  2.59 MB       1  [emitted]  [big]  manager
>            static/preview.bundle.js.map  6.79 MB       0  [emitted]         preview
>            static/manager.bundle.js.map  3.19 MB       1  [emitted]         manager
>  [185] ./node_modules/@storybook/react/dist/client/index.js 1.63 kB {0} [built]
>  [301] ./node_modules/@storybook/react/dist/server/config/polyfills.js 113 bytes {0} {1} [built]
>  [302] ./node_modules/core-js/es6/symbol.js 131 bytes {0} {1} [built]
>  [576] ./node_modules/@storybook/ui/dist/index.js 2.42 kB {1} [built]
>  [694] multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./.storybook/addons.js ./node_modules/@storybook/react/dist/client/manager/index.js 52 bytes {1} [built]
>  [695] ./.storybook/addons.js 60 bytes {1} [built]
>  [696] ./node_modules/@storybook/addon-actions/register.js 30 bytes {1} [built]
>  [697] ./node_modules/@storybook/react/dist/client/manager/index.js 404 bytes {1} [built]
>  [888] multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true .
>
> /.storybook/config.js 64 bytes {0} [built]
>  [889] ./node_modules/@storybook/react/dist/server/config/globals.js 105 bytes {0} [built]
>  [890] ./node_modules/webpack-hot-middleware/client.js?reload=true 7.35 kB {0} [built]
>  [902] ./.storybook/config.js 638 bytes {0} [built]
>  [966] ./client/src (\/bundle\.scss|[A-Za-z]-story\.jsx?)$ 435 bytes {0} [built]
> [1128] ../campaign-admin/client/src (\/bundle\.scss|[A-Za-z]-story\.jsx?)$ 185 bytes {0} [built]
> [1132] ../cms/client/src (\/bundle\.scss|[A-Za-z]-story\.jsx?)$ 185 bytes {0} [built]
>     + 1120 hidden modules
>
> WARNING in ../asset-admin/client/src/components/BackButton/tests/BackButton-story.js
> Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "D:\\dev\\my-project\\www\\vendor\\silverstripe\\asset-admin\\package.json" at 0, attempted to resolve
>
>  relative to "D:\\dev\\my-project\\www\\vendor\\silverstripe\\asset-admin"
>     at D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
>     at Array.map (native)
>     at Function.normalisePlugins (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
>     at OptionManager.mergeOptions (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
>     at OptionManager.init (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
>     at File.initOptions (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\file\index.js:212:65)
>     at new File (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\file\index.js:135:24)
>     at Pipeline.transform (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
>     at transpile (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-loader\lib\index.js:50:20)
>     at D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-loader\lib\fs-cache.js:118:18
>  @ ../asset-admin/client/src (\/bundle\.scss|[A-Za-z]-story\.jsx?)$
>  @ ./.storybook/config.js
>  @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.st
>
> orybook/config.js
>
> WARNING in ../asset-admin/client/src/components/GalleryItem/tests/GalleryItem-story.js
> Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "D:\\dev\\my-project\\www\\vendor\\silverstripe\\asset-admin\\package.json" at 0, attempted to resolve
>
>  relative to "D:\\dev\\my-project\\www\\vendor\\silverstripe\\asset-admin"
>     at D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
>     at Array.map (native)
>     at Function.normalisePlugins (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
>     at OptionManager.mergeOptions (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
>     at OptionManager.init (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
>     at File.initOptions (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\file\index.js:212:65)
>     at new File (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\file\index.js:135:24)
>     at Pipeline.transform (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
>     at transpile (D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-loader\lib\index.js:50:20)
>     at D:\dev\my-project\www\vendor\silverstripe\admin\node_modules\babel-loader\lib\fs-cache.js:118:18
>  @ ../asset-admin/client/src (\/bundle\.scss|[A-Za-z]-story\.jsx?)$
>  @ ./.storybook/config.js
>  @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.st
>
> orybook/config.js
>
> ERROR in ./client/src/font/fonts/silverstripe.ttf
> Module parse failed: Unexpected character ' ' (1:0)
> You may need an appropriate loader to handle this file type.
> (Source code omitted for this binary file)
>  @ ./node_modules/css-loader?{"sourceMap":true,"minimize":true,"discardComments":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"plugins":[null]}!./node_modules/resolve-url-loader!./node_mo
>
> dules/sass-loader/lib/loader.js?{"includePaths":["D://dev//my-project//www//vendor//silverstripe//admin//client//src//styles","D://dev//my-project//www//vendor//silverstripe//admin//vendor//silver
>
> stripe//admin//client//src//styles","D://dev//my-project//www//vendor//silverstripe//admin//client//src//styles","D://dev//my-project//www//vendor//silverstripe//admin//client//src//styles"],"sour
>
> ceMap":true}!./client/src/styles/bundle.scss 11:173893-173936
>  @ ./client/src/styles/bundle.scss
>  @ ./client/src (\/bundle\.scss|[A-Za-z]-story\.jsx?)$
>  @ ./.storybook/config.js
>  @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.st
>
> orybook/config.js
>
> ERROR in ./client/src/font/fonts/silverstripe.woff
> Module parse failed: Unexpected character ' ' (1:8)
> You may need an appropriate loader to handle this file type.
> (Source code omitted for this binary file)
>  @ ./node_modules/css-loader?{"sourceMap":true,"minimize":true,"discardComments":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"plugins":[null]}!./node_modules/resolve-url-loader!./node_mo
>
> dules/sass-loader/lib/loader.js?{"includePaths":["D://dev//my-project//www//vendor//silverstripe//admin//client//src//styles","D://dev//my-project//www//vendor//silverstripe//admin//vendor//silver
>
> stripe//admin//client//src//styles","D://dev//my-project//www//vendor//silverstripe//admin//client//src//styles","D://dev//my-project//www//vendor//silverstripe//admin//client//src//styles"],"sour
>
> ceMap":true}!./client/src/styles/bundle.scss 11:173810-173854
>  @ ./client/src/styles/bundle.scss
>  @ ./client/src (\/bundle\.scss|[A-Za-z]-story\.jsx?)$
>  @ ./.storybook/config.js
>  @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.st
>
> orybook/config.js
>
> ERROR in ./client/src/font/fonts/silverstripe.eot
> Module parse failed: Unexpected character '' (1:0)
> You may need an appropriate loader to handle this file type.
> (Source code omitted for this binary file)
>  @ ./node_modules/css-loader?{"sourceMap":true,"minimize":true,"discardComments":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"plugins":[null]}!./node_modules/resolve-url-loader!./node_mo
>
> dules/sass-loader/lib/loader.js?{"includePaths":["D://dev//my-project//www//vendor//silverstripe//admin//client//src//styles","D://dev//my-project//www//vendor//silverstripe//admin//vendor//silver
>
> stripe//admin//client//src//styles","D://dev//my-project//www//vendor//silverstripe//admin//client//src//styles","D://dev//my-project//www//vendor//silverstripe//admin//client//src//styles"],"sour
>
> ceMap":true}!./client/src/styles/bundle.scss 11:173646-173689 11:173715-173758
>  @ ./client/src/styles/bundle.scss
>  @ ./client/src (\/bundle\.scss|[A-Za-z]-story\.jsx?)$
>  @ ./.storybook/config.js
>  @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.st
>
> orybook/config.js
>

**Comment by NightJar** [comment]
Can confirm.

**Comment by NightJar** [comment]
Looking through the error log I see references to #426 - perhaps the same cause.

**Comment by raissanorth** [comment]
Although seems to be a different error, complaining about missing configuration files - which there seems to be no documentation about setting up.

**Comment by chillu** [comment]
Did you run `yarn` on `admin`, `cms`, `campaign-admin`, `asset-admin` modules? You need all of these before the pattern lib works.

**Comment by NightJar** [comment]
Things work better now, thanks @chillu 
However you'll need to start the storybook with: `node_modules/.bin/start-storybook -p 6006` @wernerkrauss 

At this point it's bringing me to a loading webpage, but then that page is filled with errors instead of patterns. My (shell) console is loaded up with ERRORs about failed parsing due to unexpected characters in the font files, which is reflected the resulting page served to the browser.

This could be an unstable head thing though, unsure.

```
silverstripe/admin                        1.1.x-dev 4166209
silverstripe/asset-admin                  1.1.x-dev 4e88f38
silverstripe/campaign-admin               1.1.x-dev ce283d1
silverstripe/cms                          4.1.x-dev 7dea009
```

**Comment by NightJar** [comment]
So, this actually extends further than here (checking out the pattern library) - building the UI for admin also does not complete successfully on Windows.
See #495

**Comment by NightJar** [comment]
Good news @wernerkrauss - Al Twohill has fixed this for us in https://github.com/silverstripe/webpack-config/pull/24 :)

Ingo's caveat at https://github.com/silverstripe/silverstripe-admin/issues/465#issuecomment-376305218 is still important though, as is adapting the commands to run in a windows shell where applicable.

But it builds, and you can run it :)

**Comment by robbieaverill** [comment]
I wouldn't describe that as a caveat, but a necessary step in order to get the pattern library running. If you think it should be a workaround of some sort/caveat, perhaps we need to make it clearer in the documentation? It's the same for macOS users too of course

**Comment by NightJar** [comment]
I put it here as it's already been mentioned here. I've not read the recent documentation, so didn't want to comment. If it's not a prominent, then it should be - otherwise it leads to confusion such as above and https://github.com/silverstripe/silverstripe-admin/issues/426

**Comment by robbieaverill** [comment]
I don't think #426 is related, but the [documentation](https://docs.silverstripe.org/en/4/developer_guides/customising_the_admin_interface/cms_architecture/#pattern-library) I could find via Google definitely doesn't mention needing to install dev deps in each of these modules. I'll raise a new issue to ensure it gets updated.

**Comment by NightJar** [comment]
Hmm, description indicated that it might be in
>If I run yarn from asset-admin then re-run this in admin, it works.

But a new issue about docs sounds the best solution really :)

**Comment by maxime-rainville** [comment]
We've got a separate module for handling the doc update #586 to include the info as per [Ingo's comment](https://github.com/silverstripe/silverstripe-admin/issues/465#issuecomment-376305218).

From @NightJar, I understand that this is now building on Windows. I'll close this for now, but do let me know if it needs to be reopened.
