### ISSUE TITLE
TreeDropdownField renders no items after navigation + remount

### ISSUE THREAD

**Issue by scott1702** [silverstripe/silverstripe-admin#472]
After navigating to children inside the TreeDropdownField, when the component is mounted to the DOM again (see example scenarios below) then there are no items rendered into the dropdown. This seems to be caused by the `visible` prop on TreeDropdownField, ie. on mount the tree is loaded again and the tree prop is reset for children at the root but the visible prop is still set to the child previously navigated so no items are rendered.

Example scenarios:
- Navigate to child and attempt to save page with failing validation
- Navigate to child items in TreedropdownField, then navigate to other area of CMS with a TreedropdownField of the same ID (e.g. a gridfield of items containing TreeDropddownFields).

![treedropdownfield](https://user-images.githubusercontent.com/10215604/38286359-1246bbb0-3819-11e8-9944-cd8176bcf447.gif)

**Comment by robbieaverill** [comment]
@scott1702 is this the same issue as https://github.com/silverstripe/silverstripe-cms/issues/2112?

**Comment by scott1702** [comment]
@robbieaverill Yep, sure is
