### ISSUE TITLE
Add split/edit/preview toggle component to work with the Preview component

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#480]
In the non-React driven CMS preview feature we have a variety of toggles, one of which is the ability to change whether you're in Edit mode, Preview mode or Split mode (both):

![image](https://user-images.githubusercontent.com/5170590/38527320-2ed1b386-3cae-11e8-8e05-26023ea3faeb.png)

We need to add this as a new React component to work with the existing Preview component as a step towards having a React driven CMS. It's also required for https://github.com/silverstripe/silverstripe-versioned/issues/104.

The Preview component currently uses a PopoverField to render a "more actions" type menu. We could use one of these with the appropriate icons and titles.

## Acceptance criteria

* There can be a toggle button with menu in the Preview component's toolbar
* It is right aligned
* It has font icons for each action
* Changing the state will also change the primary button's caption and icon to that which is selected
* When viewing on a small screen, "split mode" option is disabled with a tooltip/title "Screen is too small"
* When selecting "Edit mode" the preview panel will be hidden, and the toggle component will then show in the main/edit window's toolbar (so user's can switch back into preview again)
* It works on small screens

## Notes

The action handlers for clicking on each state might need to be provided as props to the component, since "switch to edit preview mode" is essentially saying "hide the edit form" and to do so the component would need to know the target to hide.

Implementations of this component will probably need to be responsible for rendering two instances of this component - one in the edit form and one in the Preview component. The edit form component wouldn't be rendered, or would be hidden, when the Preview component is visible, and the Preview component's toggle would always be visible when the Preview component is visible.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/560
- [x] https://github.com/silverstripe/webpack-config/pull/22
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/109

**Comment by raissanorth** [comment]
@NightJar  and I looked into this issue, had to timebox our efforts though. The **WIP** commits for this ticket were made to 

Creative Commoner's fork of the **versioned-admin module**:

- [pulls/1.0/resizeAware-preview-selector](https://github.com/creative-commoners/silverstripe-versioned-admin/tree/pulls/1.0/resizeAware-preview-selector) branch
- last commit 098df38df1384e2e71395499074d33e265a600e6 

as well as

Creative Commoner's fork of the **admin module**:

- [pulls/1/build-view-mode-toggle-component](https://github.com/creative-commoners/silverstripe-admin/tree/pulls/1/build-view-mode-toggle-component) branch 
- last commit 098df38df1384e2e71395499074d33e265a600e6

The component is _functional_ as such, however relies on a variety of props being passed down from parent components. There are still some changes to be made for this to be _usable_.

**Still outstanding are:**

- unit tests
- storybook entry for the component
- a tooltip when the split view button is disabled to alert users that 'Screen size too small'
- minor styling issues such as the top toolbar having to be resized when 'edit' or preview' take on the entire screen width

**Comment by lukereative** [comment]
Hey @raissanorth, I'm not sure if this was discussed with either Paul or Jared but we were trying to move any new action menus in the CMS to use the reactstrap Dropdown component rather than using Popover Field as it's more targeted and accessible for accessing actions. Has this been discussed or considered?

**Comment by raissanorth** [comment]
Thanks @lukereative for raising this. No, it hasn't been considered, I am afraid. Will discuss with the team, @clarkepaul, and @newleeland today.

**Comment by raissanorth** [comment]
I have chosen to use the `react-resize-aware` library in favour of the media queries to handle the logic for changing the view mode states after discussing with @lukereative and @robbieaverill. This is not purely a concern of styling any longer, but of behaviour. The ViewModeToggle component is the controlling unit for this logic.

**Comment by robbieaverill** [comment]
All merged, awesome work @raissanorth!
