### ISSUE TITLE
Gridfield pagination shows changed navigation warning without changes

### ISSUE THREAD

**Issue by matt-in-a-hat** [silverstripe/silverstripe-admin#482]
If you use the pagination buttons within the default model admin gridfield then attempts to navigate away or edit a row will show the warning message:
```
Are you sure you want to navigate away from this page?
WARNING: Your changes have not been saved.
```

Without anything being edited, just press the next page button and it then marks the form as changed.
![image](https://user-images.githubusercontent.com/1852796/38590657-b5b6e906-3d86-11e8-9c34-432f990cff4a.png)

This is happening on SS 4.2.0, see an example set up here https://github.com/mediasuitenz/silverstripe-modeladmin-example

From what I can see, it looks like it might have been happening since #362, and removing the `self.trigger('change');` line does seem to fix it for me. I'm not sure I understand why that was added though @flamerohr ?

**Comment by flamerohr** [comment]
the trigger is needed to update some state inside the GridField, I don't remember what but something else breaks when it's not there.

Also, something else is wrong and you're seeing the popup as a symptom of that, the trigger change isn't the root cause of the issue.

**Comment by tractorcow** [comment]
Possibly related to https://github.com/silverstripe/silverstripe-framework/issues/7997

I think we just turn of change tracking for gridfield (outside of detail form that is).

**Comment by flamerohr** [comment]
it's related :)
I don't think turning off change tracking for gridfield would be a good idea, unless you find a solution which is opt-in for particular fields.
If there's inline editing for the GridField then you'd want those to trigger the change tracker (thinking userforms)

**Comment by ivoba** [comment]
I still have this in SS4.3.
Paginating a Gridfield will cause the "Are you sure you want to leave the page" to pop up.
