### ISSUE TITLE
Client UI cannot be built on Windows

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-admin#495]
While this doesn't matter for many folks, I feel it instantly precludes any community member from contributing, which _is_ a reasonably troubling concern.

The majority of the UI builds just fine, but the webpack pipeline does not complete and ends up rendering errors to the output. This happens at the font stage.

I am using Windows 10, and the shell seems inconsequential (first attempted with git-bash, then with the 'windows default' of `cmd`).

In CMD there is no concept of inlining environment variables:
![image](https://user-images.githubusercontent.com/778003/38959781-126fbe4a-43b6-11e8-9a3b-892f402fd29c.png)

This is not an issue in git-bash, if one does not attempt to run `yarn dev` (and friends) as it jumps to this cmd environment internally it seems. Running `node_modules/.bin/webpack --progress` does successfully run (but not complete). This work around is OK, and *not what this issue is about*. I am simply being thorough in my report as so people don't confuse the issue (or maybe it's pertinent to debugging).

Since webpack config contains `(ENV !== 'production') ? 'source-map' : '',` we'll just omit the env var, and make the call adjustment as above: `node_modules\.bin\webpack --progress` (in CMD, note backslash not forward slash).

Which results in:
```
        ERROR in ./client/src/font/fonts/silverstripe.eot
        Module parse failed: ..client\src\font\fonts\silverstripe.eot Unexpected character '' (1:0)
        You may need an appropriate loader to handle this file type.
        (Source code omitted for this binary file)
         @ ./~/css-loader?{"sourceMap":true,"minimize":true,"discardComments":true}!./~/postcss-loader/lib?{"sourceMap":true,"plugins":[null]}!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?{"includePaths":[...
```
(edited for brevity - but there are also a number of these).

This same error is what pops up in the bash shell, so appears more environmental than command syntax issues.

If one pushes through this results in:
![image](https://user-images.githubusercontent.com/778003/38960411-8365d7ea-43b8-11e8-9a40-34dcb1a08c0f.png)
Which is clearly invalid CSS, and leaves the CMS looking like assets weren't exposed by composer.

This also affects the pattern library (storybook): #465
Although I could get that running, the interface in the browser was non-functional and also littered with the same error as above (unknown char in font, etc.)

# Related PR
* [x] https://github.com/silverstripe/webpack-config/pull/20

**Comment by NightJar** [comment]
Thanks @altwohill it's good to know the environment variable business in the script alias is an easy fix :)
But unfortunately this issue is a bit bigger than that.

Or are you also reporting that you do not hit fatal errors mid-build (in font files) on windows at the current `master` HEAD?

**Comment by maxime-rainville** [comment]
I had a go at fixing this and I think I found the problem. Our webpack rule for handling font file looks like this:
```js
{
    test: /fonts\/([\w_-]+)\.(woff|eot|ttf|svg)$/,
    loader: 'file-loader',
    options: { name: 'fonts/[name].[ext]' }
}
```

If you tweak the test regex to expect a Windows directory separator (`/fonts\\([\w_-]+)\.(woff|eot|ttf|svg)$/`), the build process seems to complete normally.

**Comment by NightJar** [comment]
Neat, I'll give it a go.
Which file am I finding this in?

**Comment by NightJar** [comment]
So what you're saying here is that this should actually be patched [in the webpack config](https://github.com/silverstripe/webpack-config/blob/master/css/modules.js#L117) directly?

**Comment by maxime-rainville** [comment]
@NightJar Yes that looks like the best place to put it. Feel free to do a PR for it if you want. Otherwise, I'll do it when I've got a spare 5 min somewhere.

**Comment by NightJar** [comment]
Hi team, thanks for the work on this! I've tested and it seems to work... however I'd like to point out that this issue is not closed until the following line is also updated to access this dependency change:

https://github.com/silverstripe/silverstripe-admin/blob/1e4bd77f3046e88a8988dc041d7c2de2d910e38b/package.json#L89

**Comment by robbieaverill** [comment]
Looks like the change was released in 0.8.1 - that constraint will allow you to install that - are you having problems with it?

**Comment by NightJar** [comment]
Yes it was released in `silverstripe/webpack-config` `0.8.1` - but this issue is open on `silverstripe/admin`, not `silverstripe/webpack-config`
And unfortunately yes, after updating the `package.json` to pull the change, issues persist.

**Comment by NightJar** [comment]
Have opened a more relevant issue at https://github.com/silverstripe/webpack-config/issues/21
But the fact remains that this issue is not closed, so I should like it to be reopened please (although it amounts to little more than updating the `package.json` now).

**Comment by robbieaverill** [comment]
What would you like the package.json updated to? I don't see anything wrong with it, but I'm happy to reopen the issue for you until it's resolved

**Comment by NightJar** [comment]
It still seemed to pull the unfixed webpack dependency for me - 0.8.0 rather than 0.8.1 - although perhaps I should check I wasn't having a daft moment as reinspecting the constraint it seems it should be fine with the caret.

@altwohill 's suggestion would also be nice - but perhaps that warrants wider discussion about whether or not it belongs here or further up in webpack config also - would it work like that?

**Comment by unclecheese** [comment]
I'm not sure there's anything actionable, here. The latest webpack-config release fixes the issue. The version constraints in the `package.json` afford that version to be installed. It's a single `yarn upgrade` command to get it. Because this only affects the developer experience, I don't see value in issuing six PRs for `yarn.lock` updates just to save developers the trouble of running `yarn upgrade`. Even if we did do PRs, developers would still have to run `yarn` to get the new version.

Does that make sense, @NightJar or have I misrepresented your concern?

**Comment by NightJar** [comment]
>The latest webpack-config release fixes the issue.

How did you test this @unclecheese ?

**Comment by NightJar** [comment]
hahahaha, I can't believe I didn't pick up the slashes added in the fix PR were the wrong way around xD
Sorry for half arsing the check team (and then getting confused as to while it still failed), but @altwohill has come to the rescue :D

https://github.com/silverstripe/webpack-config/pull/24

**Comment by maxime-rainville** [comment]
@NightJar Awesome! Are you OK if I close this one?

**Comment by maxime-rainville** [comment]
@NightJar Sure go for it.
