### ISSUE TITLE
Move link to userhelp, add docs links, and link to community site

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#500]
These designs were done a long time ago to provide CMS users more visibility of useful resources like links to docs, silverstripe.org and gave us the potential to link to a feedback form on silverstripe.org. Although these were provided when we did the responsive menu work, this portion of the work was broken out, but it seems that no issue was created to pick up the rest of the work. 

This also re-located the CMS user help to a new location as specified in the designs.
![image](https://user-images.githubusercontent.com/555033/39164133-fede656e-47d1-11e8-9e76-78ee5a3e2d9a.png)

See larger image https://invis.io/Q6HDDHDVWBT#/291644496_Menu

# Related PRs
* [ ] https://github.com/silverstripe/silverstripe-admin/pull/615

**Comment by robbieaverill** [comment]
Might make sense to move the tooltip from the SilverStripe logo in top left to the bottom one here if this goes ahead

**Comment by robbieaverill** [comment]
Yeah ok. Site summariser would make this less relevant, but it currently does provide more information at a dev configurable level - e.g. CWP is _supposed to_ (broken) show which CWP version you're running instead of the SilverStripe version

**Comment by clarkepaul** [comment]
BTW this is currently in progress, hope to have something PR ready for September.
