### ISSUE TITLE
Rename filter to search

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#502]
Although there is filter functionality within the search, users will be more familiar with the term "Search". We should take a look over the admin to align iconography and labels.

![pasted image at 2018_04_30 12_26 pm](https://user-images.githubusercontent.com/555033/39412620-62f808ac-4c73-11e8-9ede-b4603e16f66f.png)

**Comment by hdpero** [comment]
By the look of icon (magnifier) the title should be "Search" because it is associated with search function, and because when you click it in form it is used labels "Search".

I have created a PR that make this change.

**Comment by robbieaverill** [comment]
Fixed in #536
