### ISSUE TITLE
Allow toast notifications to be added from React

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#504]
If we add some sort of connection between the toast notification system and the Redux store, we should be able to push new toast notifications from React applications anywhere in the CMS.

Currently there are controlled via PHP and AJAX requests.

For example, when reverting to a version in history viewer, ideally we could push a toast notification via Redux. At the moment we'll be rendering an inline FormAlert in the app instead.

# Acceptance criteria
- Toast notification can be used in React
- Existing `jQuery.noticeAdd()` calls still work
- Toasts are not auto-dismissed when the user is interacting with them
- Actions can be added to individual Toast.
- A proper API and documentation is provided so third party developer can use Toast in their own app
- We have clear guidelines where it's appropriate to use toast notification and where it isn't
- Component added to pattern library

# Note
- The purpose of this card is to provide a solid API so we can start using Toast where it makes sense to use them
- We might end up converting a few alerts to toast for to demonstrate the feature, but converting all the existing alerts to to toast is not the goal of this card
- Toast could be use for a lot of other cool things (e.g. async push notification). While that's cool, it should be handle via follow up cards.

# Design
https://projects.invisionapp.com/dsm/silver-stripe/silverstripe-cms/nav/build/asset/componentContainers/5f0fdc1f9e3d52081dbf4408/tab/design?mode=preview

# Pull requests
* [x] https://github.com/silverstripe/silverstripe-admin/pull/1068
* [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1111
* [x] https://github.com/silverstripe/webpack-config/pull/48
* [x] https://github.com/silverstripe/silverstripe-framework/pull/9695
* [ ] ~~https://github.com/silverstripe/silverstripe-admin/pull/1125~~

**Comment by robbieaverill** [comment]
I think there's still a jQuery plugin that we could use via the global window object to push new toast messages...

**Comment by robbieaverill** [comment]
I'm pretty keen to work on this myself, so might pick it up at some point in the next month or two

**Comment by robbieaverill** [comment]
I've had a quick tinker and have come up with a lightweight API that we can start to move towards, gradually in SilverStripe 4 and potentially entirely in SilverStripe 5. You can see the changes here: 



I tested this with a success toast whenever you insert an image into TinyMCE content via the asset-admin module: https://gist.github.com/robbieaverill/59958fdfbdf2064c48ea651c6c9ab41e

```diff
diff --git a/client/src/entwine/TinyMCE_ssmedia.js b/client/src/entwine/TinyMCE_ssmedia.js
index 037f846..7d9ccd1 100644
--- a/client/src/entwine/TinyMCE_ssmedia.js
+++ b/client/src/entwine/TinyMCE_ssmedia.js
@@ -9,6 +9,7 @@ import i18n from 'i18n';
 import React from 'react';
 import ReactDOM from 'react-dom';
 import { loadComponent } from 'lib/Injector';
+import { addMessage } from 'state/messages/MessageActions';
 import InsertMediaModal from 'containers/InsertMediaModal/InsertMediaModal';
 import ShortcodeSerialiser from 'lib/ShortcodeSerialiser';
 
@@ -232,6 +233,8 @@ jQuery.entwine('ss', ($) => {
         this.statusMessage(e, 'bad');
       }
 
+      this.statusMessage('Done!', 'success');
+
       if (result) {
         this.close();
       }
@@ -479,12 +482,7 @@ jQuery.entwine('ss', ($) => {
      */
     statusMessage(text, type) {
       const content = $('<div/>').text(text).html(); // Escape HTML entities in text
-      $.noticeAdd({
-        text: content,
-        type,
-        stayTime: 5000,
-        inEffect: { left: '0', opacity: 'show' },
-      });
+      window.ss.store.dispatch(addMessage(content, type));
     },
   });
 });
```

Follow up questions:

* Do we want to expose a SilverStripe JS API wrapper, such as these `addMessage()` etc functions?
* Do we want to use an existing library instead, such as [react-toastify](https://github.com/fkhadra/react-toastify)?
  * If so, and clients access it directly when pushing toast messages, how do we control the styling, SS specific customisation, etc?
* If we go with a SS JS API wrapper like this, it could potentially use react-toastify under the hook in future
* Do we want to alias the existing `jQuery.noticeAdd()` plugin as `.noticeAddLegacy()`, and change `.noticeAdd()` to use the new API under the hood, ensuring backwards compatibility with existing implementations?
* Do we want `addMessage()` to provide the format for the Redux dispatch, or should it also handle the Redux dispatch as well? Difference is whether you call `window.ss.store.dispatch(addMessage(content, type))` or just `addMessage(content, type)`.

cc @silverstripe/creative-commoners @silverstripe/open-sourcerers

**Comment by maxime-rainville** [comment]
If `jQuery.noticeAdd()` is the way most entwine logic display notification, could we just replace it with some logic that dispatches to the redux store?

That way, any module that displays notification via entwine will automatically switch to using the new react toasts without having to do anything.

**Comment by robbieaverill** [comment]
Yeah that’s what I was thinking with my second to last point

**Comment by maxime-rainville** [comment]
Made a start at https://github.com/silverstripe/silverstripe-admin/pull/1068

**Comment by maxime-rainville** [comment]
Oups ... that wasn't meant to be closed.

**Comment by maxime-rainville** [comment]
The eagle has landed.
