### ISSUE TITLE
CMS field description tooltips/toggles are broken

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-admin#517]
I had no idea this functionality even existed until it was raised on Slack... looks like we broke this: https://docs.silverstripe.org/en/4/developer_guides/customising_the_admin_interface/how_tos/cms_formfield_help_text/#how-to-show-help-text-on-cms-form-fields

This looks like it should be fairly easy to fix (\*gulp\*):

- https://github.com/silverstripe/silverstripe-admin/blob/1.1.0/client/src/legacy/LeftAndMain.FieldDescriptionToggle.js
- https://github.com/silverstripe/silverstripe-admin/blob/1.1.0/client/src/legacy/LeftAndMain.FieldHelp.js

**Comment by selay** [comment]
Which release is this fix expected to come with? still broken in 4.2.x

**Comment by maxime-rainville** [comment]
We discuss this in detail here: https://github.com/silverstripe/silverstripe-admin/pull/518

The general conclusion was that this is something inherently buggy that we won't support.

The "How-to" article was updated to remove the buggy examples by https://github.com/silverstripe/silverstripe-framework/pull/8510

**Comment by GuySartorelli** [comment]
@maxime-rainville The how-to still has instructions for using the `cms-description-toggle` extra class - am I understanding wrong or was that the example that should be removed?
