### ISSUE TITLE
No tooltip on hover for the profile icon

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#533]
All menu items have a tooltip on hover but it seems the profile icon doesn't have one. This is more important when the menu is collapsed as you can't see the text which supports the icon.

It doesn't have the "title" attribute.

<img width="155" alt="log_in___my_council_and_co-funded_development_submissions_-_cwp_-_silverstripe_confluence" src="https://user-images.githubusercontent.com/555033/40688736-548f3f1e-63f3-11e8-9f07-37fac32502a1.png">

**Comment by clarkepaul** [comment]
I think it should be the persons name, then at least it'll be the same pattern as the other menu items.

**Comment by clarkepaul** [comment]
Asked around it was a 50/50 thing whether to use "My profile" or "Joe Bloggs", even Facebook and Google take different approaches.

**Comment by robbieaverill** [comment]
My vote would be "My profile"
