### ISSUE TITLE
Modal close icon has no cursor change, and doesn't use icon library

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#548]
The close icon on modals don't have a cursor change when you hover over the action. We should swap the close icon for one from the icon font library so it fits the rest of the UI (suggested classes: .btn .font-icon-cancel .btn--icon-xl .no-text).

<img width="111" alt="pasted_image_19_06_18__3_14_pm" src="https://user-images.githubusercontent.com/555033/41573988-903e9150-73d3-11e8-8584-4e29fc463f43.png">

We've had a mention that the modal close action was hard to click, I've test this functionally myself and didn't see any issues but worth confirming again when this issue is picked up (perhaps through browser testing).

**Comment by sachajudd** [comment]
@clarkepaul cursor change and font-icon is implemented. Just wondering if the hover here is meant to be blue?
<img width="193" alt="close-modal" src="https://user-images.githubusercontent.com/24258161/47119063-fa07b700-d2c5-11e8-9d5d-3ab652f867fb.png">

**Comment by clarkepaul** [comment]
Nope shouldn't be blue, should be the same as the other icons.
