### ISSUE TITLE
Remove border on insert media dialog actions

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#56]
The styles for border above the actions is too generic (there shouldn't be a border in this case).
![image](https://cloud.githubusercontent.com/assets/555033/25791827/0d391200-3417-11e7-8537-d1bc9aa838eb.png)

**Comment by dhensby** [comment]
Will this be making 4.0 release?

**Comment by clarkepaul** [comment]
It hasn't been marked as Recipe 4.0.0-rc2 so I doubt it.

**Comment by sachajudd** [comment]
Seems to be fixed, closing.
