### ISSUE TITLE
Remove warning note (in south toolbar) about publishing on Security groups

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#567]
Security groups/users don't have a draft state (and the things within them) so don't require the warning about publishing draft items. The notification has also been created using a button so it has a active (you can click it) which makes you think it preforms an action (which it doesn't). 

From a users perspective this is very confusing. For example, in this instance it might make them think its going to publish all of the users blog posts—as when you click into the user their blog posts are visible.

Note: Feedback I have received from a dev makes me think that its purpose might not be clear enough even for areas where it should be displayed, I will create a separate issue if I come up with a possible recommendation.

![image](https://user-images.githubusercontent.com/555033/42540859-2822fcdc-84f4-11e8-9eff-420c7d14a4bd.png)

cc @chillu

**Comment by lukereative** [comment]
Would a solution to to check if a dataobject has any owned records (through `findOwned`) before showing this warning? Owned records are the ones that will be published. As for the message itself, that is a tough cookie.

**Comment by chillu** [comment]
We've decided to remove it everywhere, because this feature can't be implement in a performant way that makes sense to users. Closing.
