### ISSUE TITLE
SiteTree page icons update and accessibility fixes

### ISSUE THREAD

**Issue by hdpero** [silverstripe/silverstripe-admin#574]
Current SiteTree page icons 
![sitetree-page-icons](https://user-images.githubusercontent.com/13778690/42943368-d76bd12c-8b62-11e8-90ee-1133a75ed27f.png)
 are kind of ugly (IMHO) and doesn't match current UI of SilverStripe 4 Admin Interface, further more they are PNG, and not SVG sprite. 

Is there a new version of icons?

# Related PRs
* [ ] https://github.com/silverstripe/silverstripe-admin/pull/803
* [ ] https://github.com/silverstripe/silverstripe-cms/pull/2364
* [ ] https://github.com/silverstripe/silverstripe-errorpage/pull/29

**Comment by hdpero** [comment]
@robbieaverill @clarkepaul  Based on I didn't find suitable icons in current [SilverStripe Font Icons Reference](https://github.com/silverstripe/silverstripe-admin/blob/master/client/src/font/icons-reference.html) I've created an SVG Sprite from [IcoMoon aplication](https://icomoon.io/app) and they are from [_IcoMoon - Free set_](https://icomoon.io/#icons-icomoon) with CC BY 4.0 licence.

Icons are as follows:
![sitetree-pagetype-icons](https://user-images.githubusercontent.com/13778690/43220361-27ae2612-904a-11e8-882d-0f47d9146c89.png)

- Page
- BlogPost (SilverStripe Blog module)
- Blog (SilverStripe Blog module)
- Profile (SilverShop module)
- Home _(HomePage class or URLSegment="home")_
- VirtualPage
- ElementalPage (usage with DNADesigns Elemental module - if Page Type exists)
- CartPage (SilverShop module)
- CheckoutPage (SilverShop module)
- CalendarPage (TitleDk SilverStripe Calendar module)
- ErrorPage
- RedirectorPage

Here is how they look like in fresh SS4 install:
![sitetree-add-page-form](https://user-images.githubusercontent.com/13778690/43220620-c80c151a-904a-11e8-89e9-c6b004d3928f.png)

**Comment by DorsetDigital** [comment]
I'd agree the current icons aren't that pretty, but I'd also put a slightly different perspective (for what it's worth):

I like a clean site tree, without the noise of different icons.  The names of the pages ought to provide at least some hints as to what they are.  (I don't even like the icons you get with the blog module)

Lots of different icons in the SiteTree can be a visual distraction and, for a lot of users, not especially helpful.    If they can't work out that the page titled 'Checkout' is the checkout page without a pretty icon, then they maybe have bigger issues!

My vote would be to keep a minimalist set of icons for the core pages, and let module authors decide if they want something.   

Or, maybe an option to turn on or off 'fancy icons' too, for those curmudgeonly types like me ;-)

**Comment by clarkepaul** [comment]
Thanks for looking into this, they are the last set of icons that need to be replaced from what I know of. I feel that the set needs to look more cohesive as these look a little busy specially if they were amongst the site tree pages all at once, they also need to work with the modified and draft status dot so they will get even busier. 

With the right icons we can get them added to the admin set as SVGs, I guess what I thinking is that its an actual set designed for the likes of a site tree rather than UI icons, might not be as easy finding such a set though. From my quick search there are no obvious sets which seem to cater to the likes of a site tree like we need although Fontawesome has quite a few page type icons and its already an existing set we've used icons from (the other set we heavily use is Entypo). I will add the most obvious icons from Fontawesome that will be useful for pages. I'll share back here which ones have been added so that any gaps can be filled by adding custom SVGs into the set. 

We really need them to be added to the core set to be used consistently across all modules and UIs.

**Comment by clarkepaul** [comment]
These are what I've come up with, I don't expect all of these to be used but thought if I get enough variety it should keep most devs/users happy having some variety when building custom templates and modules.
<img width="576" alt="pasted_image_27_07_18__2_46_pm" src="https://user-images.githubusercontent.com/555033/43299415-410499ba-91ae-11e8-9724-a28a7e2b9498.png">

I've made them the same size as the old icons so hopefully we don't need to reposition the modified and draft dot. I've stayed away from icons which are filled as they attract a lot of attention when they are all next to each other.

Feedback/question/requests welcome before I add these to the set properly.

**Comment by be2n** [comment]
Do we need an event page icon?

**Comment by hdpero** [comment]
> Feedback/question/requests welcome before I add these to the set properly.

Icons are nice. @clarkepaul are you planing to add them to Font Icons?


> **From Slack**
> tractorcow [Yesterday 12:01 AM]
> I wonder if we should switch to font icons for everything
> it'd be great if sitetree could support that too.

I agree with Damian it would be more versatile if Sitetree supports font icons.

**Comment by clarkepaul** [comment]
Yup thats the plan, I be adding them to the font but they can also be used as SVGs if we choose to do so at a later date.

**Comment by kinglozzer** [comment]
I think those icons look excellent. My suggestions to add to the list:

- Product icon (I’m thinking ecommerce modules)
- Something representing “location” - a map/map marker perhaps?
- Magnifying glass (representing pages with a search/filtering)

Alternatively, if it’s possible to provide a template and an easy way to define your own icons we could leave the default set a bit lighter 😉

**Comment by clarkepaul** [comment]
Current set...
![image](https://user-images.githubusercontent.com/555033/43809504-975f127a-9b06-11e8-9376-e2a5c9cf3d03.png)

**Comment by hdpero** [comment]
@clarkepaul these are great! 
What is a HEX color for those icons?

**Comment by clarkepaul** [comment]
We would apply the colour #6F84A7 which is (or will be) the variable $grey-500 in the CMS.

**Comment by JorisDebonnet** [comment]
Beautiful. When might these be implemented? I don't see a milestone :)

**Comment by clarkepaul** [comment]
They are already part of the CMS ready for use, although updating the site tree still needs to be done.

**Comment by clarkepaul** [comment]
FYI we've got someone on this issue currently, hoping to get it in the next release.

**Comment by ScopeyNZ** [comment]
@chillu we might want to reopen that issue about the accessibility of the active state because all the new icons have just been merged in!

**Comment by maxime-rainville** [comment]
@sachajudd Was doing a PR to update the doc about how to use this feature. We should wait until that is merged to close this issue.
