### ISSUE TITLE
when loading the CMS, an M shows - what is the M for?

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-admin#577]
When you load the CMS, you first see an "M" ... Looks like the M of Magento. Why?

![image](https://user-images.githubusercontent.com/167154/43180538-bf68f31a-902c-11e8-9bd4-9e9d4c557462.png)

Here are some visuals:

![image](https://user-images.githubusercontent.com/167154/43180582-f84e5a62-902c-11e8-8cc3-3057154c090a.png)

shows:

![image](https://user-images.githubusercontent.com/167154/43180590-043efd04-902d-11e8-9c07-6b869b1355e0.png)

Once the font-family is loaded:

![image](https://user-images.githubusercontent.com/167154/43180607-16eef72e-902d-11e8-881c-dd73ae346e7b.png)

You see this:

![image](https://user-images.githubusercontent.com/167154/43180610-21230082-902d-11e8-928e-c388e075e8a0.png)

I kept seeing the "M" in a client presentation - and it looked weird... 

Maybe it is better to use "L" for Logo or "S" for Silverstripe or a non-visible / meaningfull character (e.g. an underscore or a dot)

**Comment by guci0** [comment]
With loading and logo of SilverStripe – it was better how they were pictures.

**Comment by bummzack** [comment]
Mapping icons to character-ranges is bad practice though. Icons should be mapped to the [private use unicode-range](https://en.wikipedia.org/wiki/Private_Use_Areas).

**Comment by sunnysideup** [comment]
@kinglozzer - I am not sure about the network issue, because i was at my client who have an office downtown Wellington.  The server is in Auckland, and it is a fast server - yet it kept happening.

**Comment by dhensby** [comment]
> Mapping icons to character-ranges is bad practice though. Icons should be mapped to the private use unicode-range.

yeah - that has struck me as odd that we'd replace letters with a completely unrelated icon

Another solution is to hide the logo until the fonts are loaded

**Comment by NightJar** [comment]
For reference, loading a site on my local development is enough to manifest this issue. I can't even imagine loading the CMS over the actual internet >.>

In the very least I have a strong agreement with @bummzack :)

**Comment by mhenden** [comment]
I've just had the same problem on SS3 and SS4 CMS interfaces. Still trying to get to the bottom of the problem...

![ss-admin-glyphs](https://user-images.githubusercontent.com/5275084/43556570-7eeeccaa-9654-11e8-96da-93f68326eb43.png)

**Comment by lukereative** [comment]
Has been fixed by https://github.com/silverstripe/silverstripe-admin/pull/582 as it's now an SVG.

**Comment by robbieaverill** [comment]
>For reference, loading a site on my local development is enough to manifest this issue. I can't even imagine loading the CMS over the actual internet >.>

The internet's probably faster than your local environment :trollface:
