### ISSUE TITLE
ModelAdmin shows "Unlink" action instead of "Delete" with SS 4.2

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-admin#578]
Apparently, the default components in `GridFieldConfig_RecordEditor` have changed in SS 4.2, from using **unlink** instead of the previous **delete** (see: https://github.com/silverstripe/silverstripe-framework/commit/385e9e105c20d42687cd6713d975a1b45e28e32c).

Since unlinking records is quite useless in `ModelAdmin`, the edit gridfield should be updated accordingly.

# Related PR
* [x] https://github.com/silverstripe/silverstripe-framework/pull/8293

**Comment by dhensby** [comment]
bah - well, it didn't make 4.2.1

**Comment by mediabeastnz** [comment]
Will this be in 4.2.1+?

**Comment by Jellygnite** [comment]
Potential bug:
I had canDelete() set to return false and when I used Unlink in model admin it still removed the item from the database. This wasn't a many_many list just a straightforward model admin for a dataobject.

**Comment by maxime-rainville** [comment]
@Jellygnite Can you confirm what version of Framework you are using?

**Comment by Jellygnite** [comment]
SilverStripe (Version - CMS: 4.2.1)

**Comment by Jellygnite** [comment]
I thought it was using 4.2.1 framework but maybe that is the issue, just looked at composer.json in vendor/silverstripe/cms folder and it reports: 
"silverstripe/framework": "^4.1@dev",

**Comment by maxime-rainville** [comment]
@Jellygnite @mediabeastnz The fix will be available in 4.2.2 which should be release in the next few days.
