### ISSUE TITLE
Submit ModelAdmin->ImportForm() via ajax

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-admin#584]
https://github.com/silverstripe/silverstripe-admin/blob/6ac3ba56783f553a5a567140de3e7984edfb48bf/code/ModelAdmin.php#L538

related to #583 and https://github.com/silverstripe/silverstripe-framework/issues/6319

**Comment by chillu** [comment]
Why is this necessary? We'll probably do this as part of a larger ModelAdmin refactor into React+GraphQL, but I'm keen for the bugtracker not to become a "graveyard of good ideas", unless they have an owner (you?) with a specific plan to implement.

**Comment by Zauberfisch** [comment]
just saw the comment, and since I'm doing work on an related issue, I figured I'll bring it up. Happy to have that closed though as a wont-fix. I don't really mind this being non-ajax.

**Comment by chillu** [comment]
Happy to look at a 4.x pull request, but until then, it's probably fine to close this issue :)
