### ISSUE TITLE
Auto-publish our pattern library to a public website

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#587]
The pattern library is currently generated by devs on their local environment. This is fine for dev-focused workflows, but doesn't help our product designers (@sachajudd @newleeland @clarkepaul) who want to keep up-to-date with the components as they are actually built. 

Publishing a pattern library would also be a clear signal to the developer community about the extensibility of the CMS UI, giving them confidence in the system without requiring the (relatively large) investment of a full git clone of our modules, with an `npm build` step, just to see what's actually available in the pattern library.

This could be done via Github Pages, which would remove the need for any deployment flows in SilverStripe Platform.

# Pulls requests
* [x] https://github.com/silverstripe/silverstripe-framework/pull/8488
* [x] https://github.com/silverstripe/silverstripe-admin/pull/685

**Comment by maxime-rainville** [comment]
We could use the same workflow we are using to [auto-publish the upgrader](https://github.com/silverstripe/silverstripe-upgrader/pull/127)

**Comment by clarkepaul** [comment]
How much effort would this one be? could it be a hackday thing? or can we access the pattern library through our existing community demo, or UAT demo?

**Comment by maxime-rainville** [comment]
I'm thinking hack day project. It would require:
* getting the story book build script working properly ;
* configuring a travis job to auto build it ;
* get travis to push to build files to a  `gh-page` branch.

**Comment by maxime-rainville** [comment]
Sorry forgot to reference the original issue. Yep it's all fixed and I add linked up the 2 related PRs.
