### ISSUE TITLE
Consistency of toolbar actions positions

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#60]
Buttons (of button toolbar) should align with the button area rather than the icon within the button. Just so it is consistent with the rest of the CMS.

**Campaigns example**
![screen_shot_2017-08-28_at_11_20_33_am](https://user-images.githubusercontent.com/8085295/29754933-a4532c38-8be3-11e7-9c7e-bf9c67a53549.png)

## AC 
I would like to see all buttons on the button toolbar aligned consistently so that I feel I'm using a finished product that is stable and robust.
- See that Button toolbar throughout the CMS is aligned from the button area and not from the icon. (SEE campaign example above)
- I want to see "Add Campaign" Button from more noticeable, i.e. a primary button.

## Archive
Buttons with no background (.btn-secondary) should align by the icon rather than the surrounding button area, applies left side of toolbar and right side.
<img width="557" alt="pasted_image_10_05_17__5_17_pm" src="https://cloud.githubusercontent.com/assets/555033/25884187/a860cc44-35a4-11e7-80e8-fcaa3237753c.png">
<img width="165" alt="pasted_image_10_05_17__5_19_pm" src="https://cloud.githubusercontent.com/assets/555033/25884228/ec95d058-35a4-11e7-9d6e-19b8528af7e1.png">

Related:
Drop area on the "Up folder" icon can be improved as it is covered when an image is dragged on top of it.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/221
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7340

The above pull requests fix:

![silverstripe_-_security_](https://user-images.githubusercontent.com/318116/30043999-1ee0a0c2-924f-11e7-9831-abf2826c65cd.png)

![silverstripe_-_files_](https://user-images.githubusercontent.com/318116/30044000-1f02519a-924f-11e7-8b6b-3b6ea84d6672.png)

**Comment by chillu** [comment]
It's a major new area, and looks messy in a quite visible place, so setting `impact/medium` (/cc @clarkepaul)

**Comment by phalkunz** [comment]
It looks fine now

![silverstripe_-_campaigns_](https://user-images.githubusercontent.com/318116/30041976-427fb2fa-9242-11e7-83ae-cd8fe5f47da2.png)

**Comment by clarkepaul** [comment]
It would be good if this code was removed to that the alignment issue didn't happen again.
```
.toolbar .btn-toolbar>.btn-secondary:first-child, .toolbar .btn-toolbar>.grid-csv-button:first-child, .toolbar .btn-toolbar>.grid-print-button:first-child {
    margin-left: -5px;
}
```
