### ISSUE TITLE
LeftAndMain::getClientConfig url includes version param in the query string

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#616]
**Version: SS 4.2.1**

When `LeftAndMain::getClientConfig()` is called on a page that has `?stage=Stage` in the URL, it includes this argument in the URL that is given for clients.

```diff
    /**
     * Returns configuration required by the client app.
     *
     * @return array
     *
     * WARNING: Experimental API
     */
    public function getClientConfig()
    {
        $clientConfig = [
            // Trim leading/trailing slash to make it easier to concatenate URL
            // and use in routing definitions.
            'name' => static::class,
            'url' => trim($this->Link(), '/'),
```

Notes:
* `$this->Link()` will naturally include it
* We "trim leading/trailing slash to make it easier to concatenate URL", but we can't concatenate when easily when it has a query string in it
* This breaks history viewer when using it on content blocks and stage=Stage is present

This is coming from `$this->extend('updateLink', $link)` in which `VersionedStateExtension` adds the query string argument. Introduced in https://github.com/silverstripe/silverstripe-versioned/commit/32dcc4d34fa3490dfa4b1dd877448673176ca236

**Comment by robbieaverill** [comment]
I wonder whether client implementations should be updated to handle query strings in this instead. It clearly wasn't originally designed with them in mind though.

**Comment by ScopeyNZ** [comment]
Related: silverstripe/asset-admin#824

**Comment by robbieaverill** [comment]
Versioned admin fix at https://github.com/silverstripe/silverstripe-versioned-admin/pull/54

**Comment by ScopeyNZ** [comment]
I feel as though the fix here would be to make sure all the forms in the javascript config sections do not have `?stage=Stage` on their schemaUrls:

![image](https://user-images.githubusercontent.com/3260989/44639455-19920a00-aa10-11e8-8a5f-d5ec9baee09f.png)

**Comment by robbieaverill** [comment]
Yeah, but the code in `Config.getSection` in core is currently extremely un-opinionated, it feels rude to me to add lookups for `url` and remove its query string args there.

The backend is also too late, because we've written it in a way that means user code is unlikely to be extensible (see X) this bug is probably already out there. An example is history viewer where it happens when we overload the core getClientConfig method then add a new entry with `$this->Link()` called again. I think we need to fix it in the frontend.

We could make the change in FormBuilderLoader instead maybe?

**Comment by robbieaverill** [comment]
Yeah let's do that, then it's contained

**Comment by ScopeyNZ** [comment]
I'm fine having it in FormBuilderLoader - it seems odd to always strip query parameters at that point though.

**Comment by robbieaverill** [comment]
It would be better to remove them at the backend source, but we can't (see https://github.com/silverstripe/silverstripe-admin/issues/575)

**Comment by robbieaverill** [comment]
Damn, so the way options are:

* Add logic into LeftAndMain to return Link() without any query string 
* Implement this on the client end (not FormBuilderLoader)

If we strip it out in FormBuilderLoader we lose the actual query string params we might want. 

I don't want to write code into it that is looking for malformed URLs that we generate then fix those...

**Comment by robbieaverill** [comment]
Closing as a duplicate of #607, thanks @maxime-rainville
