### ISSUE TITLE
Customise React EditForm: a HOC of TextField

### ISSUE THREAD

**Issue by froger** [silverstripe/silverstripe-admin#617]
## Affected Version 
```
phpunit/phpunit                           5.7.27 The PHP Unit Testing framework.
silverstripe-themes/simple                3.2.0  The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/recipe-cms                   4.2.1  SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-plugin                1.3.0  Helper plugin to install SilverStripe recipes
```

## Description

Hello,
I am trying to customise the CMS (EditForm) and I want to do a react's HOC on a TextField. Following [this documentation](https://docs.silverstripe.org/en/4/developer_guides/customising_the_admin_interface/how_tos/customise_react_forms/), it seems pretty easy : 

```
import Injector from 'lib/Injector';
Injector.transform(
  'my-transformation',
  (updater) => {
    updater.component('TextField', ({Component, ...props}) => {
      console.log('HOC TextField with props', props);
      return Component;
    });
  }
);
```
__I expected__ : Seeing logs on my pages, as `Title` is a `TextField`
__I got__ : nothing, the `update.component` is called, but nothing happen.

I am using the `"@silverstripe/webpack-config": "^0.10.0"`, and my file build successfully.
I require it through `SilverStripe\Admin\LeftAndMain#extra_requirements_javascript` and my bundle appears in sources, after all the js files : 
```
[… other scripts]
  <script type="application/javascript" src="/resources/vendor/silverstripe/cms/client/lang/fr.js?m=1533880379"></script>
  <script type="application/javascript" src="/assets/_tinymce/tinymce-cms-c0d4113039.js"></script>
  <script type="application/javascript" src="/resources/mycustomfield/admin/client/dist/main.bundle.js?m=1535365162"></script>
``` 

The documentation about how to work with React in the CMS is not really helpfull, and I suspect I need to do some entwine hacks, like the [silverstriper/seo module did](https://github.com/SilverStripers/seo/blob/master/client/src/bundles/bundle.js). 

Thanks for your help,

**Comment by chillu** [comment]
@flamerohr @unclecheese Can you please help? :)

**Comment by flamerohr** [comment]
The syntax seems incorrect, try this:
```
 updater.component('TextField', (Component) => { console.log('HOC TextField with props', props); return Component; });
```
You're right, the documentation could be improved, I'll see if I have time to make a pull request to improve that later today.

**Comment by robbieaverill** [comment]
@froger did @flamerohr's suggestion fix your issue?

**Comment by froger** [comment]
@robbieaverill sorry, didn't gave feedback about the answer. 
No it didn't really help me, but I ended not using the Injector, like silverstripe/seo did and I did implement the feature I wanted at that time. 

There's still some lacking documentation about how we can use the injector, but that's another issue, so I will close mine.

**Comment by robbieaverill** [comment]
I'd like to follow up on this to make sure our docs are suggesting working examples, so will add to my todo list

**Comment by markdynamo6** [comment]
Any update to this yet? Froger's original problem still seems to be an issue.
