### ISSUE TITLE
Replace PropTypes with external lib

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-admin#644]
In React 16, the `PropTypes` library has been removed and put into its own `prop-types` external library.

## Pull Requests
- [ ] https://github.com/silverstripe/silverstripe-campaign-admin/pull/118
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2264
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/836
- [x] https://github.com/silverstripe/silverstripe-admin/pull/645
- [ ] https://github.com/silverstripe/silverstripe-versioned-admin/pull/63
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/8385
- [x] https://github.com/silverstripe/webpack-config/pull/27

**Comment by lukereative** [comment]
I think it was auto-closed because one of the associated issues was merged.
