### ISSUE TITLE
Use TinyMCE Mobile for mobile devices

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#657]
# Overview

TinyMCE had a mobile variation of its editor for a least a year - about time we start using it, and create a viable authoring experience on smaller screen sizes with touch inputs: https://go.tiny.cloud/blog/tinymce-is-going-mobile/

# Acceptance Criteria

 * The mobile TinyMCE variation is automatically chosen for touch based devices (regardless of screen size)
 * Custom HTMLEditorField configurations (e.g. removing a button from the toolbar) are honoured
 * The custom SilverStripe additions like "edit image" buttons and "link" dialogs work as expected
 * The JS/CSS bundle size loaded by the CMS does not increase significantly
 * There is developer documentation on how to adjust if using a custom theme

# Notes

 * We're working towards wider mobile compatibility through responsive designs. There's a lot more to it, e.g. network performance, bundle sizes, JS/CSS processing. This is out of scope for this card.
 * Here's the current 4.2 loaded in Mobile Safari:

![image](https://user-images.githubusercontent.com/111025/45791038-f3444f00-bcdb-11e8-8108-06337ec199fd.png)

**Comment by sachajudd** [comment]
After discussing with @clarkepaul we are not sure if this mobile variation of TinyMCE is suitable for desktop users so we would need to be able to swap it completely out, and therefore create more overhead to support (seems more suited to a mobile app). Hopefully, we can reduce the UI actions by condensing the options initially seen. See [comment at #653](https://github.com/silverstripe/silverstripe-admin/issues/653#issuecomment-425759593).  

We might need someone to see if we can change the displayed options based on viewport size. Perhaps we can provide designs for an idyllic situation where we can have slightly different options for mobile and desktop and see if they can be developed.

**Comment by chillu** [comment]
> we are not sure if this mobile variation of TinyMCE is suitable for desktop users so we would need to be able to swap it completely out

No, it's specifically designed for touch, and shouldn't be used on non-touch devices (mostly desktops). So this card is predicated on the assumption that we can dynamically detect a "touch device" and use the correct TinyMCE theme (mobile or not)

**Comment by chillu** [comment]
Aaaactually, we might wait with this until the TinyMCE 5 upgrade: https://go.tiny.cloud/blog/announcing-tinymce-5-developer-preview/

> Although a majority of content creation still occurs on the desktop, it goes without saying that your application should fluently adapt to mobile and tablet users as well. Around 14% of our CDN traffic is from mobile or tablet, and this is steadily increasing. Starting in version 5, TinyMCE will now support mobile without the need to specify or load a separate theme. The “Mobile” theme capabilities are being rolled into the main theme and will just work.

See https://github.com/silverstripe/silverstripe-admin/issues/675

**Comment by GuySartorelli** [comment]
Sounds like TinyMCE 5 onwards doesn't need an explicit mobile version, and CMS 5 uses TinyMCE 6, so I'm gonna close this one
