### ISSUE TITLE
SearchForm has been removed from ModelAdmin

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-admin#662]
There's a commit in 4.3 (1.3) that has removed `SearchForm` from model admin:

https://github.com/silverstripe/silverstripe-admin/commit/7aa0fad69447f8820324dd7671ddbedfb8269b16#diff-fdb2c6ab0eacaf1803e1d9c64a3cb318L278

Although I understand the sentiment with the new search implementation I think this is surely too much of a BC break to be released as a minor?

## PRs
- [x] https://github.com/silverstripe/silverstripe-admin/pull/665
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8420
- [ ] silverstripe/silverstripe-framework#8441

**Comment by chillu** [comment]
Cringe. @lukereative @maxime-rainville  Can you please get across this? Customising `MyModelAdmin->SearchForm()` is extremely common. My understanding from scoping this work was that we're using form schema to represent existing search forms as JSON, not that we're completely removing the method. Maybe it's been moved to an extension in another commit? Would that still allow this type of cusotmisation?



Also, why isn't the search documented in the 4.3 release notes? https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/04_Changelogs/4.3.0.md

**Comment by chillu** [comment]
Note that customising most public methods in ModelAdmin is common. Please go through the API surface of this class and see where expectations would be broken in a minor release, and how we can fix this. We also need to make `showSearchForm` work, for example.

**Comment by sminnee** [comment]
Note that the customisable search forms are included in the down-arrow, as shown below. But they don't appear to work.

![image](https://user-images.githubusercontent.com/59968/46442469-3b786c80-c7c6-11e8-8613-b0c3464f9ac6.png)

**Comment by maxime-rainville** [comment]
That looks like a different issue. I'm getting weird pagination results as well. I'll split it up.

**Comment by maxime-rainville** [comment]
Raised as a separate issue in #672

**Comment by sminnee** [comment]
Has this issue been resolved, or did you close it accidentally?

**Comment by maxime-rainville** [comment]
@sminnee The original problem this issue was tracking has been resolved. I think the behavior you are seeing is a different problem, so I raised a distinct issue to track it #672.
