### ISSUE TITLE
Cannot clear advanced filters from search form

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#668]
**Version: 4.3.x-dev**

## Steps

* Go to Security
* Add a new member: Test Test
* Open search form in members GridField
* Set advanced filter: First Name to "test" and search
* Open advanced filters and clear the First Name, then search

## Expected

GridField should reset to an unfiltered state

## Actual

"test" remains in the First Name field

## Workaround

Click on the "X" to clear the search

## PRs
- [x] https://github.com/silverstripe/silverstripe-admin/pull/687
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8477

**Comment by chillu** [comment]
@lukereative @maxime-rainville

**Comment by bergice** [comment]
I'm unable to replicate this issue. Tested with Chrome on `4.3.x-dev`.

Please reopen if this is still an issue with further details.
