### ISSUE TITLE
Search Form Schema doesn't handle more complex relational search field

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#672]
If you try to use a more complex search that references relations, they don't appear to affect your search results.

I've confirmed in the CWP kitchen with frameworktest running. We probably want to do a PR against frameworktest so we have more fancy search field to test against going forward.

From @sminnee at https://github.com/silverstripe/silverstripe-admin/issues/662#issuecomment-426821181
> Note that the customisable search forms are included in the down-arrow, as shown below. But they don't appear to work.
> 
> Although this form was created by searchable_fields modifications rather than SearchForm customisation:
> 
> ```
>     private static $searchable_fields = array(
>         'Name',
>         'Company.Name' => array( 'title' => 'Company' ),
>         'Company.Employees.Name' => array( 'title' => 'Colleague' ),
>         'Company.Offices.City' => array( 'title' => 'Company city' ),
>     );
> ```
> 
> ![image](https://user-images.githubusercontent.com/59968/46442469-3b786c80-c7c6-11e8-8613-b0c3464f9ac6.png)

## PRs
- [x] https://github.com/silverstripe/silverstripe-admin/pull/687
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8477

**Comment by chillu** [comment]
Yep agree with the `impact/high` assessment, this will be a quite common API usage
