### ISSUE TITLE
TinyMCE width in latest release has a smaller width

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#674]
This issue has been picked up by a community member where the width of TinyMCE has reduced between 4.1 and 4.2. It would be good to get someone to look into this issue to see if the change was intentional or not. I don't see any reason why we need to reduce the width. Its only on very large screen that we wouldn't want it full screen width.

Original feedback here on the forum https://forum.silverstripe.org/t/cms-editor-width/1028/3

4.1
![image](https://user-images.githubusercontent.com/555033/46513060-570d7100-c8b3-11e8-80fe-0188c5921678.png)

4.2
![image](https://user-images.githubusercontent.com/555033/46513067-5ffe4280-c8b3-11e8-8654-47e73f753648.png)

#### PR's

- [x] https://github.com/silverstripe/silverstripe-admin/pull/695

**Comment by chillu** [comment]
This is the main interaction surface area of the CMS, and makes it look unprofessional. When you pick this up, please do a root cause analysis on how this happened - we really need to avoid those types of regressions going forward :/

**Comment by bergice** [comment]
This is caused by https://github.com/silverstripe/silverstripe-admin/pull/446, which intended to give form fields the same width, but seems to have also been applied to TinyMCE. TinyMCE should have a max width, but otherwise full width.
