### ISSUE TITLE
Upgrade to TinyMCE 5

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#675]
### Overview

As at the time of writing, the CMS is running version 4.6.5 of TinyMCE while there is a new major version (v5).

https://www.tiny.cloud/docs/general-configuration-guide/system-requirements/#supportedtinymceversions

### Notes
* Related: https://github.com/silverstripe/silverstripe-admin/issues/657

**Comment by robbieaverill** [comment]
Looks awesome. I might finally start to like WYSIWYG editors =D

**Comment by TheSpyder** [comment]
Glad you like it! We released the dev preview to get some early API feedback as early as we can, I’m anticipating we will reach beta in a few weeks.

Let us know if there’s anything we can help with!

**Comment by christopherdarling** [comment]
Just a heads up, TinyMCE v5 is now stable - https://go.tiny.cloud/blog/tinymce-5-power-meets-beauty/

**Comment by TheSpyder** [comment]
Stable, and we’ve done three bug fix releases already :)

**Comment by wilr** [comment]
@chillu any progress on this one and if it's likely to hit in SilverStripe 4 or would be targeted at SilverStripe 4?

Running into a few issues with the outdated version of TinyMCE within SilverStripe (e.g https://github.com/tinymce/tinymce/issues/3276)

**Comment by ScopeyNZ** [comment]
Provided it can be implemented in a non-breaking way with the PHP API (pretty certain this is doable) then there's no reason it can't be in 4.5. We're not due to release that for a few months yet though. Happy to receive contributions - I don't think this is on our radar...

**Comment by wilr** [comment]
Thanks @ScopeyNZ happy to contribute it. I think the issue above will be a blocker for our go-live on SS4 so didn't want to wait. I'll give it a crack 💪

**Comment by wilr** [comment]
WIP is on my fork. Screenshot of what it looks out of the box @clarkepaul  happy with this or do we want to theme to fit into SilverStripe styles now.

![Screen Shot 2019-08-06 at 2 10 45 PM](https://user-images.githubusercontent.com/101629/62506308-440d5980-b854-11e9-9ace-55d8d46d0e6a.png)

**Comment by clarkepaul** [comment]
Na doesn't need theming, I think its more important to get the right default actions in place (ensure there is a like for like). I see a few actions that I'm not familiar with in there. Really good to see the full-screen edit in there and might be a few to remove by default. Do you know if we can re-arrange or limit actions in smaller views @wilr ?

**Comment by TheSpyder** [comment]
Which action is showing the bomb (in between image and code on the second toolbar line)? That's our placeholder for unknown icon.

**Comment by wilr** [comment]
@TheSpyder "Insert new media from the web" our custom plugin for oembed. I'll need to see why our icon isn't displaying.

**Comment by TheSpyder** [comment]
Oh, it's custom. Of course. I expect it's because we only support SVG icons in v5 - but we have had plenty of requests to allow other image formats (particularly since v4 didn't restrict this) so our designer has agreed to plan for opening that up.

**Comment by ScopeyNZ** [comment]
I'm completely in favour of limiting the supported icon format to SVG. It's nice to encourage people _not_ to use PNGs or some icon font.

**Comment by patricknelson** [comment]
Big +1 on finally moving forward with SVG's and ensuring we have backward compatibility with existing SS v4 API. Only minor issue with that might be the icons and reconciling that with backward compatibility in the CMS since this isn't a major version change on _our_ end.

I'm more for graceful degradation in this respect. For example, say you're working on upgrading SS v4.4 to SS v4.5 and you find that now custom icons are now missing and didn't realize it until after you went into production. I'd rather have those ugly old school pixelated icons there and working, find out later and queue it up as a hotfix later than have it effectively break for end users.

**Comment by chillu** [comment]
@wilr Are you still working on this? How far away from a PR are ya? I'm assuming it's intended as a replacement in core, as opposed to an opt-in module, given how much core UI is tied around TinyMCE?

**Comment by wilr** [comment]
Yep it's intended to replace the current TinyMCE 4. Will aim to finish this off next week for review (WIP is at https://github.com/silverstripe/silverstripe-admin/pull/923) I had it at enough a working state for our use case but that didn't include some of the media things.

**Comment by GuySartorelli** [comment]
CMS 5 uses tinymce 6
