### ISSUE TITLE
React breadcrumb goes backwards

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#699]
The react breadcrumb parent levels are displayed backward ... the root level is displayed on the far right while the direct parent is displayed to the left. You need at least 3 level or more to see it. This can be replicated in the pattern library and in asset-admin.

I've confirmed with @clarkepaul and @sachajudd that this is not the intended behavior.

![image 1](https://user-images.githubusercontent.com/1168676/47119701-64215b80-d2c8-11e8-9764-26b950bfeb83.png)

https://www.youtube.com/watch?v=P8XxXvAd5d0&feature=youtu.be

#614 is opened to address inconsistencies between the react breadcrumb and legacy breadcrumb. We might want to look at these two issues together.

# Pull Request
* [ ] https://github.com/silverstripe/silverstripe-admin/pull/925

**Comment by maxime-rainville** [comment]
Setting impact to medium as it's really confusing, but doesn't prevent you from doing anything.

**Comment by ScopeyNZ** [comment]
Closed in #925
