### ISSUE TITLE
New help menu toggle is not accessible

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#714]
The markup has a `<button>` as the trigger, which makes it focusable. But the trigger isn't mapped as an `aria-expanded` on the area it toggles: https://www.w3.org/WAI/GL/wiki/Using_aria-expanded_to_indicate_the_state_of_a_collapsible_element. I'm not actually sure how that's treated differently from a `display: none`, but it seems best practice.

/cc @sachajudd @scott1702

**Comment by maxime-rainville** [comment]
Fixed by https://github.com/silverstripe/silverstripe-admin/pull/718
