### ISSUE TITLE
DateField shows US format instead of NZ format in IE11 and Firefox

### ISSUE THREAD

**Issue by pjayme** [silverstripe/silverstripe-admin#723]
## Affected Version

SS - 4.2.1
CWP - 2.1

## Description

The issue occurs in IE11 and Firefox browsers, we have confirmed that we have set the locale correctly in the configs and CMS settings.

This occurred with a custom field as well as an existing CMS field.

## Steps to Reproduce
In the `silverstripe/reports` module the `PagesDueForReviewReport` features a set of date filters which display the dates in US format instead of NZ format. 

# Pull Requests
- [x] https://github.com/silverstripe/silverstripe-admin/pull/630
- [x] ~https://github.com/silverstripe/silverstripe-admin/pull/781~
- [x] ~https://github.com/silverstripe/silverstripe-framework/pull/8362~
- [x] https://github.com/silverstripe/silverstripe-admin/pull/791
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8726

# Closes
https://github.com/silverstripe/silverstripe-admin/issues/631

**Comment by lukereative** [comment]
I think this is related to https://github.com/silverstripe/silverstripe-admin/issues/631

**Comment by rupachup** [comment]
I'm changing the labels, estimate & epic to match the old issue under silverstripe-framework, #8332. It looks like both are still open on the board, but if you click on the old issue it takes you to the new issue (so I can't close the old issue)...

**Comment by maxime-rainville** [comment]
Everything is working now and we shall never talk about the DateTime field ever again.
