### ISSUE TITLE
HtmlEditorField insert link toggle broken with pre3.2 form ID/classes set

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-admin#726]
On one of my sites we have the FormTemplateHelper_Pre32 enabled for forms, this seems to break the HtmlEditorField insert link feature, when selecting the link type the form options aren't updated. 

This looks to be down to https://github.com/silverstripe/silverstripe-framework/blob/3.6/javascript/HtmlEditorField.js#L582-L597 where it's searching for elements with an ID ending with _holder

When I disable the FormTemplateHelper_Pre32 extension, the insert link dialog works as expected.

**Comment by maxime-rainville** [comment]
From the description, I don't think this will affects SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

If someone think this will cause trouble in SS4, please leave some extra details and I'll reopen.
