### ISSUE TITLE
SS4 - No loading states for react components

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-admin#735]
I've noticed a few times whilst clicking around ss4 that there's sometimes a flicker whilst it loads the component or data. This happens with the campaign form when you click 'Add campaign', the breadcrumbs and most notable the files area starts by saying 'No items found' before loading the items.

I think anything that relies on retrieving data should have a `hasloaded` state set to false so that it can be relayed to the user that the page/component isn't ready yet.

**Comment by maxime-rainville** [comment]
That's already been fixed.
