### ISSUE TITLE
NTH: Disable "overflow hidden" on CMS, in case of reload with error

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-admin#736]
Having to disable the overflow hidden on the CMS html, to view the rendered error, annoys me a bit. It would be nice that if there's an error detected, the overflow hidden isn't set.
I understand that this is not easy to detect/implement, so it's a very big NTH.

**Comment by maxime-rainville** [comment]
This is no longer an issue in SS4. 

![image](https://user-images.githubusercontent.com/1168676/49978355-f5523d00-ffae-11e8-89fb-65310a9ed012.png)

Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
