### ISSUE TITLE
BUG: Forward and Back button behaviour

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe/silverstripe-admin#737]
Navigating using the forward and back browser buttons is inconsistent.

**Steps to reproduce:**
1. Load the CMS at `admin/pages`
2. Navigate to the Reports section using the left menu
3. Navigate back using the browser's back button

**Expected:**
URL changes back to `admin/pages` and the pages section loads

**Actual:**
URL changes back to `admin/pages` but the section doesn't load.

**Comment by maxime-rainville** [comment]
Just tested it in SS44 and it works fine.

Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
