### ISSUE TITLE
SecurityAdmin breadcrumbs show duplicates

### ISSUE THREAD

**Issue by halkyon** [silverstripe/silverstripe-admin#742]
Breadcrumbs in SecurityAdmin get duplicates after saving a group.

Steps to replicate:
1. Go to admin/security
2. Add a new group by clicking the "Groups" tab, then hit "Add Group" button
3. Fill out the group name, call it "My Group", but don't set a parent group
4. Click "Create" to create the group (reloads to show the newly created group)
5. Click "Save" to save it again

Breadcrumbs are now broken:

Expected: "Security / Groups / My Group"
Actual: "Security / Groups / My Group / My Group"

If you click "My Group" link in the breadcrumbs you're taken back to the root of SecurityAdmin, but instead of just showing "Security" in the breadcrumbs, it shows as "Security / My Group".

Affects SilverStripe 3.1.x-dev, all browsers.

# Pulls requests
* [x] https://github.com/silverstripe/silverstripe-admin/pull/962

**Comment by maxime-rainville** [comment]
I think the problem is with this bit of code: https://github.com/silverstripe/silverstripe-admin/blob/05a081b45413af15ce763a1532e1562f754fea54/code/LeftAndMain.php#L1187-L1206

On the first load, `$record` will be unset, so it's skip the condition. After you saved the group however, the logic kicks in and the last crumbs gets duplicated.

This doesn't get triggered for Member or Permission because they are not Hierarchies.

**Comment by maxime-rainville** [comment]
Got the Versioned issue sorted. Just need to double check if this Polymorphic relationship issue is still a problem and write some unit test.

**Comment by maxime-rainville** [comment]
The security breadcrumb is kind of  mess: https://youtu.be/ilP69DzQQxw

In the video, notice the following problems:
* When viewing a specific user, the breadcrumb just says "Security > Smith, John". It should arguably say "Security > Users >  Smith, John".
* Groups and Roles come out as "Security > Groups >  Administrator" and "Security > Roles >  Role name", however when you click the middle crumb, you don't get taken back to that specific tab of the security section.
* When you save a group, the breadcrumb gets all confused and displays the full group hierarchy in breadcrumb ... if you click one of those extra crumbs, everything goes to custard and all the other security breadcrumb starts showing that group hierarchy no matter what.

**Comment by maxime-rainville** [comment]
I removed the buggy code and simplified the behavior https://github.com/silverstripe/silverstripe-admin/pull/962

Even if the "Display hierarchy in breadcrumb" logic was working correctly, it's not clear to me this would provide much benefit.

**Comment by maxime-rainville** [comment]
This issue has been worked on as part of a larger initiative focused on reducing the experience debt of the SilverStripe CMS.

Thank you for taking the time to raise this issue and/ or provide feedback supporting the implementation.

This is an initiative from the teams maintaining the commercially supported module list. If you're interested to read more about this initiative and keep up with our progress have a look at our [blog post on experience debt](https://www.silverstripe.org/blog/weve-got-experience-debt-in-our-sights).
