### ISSUE TITLE
Tag React component styles are too broad

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#747]
**Version: SS 4.3.x-dev**

https://github.com/silverstripe/silverstripe-admin/blob/1.3.0-rc1/client/src/components/Tag/Tag.scss#L1-L12

These styles are too broad. They're applying themselves to a TagField instance in the blog module and breaking the layout of it (https://github.com/silverstripe/silverstripe-blog/issues/558).

How many places would be affected if we changed the `tag` class to something less generic?

# Pull Request
* [x] #754

**Comment by robbieaverill** [comment]
soft ping on @maxime-rainville - if we change this before SS 4.3 is released then it won't be a breaking change later ;)

**Comment by maxime-rainville** [comment]
I see what you mean. How about we update the class to say something like `.tag-component`?

Although, I would humbly express the view that this tag component probably ought to be the primary tag UI going forward and that every other tag should work off it for consistency. (My tag is better yours!!!  :wink: )

**Comment by robbieaverill** [comment]
Sounds good, and agreed :-)

**Comment by robbieaverill** [comment]
Thanks @maxime-rainville
