### ISSUE TITLE
Default site name is slightly off center

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#761]
**Version: SilverStripe 4.3.x-dev**

![image](https://user-images.githubusercontent.com/5170590/49093083-ac3a8300-f263-11e8-9475-d517ed227210.png)

If you remove the `1em` right margin it's correctly centered

**Comment by purplespider** [comment]
Looks like the margin wasn't updated when the SilverStripe icon was removed:

![](http://spdr.me/nqlD0p+)

More obviously, it results in this with a longer site name:

![](http://spdr.me/HD4a2Z+)

Ideally we'd be able to easily add the site's favicon into the place where the SilverStripe logo used to be, this would keep the bar consistent.

**Comment by robbieaverill** [comment]
PR at #856
