### ISSUE TITLE
Hot keys for jquery.entwine.inspector are the same as the emoji shortcuts on OSX

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-admin#768]
Probably not the highest of importance, file is added through [here](https://github.com/silverstripe/silverstripe-admin/blob/86282b10235358c019355fa5984ef681b2a3eb7d/code/LeftAndMain.php#L697). 
The short cut is `control + cmd + space`

Would be good to change to something that's not as likely to be taken 👍

Reproduce by going into any admin page and entering the mentioned keys

# Related PRs
* [ ] #821

**Comment by robbieaverill** [comment]
How do you reproduce this? I tried it in TinyMCE and I get an emoji popup (TIL) but no entwine inspector

**Comment by adrhumphreys** [comment]
From pressing it anywhere in the CMS
![Uploading Screen Shot 2018-12-04 at 2.57.03 PM.png…]()

**Comment by chillu** [comment]
There's a separate "entwine debug" js file which brings up some kind of inspector. I think it's only enabled in non-prod modes. I agree that we should map this to a less used key combo, or change entwine to document how to invoke this dialog via JS in the browser console.

**Comment by maxime-rainville** [comment]
Do we know for fact this debugged even works? I've try enabling it and all I get is a blank panel.

![image](https://user-images.githubusercontent.com/1168676/50750651-b613c500-12aa-11e9-8012-b0c7ee9850f8.png)

Whatever I do, nothing shows up in the inspector.

**Comment by chillu** [comment]
I've definitely used it before, without it there's little chance to understand what Entwine actually does ;)  https://github.com/silverstripe/silverstripe-admin/pull/821
