### ISSUE TITLE
Broken clipping on some loading spinners

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-admin#780]
*CMS is literally unusable* :trollface: 

<img src="https://media.giphy.com/media/yN42IMPs6ilJLT4FXD/giphy.gif" width="60" height="59" />

(the filled “S” has square tips)

The loading spinner on the tree view is always affected, the “full screen” spinners are _sometimes_ affected. I can’t really find a pattern to it!

The HTML for the SVG always seems to be the same, the only thing that changes is the URL for the `clip-path`. E.g. it might change from `admin/pages/edit/show/1#spinner__animation__mask` to `admin/pages/edit/EditForm/1/field/ElementalArea/item/1/edit#spinner__animation__mask` depending on which section is loaded, but as far as I’m aware both should be fine...

**Comment by robbieaverill** [comment]
Impact rating bumped, thanks for bringing this up!

**Comment by maxime-rainville** [comment]
What browser are you seeing this in? I've never seen this in FireFox.

**Comment by kinglozzer** [comment]
Chrome 72 on OS X here

**Comment by robbieaverill** [comment]
Reproduced in the site tree loading animation with Chrome 71, OSX

**Comment by maxime-rainville** [comment]
Just saw it on Chrome 70 on Ubuntu. I don't think Firefox is affected.

**Comment by kinglozzer** [comment]
I haven’t seen this issue for a while, I’m going to assume it’s been fixed
