### ISSUE TITLE
PopoverOptionSet search field styling is broken

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#792]
**Version: 4.x-dev**

See https://silverstripe.github.io/silverstripe-admin/?knob-Search=true&selectedKind=Admin%2FPopoverOptionSet&selectedStory=Custom%20Search&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

![image](https://user-images.githubusercontent.com/5170590/50297929-d99adb00-0475-11e9-9ca3-7af9905e3421.png)

**Comment by ScopeyNZ** [comment]
https://github.com/silverstripe/silverstripe-admin/pull/766?

**Comment by robbieaverill** [comment]
Oh yeah, haha
