### ISSUE TITLE
Pattern lib does not work on IE 11

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#794]
If you try to access the pattern library on IE 11 you get the following error
![image](https://user-images.githubusercontent.com/1168676/50791682-6d4e2180-1327-11e9-9fda-3f1fea0e69c5.png)

This makes it more difficult to test UI components in IE11. Edge works fine.

Storybook isn't super clear about what version it supports, but the showcase in their example page seem to work fine with IE11. We're still on version 3 and they've release version 4 two months ago ... that may or may not be related.

# Pull requests
* [ ] https://github.com/silverstripe/silverstripe-admin/pull/795

**Comment by maxime-rainville** [comment]
Actually it was pretty simple problem with the Icon story.

**Comment by robbieaverill** [comment]
Fixed with #795
