### ISSUE TITLE
Form field placeholders are too hard to distinguish from actual data

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-admin#805]
One of these is a placeholder, the other is a real value:

<img width="365" alt="screenshot 2019-01-15 at 15 40 28" src="https://user-images.githubusercontent.com/1655548/51191257-e88d7580-18db-11e9-8527-dc72f3b14e62.png">

Observed in Chrome 72 on OS X

# Related PRs
* [x] #806

**Comment by newleeland** [comment]
It looks like Grey-600 for both value and placeholder,

**In the design (in DSM)**
currently the designs use Grey-700 for values and use Grey-300 for placeholders,  which make it look like a placeholder but does not meet AA contrast standards. 

**Design issue**
If we increase it to greys contrast for placeholders to Grey-500, which passes the contrast standards they look the a value, as grey 500 and grey 700 don't look too different.

**Potential solutions**
Option 1
- Change values colour to Grey-800,
- Change placeholder to Grey-500, and _italicize_
Option 2
- Change values colour to Grey-800,
- Change placeholder to Grey-400, and _italicize_ (compromise a little)
Option 3
If we use material design where placeholder becomes that label once value is entered
@clarkepaul @sachajudd

**Comment by clarkepaul** [comment]
My preferred option in the mean time is actually not to use placeholder text at all, the label should be enough information. Additional guidance can be added to the main label, description (below the field), and we also have a right label. Placeholder text is not typically read by screen readers so shouldn't be relied upon.

If we need to have an option available in the meantime, I think the placeholder text should at least have a contrast of 3:1, although this would still fail accessibility tests. Try that italicised and see if there is enough difference.
> G183: Using a contrast ratio of 3:1 with surrounding text and providing additional visual cues on focus for links or controls where color alone is used to identify them.

Material doesn't use placeholder text for the same reasons. It might be a nice UX but doesn't provide any more info than a typical field and label. Something to consider for the future but not needed as part of this issue.

**Comment by robbieaverill** [comment]
Closed since #806 was merged, thanks @kinglozzer =)
