### ISSUE TITLE
Add a getter for ModelAdmin::$modelClass

### ISSUE THREAD

**Issue by JoshuaCarter** [silverstripe/silverstripe-admin#812]
Changes to ModelAdmin.php has caused a break in silverstripe-multisites

See https://github.com/symbiote/silverstripe-multisites/issues/96 for an outline of the issue.

This could be easily fixed in `silverstripe-multisites` by exposing `ModelAdmin::$modelClass` with a getter.

I'm happy to PR that in if someone can confirm that it's a suitable change?

Cheers.

**Comment by ScopeyNZ** [comment]
I think that's a reasonable enhancement. It would be a minor change though and would be released in version 1.4 of this module.

I've renamed the title of this issue to align with the suggestion :)

**Comment by chillu** [comment]
Yep, confirmed that's a good idea - but I'll close the enhancement ticket for it. PR welcome :)

**Comment by JoshuaCarter** [comment]
@chillu Cheers, PR here: https://github.com/silverstripe/silverstripe-admin/pull/813
