### ISSUE TITLE
Follow up review of Betterbuttons ported into core

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-admin#815]
Follow up design review and comments following Better buttons which was ported into core last year.
Reference: #436

Although very close to what we envisioned currently core does not match the initial designs pitched. Seeing what we currently have I've reconsidered the "Previous" and "Next" buttons due to catering for disabled states. See the [Styleguide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/folder/components/5b5e5d2963c7ad0012bc21f6) for the new designs and I'm open to feedback if anyone has any suggestions. We haven’t added any buttons without text yet in the CMS but because these are new custom styles I think we can achieve the same result we initially pitched for. 

Design and functionality review:
- [ ] Plus-circle width should be 26 x 26px
- [x] Something a bit strange going on with the hover and border of the plus-circle
![image 9](https://user-images.githubusercontent.com/24258161/52018556-af960780-254f-11e9-82d8-a511068837d5.png)
- [x] The element currently is not accessible (tested using Axe) and will need to have aria-labels for people who use screen readers and can be used when tabbing throughout the CMS.
- [x] It would be great to add the [tooltips](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5c53b3b8b8926e1087a4f294) as this will help new users who have never used BetterButtons to understand the component before using it.
- [x] As @ScopeyNZ suggested in the referenced pull request there is some specific styling and it probably makes sense to define the Betterbuttons styles in BEM format and also use existing variables.
- [x] The loading indicator should be the default page SilverStripe loading indicator rather than inside the Prev or Next buttons. @ScopeyNZ raised a good point about still being able to enter content and press save or publish if you were on slow internet or on a mobile device.

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/8953
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/873

**Comment by robbieaverill** [comment]
Bump - this is pretty ridiculous for a new feature to be missing so many basic requirements. Happy to pick this up myself if the OSers are stretched for time.

**Comment by chillu** [comment]
@bergice @unclecheese Reminder that we're committed to creating accessible UI by default (context: https://github.com/silverstripe/silverstripe-admin/issues/436).

**Comment by robbieaverill** [comment]
> Plus-circle width should be 26 x 26px
I think the way it's designed at the moment, the minimum size it can be is 32px

**Comment by robbieaverill** [comment]
I've fixed everything mentioned except for the button sizing. I think it's OK the way it is. We can open a separate follow up issue referencing this if you disagree @sachajudd when you get back.

**Comment by unclecheese** [comment]
Thanks for all your work on this, @robbieaverill. This wasn't a great merge. It didn't get the scrutiny it merited due to the pressure to get it into 4.3, which didn't even end up happening. It should have been subject to a final review from @sachajudd before merging, and as the peer reviewer, I'll own that.

I'd like to fast-track this and get it in as a post-RC patch level fix, if @chillu is okay with that. I don't think we can confidently deliver this feature in 4.4 with these known issues, especially if we have what appears to be a comprehensive set of fixes for them sitting in peer review.

Thanks again for jumping in.
