### ISSUE TITLE
CheckboxField and left margin

### ISSUE THREAD

**Issue by andreaslindahl** [silverstripe/silverstripe-admin#829]
There seems to be a layout issue with CheckboxFields - they don't line up with other fields. See screenshot. The left margin seems to be off with about 20 pixels.

<img width="351" alt="checkboxfield" src="https://user-images.githubusercontent.com/239697/52843172-a7b69580-3101-11e9-83f8-dbae6e5ab172.png">

**Comment by robbieaverill** [comment]
Hi @andreaslindahl, which version are you using please?

**Comment by andreaslindahl** [comment]
I'm using 4.3

**Comment by robbieaverill** [comment]
This should be fixed in the latest 4.3.x release. Please feel free to reopen if you're still experiencing it. See https://github.com/silverstripe/silverstripe-admin/pull/840
