### ISSUE TITLE
TinyMCE Background Colour Improvement

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-admin#83]
The shade of grey used as the TinyMCE toolbar background isn't used anywhere else in the CMS, and so the WYSIWYG toolbar doesn't look as integrated as it should.

How about changing it to the same colour as the CMS header bars? (#F0F2F4)

**Before:**
![](http://spdr.me/GaX8Ug+)

**After:**
![](http://spdr.me/39ZwY+)

Yes, it's a subtle change, but I think it makes a big difference.

**Comment by dhensby** [comment]
Sounds sensible. Can you create a PR?

**Comment by purplespider** [comment]
Would add this if I could, but not been able to get the tooling setup for editing the CMS frontend. :(

**Comment by dhensby** [comment]
What's not working for you?

you'll need npm, yarn and webpack and that should be "it". What OS you working on?

**Comment by flamerohr** [comment]
I'm blind, I can't see the difference :(

**Comment by purplespider** [comment]
@flamerohr Either replace your black and whole monitor with a colour one. :P Or look here for screenshots of the more refined skin: #425

**Comment by flamerohr** [comment]
@purplespider yeah, the contrast isn't that different enough for me to see it :P

**Comment by clarkepaul** [comment]
If the output is the same colour as the north toolbar that is enough of a change (that should be the intention I think), they are a similar shade so it is subtle.
