### ISSUE TITLE
admin 4.3 should require graphql 3

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-admin#830]
Admin expects graphql to exist. 

It relies on recipe-cms to install this, but if you've installed recipe-core + admin, you don't necessarily get graphql.

It should specify the dependency itself.

Presumably graphql 3 is required.

**Comment by robbieaverill** [comment]
Can we close this now?

**Comment by sminnee** [comment]
I think this might be an erroneous report.
