### ISSUE TITLE
BUG Chrome 58 breaks tinymce 4.3

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-admin#84]
See:
 - https://github.com/tinymce/tinymce/issues/3611
 - https://github.com/extras-evolution/tinymce4-for-modx-evo/issues/29

We are currently on tinymce 4.3.11. I suggest we update to at least 4.5.7, preferable 4.6.1
 
## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/95 - for ss4
- [x] https://github.com/silverstripe/silverstripe-framework/pull/6986 - for ss3

**Comment by chillu** [comment]
This broke 3.x as well according to Nicole.

**Comment by chillu** [comment]
Looks like somebody has already backported it to 3.x: https://github.com/tinymce/tinymce/issues/3611#issuecomment-300625326

**Comment by clarkepaul** [comment]
This also affects the resizing of images directly in the editor, once an image is selected you should be presented with drag handles to resize the image (works well in Safari still).
We should be testing against this interaction as well.

**Comment by flamerohr** [comment]
Yeah, if resizing broke then I'd choose to open a separate story for that...
As this issue is more focused on unbreaking being able to select an image ;)

Luckily this instance resizing is unaffected... it was just the browser API to select an image had changed.

**Comment by tractorcow** [comment]
https://github.com/silverstripe/silverstripe-admin/pull/95#pullrequestreview-42471743 can be merged on green.
