### ISSUE TITLE
Require re-authentication before updating email

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-admin#852]
Re-authentication is already required for a logged in member who wants to update their password, but this should be extended to updating an email address as well.

From the [OWASP Cheatsheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#require-re-authentication-for-sensitive-features):

>In order to mitigate CSRF and session hijacking, it's important to require the current credentials for an account before updating sensitive account information such as the user's password, **user's email**...

**Comment by maxime-rainville** [comment]
Is this related to the 2FA project?

**Comment by ScopeyNZ** [comment]
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8599
