### ISSUE TITLE
TreeDropdownField hover state text colour broken

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-admin#853]
Assuming text colour on hover over the item's parent should be white for the chevron and the text itself, the text colour doesn't change.

![hover colour issue](https://user-images.githubusercontent.com/233342/54799905-14561e80-4cc4-11e9-9073-94712c9d0780.png)

### ACs
- Renders as expected in the CMS _and_ the pattern library
- The additional points laid out in https://github.com/silverstripe/silverstripe-admin/issues/853#issuecomment-623765986 are addressed

**Comment by michalkleiner** [comment]
Is there a standardised way how SS tests colour contrast? If I do a fix for this, might be good to test it as well.

**Comment by clarkepaul** [comment]
Some designs here for the original development, as for contrast we should have done checks in design when these were created although variables in the CMS might not be exactly matching anymore. I would think using "near to" variables would be acceptable. https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5acd939108f7520011a65e5c

Seems the main fix for this is just white text.

**Comment by sachajudd** [comment]
Note: The field border colour also does not match the other fields, should be #ced5e1.

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-admin/pull/1166
