### ISSUE TITLE
CMS panel rendering bug

### ISSUE THREAD

**Issue by bergice** [silverstripe/silverstripe-admin#858]
# Issue 

- When clicking on `Pages` or `Reports` in the CMS panel there is a weird color and scaling animation visible on the CMS panel items.

- There also seems to be an unnecessary ajax load (`/admin/pages/`) which refreshes the whole page. Ideally it should just load the cms content area.

# Attachments
See [video of issue](https://gfycat.com/deepignoranteland).

# Expected Outcome
- No color and scaling to be applied to the CMS panel items.
- No unnecessary reloading of whole page, just the cms content area should be loaded.

# Affected Version
`4.3.x`

**Comment by michalkleiner** [comment]
That's a duplicate, but can't find the previous issue. @robbieaverill might know?

**Comment by ScopeyNZ** [comment]
https://github.com/silverstripe/silverstripe-cms/issues/1866 possibly?

**Comment by chillu** [comment]
Yep, closing as duplicate
