### ISSUE TITLE
PHP 7.3 [Warning] "continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by benhtn** [silverstripe/silverstripe-admin#871]
I think I’ve found a bug that arises in 7.3 with the use of continue in switch statements.  I get this Warning when loading Files, which causes the admin interface to fail in dev mode on the AJAX call to /admin/graphql/types:

[Warning] "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
GET /silverstripe/admin/graphql/types
Line 355 in /Applications/MAMP/htdocs/silverstripe/vendor/webonyx/graphql-php/src/Validator/Rules/OverlappingFieldsCanBeMerged.php

```
Source
346                         $selection->selectionSet,
347                         $_visitedFragmentNames,
348                         $_astAndDefs
349                     );
350                     break;
351                 case NodeKind::FRAGMENT_SPREAD:
352                     /** @var FragmentSpreadNode $selection */
353                     $fragName = $selection->name->value;
354                     if (!empty($_visitedFragmentNames[$fragName])) {
355                         continue;
356                     }
357                     $_visitedFragmentNames[$fragName] = true;
358                     $fragment = $context->getFragment($fragName);
359                     if (!$fragment) {
360                         continue;
361                     }
```
Here’s the PHP note in Backward Incompatible Changes for 7.3:
https://www.php.net/manual/en/migration73.incompatible.php

**Comment by robbieaverill** [comment]
There's a new version of the GraphQL module available which is PHP 7.3 compatible. You can either update to use it in your project, or disable warnings in your current project if that's not feasible.
