### ISSUE TITLE
[4.4] "Add new page" screen shows both font and image icons for page types

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#872]
**SS 4.4.x-dev**

This branch now supports font icons for page types, but if you also have an image defined it shows both over the top of each other:

![image](https://user-images.githubusercontent.com/5170590/56995442-e682c480-6bf5-11e9-8d67-27de34013899.png)

**Comment by ScopeyNZ** [comment]
I'm not sure it's actually a bug. Obviously it looks terrible, but the code just adds the page class as a CSS class. It's up to whomever to use that CSS class. CWP uses this to set icons but I'd argue that now that's just a bug in CWP - it should use `icon_class` configuration.

**Comment by ScopeyNZ** [comment]
Okay nevermind - looking deeper I see the whole `getPageIconURL` and `LeftAndMainPageIconsExtension` craziness. This is a bug.

**Comment by ScopeyNZ** [comment]
This is entirely an issue with `cms` - PR on that repo (referenced above).

**Comment by robbieaverill** [comment]
Fixed in the PR above
