### ISSUE TITLE
Update jQuery 3.x to latest release

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#875]
Separate from removing jQuery 1.x, see https://github.com/silverstripe/silverstripe-framework/issues/3384#issuecomment-490286255

See https://github.com/silverstripe/silverstripe-admin/network/alert/yarn.lock/jquery/closed

**Comment by brynwhyman** [comment]
Latest release is now 3.4.1

**Comment by chillu** [comment]
Raising priority since there's known security issues in jQuery <3.4, see https://github.com/silverstripeltd/cwp-demo/issues/21

**Comment by brynwhyman** [comment]
We'll do this as part of the following internal release issue: https://github.com/silverstripeltd/product-issues/issues/48

**Comment by Cheddam** [comment]
Fixed in #990.
