### ISSUE TITLE
[4.4] Search form date fields are too wide for the search form

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#878]
**SS 4.4.x-dev, Chrome 74 on MacOS**

![image](https://user-images.githubusercontent.com/5170590/57349786-7fde4780-71af-11e9-833a-b66e719b4856.png)

The date pickers don't fit within their container.

I feel like there's a duplicate issue for this somewhere, sorry in advance if there is.

**Comment by brynwhyman** [comment]
Closing as a duplicate of the newer https://github.com/silverstripe/silverstripe-admin/issues/1036 (as that has a PR)
