### ISSUE TITLE
Don't use record-specific Redux Form identifiers

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#89]
In order to interact with Redux Form data, you need to use [Selectors](http://redux-form.com/6.7.0/docs/api/Selectors.md/). These require a `FormName` argument. We register our forms with name = schema url. This URL is record specific. Which makes it impossible to hook into forms unless you know the current record identifier used for this form - which makes for tight coupling of form behaviour to components managing their state.

Note: This is a similar issue to the dependency injection service names, e.g. `admin/assets/EditForm/schema/99` schema url vs. 'TextField.AssetAdmin.EditForm` service name. We could reuse these service "namespaces"?

**Comment by unclecheese** [comment]
Yeah, this is why my initial suggestion was to use wildcards in service names. Either that, or we need to expand the API of `FormBuilder` to accept an arbitrary form name in addition to the `schemaUrl`. 

In either case, we're going to need some hierarchical way to reference a service. 

* "All the text fields"
* "all the text fields in AssetAdmin"
* "All the text fields in AssetAdmin edit form"
* "The Title field on the AssetAdmin edit form"

**Comment by chillu** [comment]
@unclecheese To be clear, this card is about redux-form selectors - I've just mentioned it here for context. I assume that service names (specifically for forms) are addressed in https://github.com/silverstripe/silverstripe-framework/issues/5630

**Comment by flamerohr** [comment]
I think this has been addressed through the original `Injector.form` API and this pull request as well https://github.com/silverstripe/silverstripe-admin/pull/188
