### ISSUE TITLE
'Interface Language' label styling is bad

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-admin#892]
### Description
A small thing, but in mobile view, the 'Interface Language' label in `/admin/myprofile` looks bad. Looks like it's not quite using the right CSS class.

![image](https://user-images.githubusercontent.com/15868440/59171947-90605400-8b99-11e9-88cd-097b2128de34.png)

### Version
Tested using SS4.4.x

**Comment by robbieaverill** [comment]
Is it the blurry text? Which browser are you using?

**Comment by maxime-rainville** [comment]
Couldn't replicate on Firefox and Chrome emulation. Couldn't replicate natively on Android with Chrome or Firefox.

**Comment by robbieaverill** [comment]
I can't reproduce it either, @brynwhyman feel free to reopen with more info
