### ISSUE TITLE
GridField react component tightly coupled with CampaignAdmin?

### ISSUE THREAD

**Issue by cwchong** [silverstripe/silverstripe-admin#898]
Hi, not quite sure if this is a bug or "feature", but looking at "client/src/components/GridField/GridField.js" there seems to be a lot of references to CampaignAdmin in the text rendered.

I am trying to create a LeftAndMain extension to manage dataobjects, and would like to re-use this GridField component where possible.

Does this mean I cannot do so? Since the references to CampaignAdmin are pretty much hardcoded?

**Comment by chillu** [comment]
Sorry, it's not a general purpose component yet - we'll get there eventually :) See https://github.com/silverstripe/silverstripe-admin/issues/463
