### ISSUE TITLE
BUG Form change detection attaches itself to all forms

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-admin#90]
At the moment change detection is attaching itself to all forms, not simply those that submit to a dataobject. E.g. search forms, insert-link forms. These incorrectly prompt the user to save the form before they navigate away, creating a highly negative user experience.

Traced back to a change in BootRoutes.js which checks all redux forms.

https://github.com/silverstripe/silverstripe-admin/pull/76/files#r118858608

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-framework/pull/7045
- [x] https://github.com/silverstripe/silverstripe-admin/pull/115
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/509
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/29

**Comment by flamerohr** [comment]
Revert this PR to re-enable the feature https://github.com/silverstripe/silverstripe-admin/pull/92
