### ISSUE TITLE
SilverStripe logo has disappeared

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-admin#900]
It's set to be display none on all devices as you can see [here](https://github.com/silverstripe/silverstripe-admin/blob/06beff71a45bca0f42c88ea931f142d8bc10d008/client/src/components/Menu/Menu.scss#L305).

Not sure if intentional or not

**Comment by robbieaverill** [comment]
It’s visible in the bottom left corner of the menu bar now, and in the top when viewing in a mobile viewport
