### ISSUE TITLE
RFC Allowing TypeScript in JS libraries

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#902]
# High level overview
TypeScript is a superset of Javascript … any JS code is implicitly TS code. TS can not be run directly it, needs to be "transpiled" back down to JS.

The main difference between TS and JS is that TS support strongly types variables and methods. TS introduces new construct, mostly around typings. This allows you to write richer, more expressive code.

# Potential benefits of using typescript
* Strongly typed definition.
* Types of variables and methods are detected implicitly
* Detect type mismatch and find more bugs upfronts … AirBnB found they could have avoided 38% of their bugs if they had use TS.
* Support for keywords like private, protected and public
* Allows us to define a proper API with interfaces
* TS and JS can co-exist in the same project. We wouldn’t need to change all our codebase at once.
* A TS project can use JS libraries and a JS project can user TS libraries.

# Potential downsides of using 
* The learning curve from JS to TS is pretty small, but it will require a bit of transition.
* TypeScript can be a pain requiring you to explicitly define interfaces. 
* In this example, TS will complain `bonjour` doesn’t exists on keypairs: `let keypairs = {hello: 'world'}; keypairs.bonjour = 'monde';`
* You can get around those problems by defining a variable as the `any` type, but that somewhat defeats the point of using TS.
* TS only understands types from libraries if the library exposes a type definition file.
* TS can create that type definition file for you, but only if your project is entirely written in TS.
* For example, you could write a class in TS in `silverstripe/admin`. If you try importing that class in a TS file in `silverstripe/asset-admin`, the type of that class will be unknown.

# Technical implementation
## silverstripe/webpack-config
Most of the changes are in `webpack-config`. This adds a loader so webpack can transpiled TS files. It also contains a generic `tsconfig.json` file that controls the settings TS will use when transpiling your files.
## Using Typescript in silverstripe/admin
The only needed changes to get `silverstripe/admin` transpiling TS is to require the write version of `silverstripe/webpack-config` and tweak a few settings in `package.json` so the TS code can be tested.

After you apply those changes, you can just rename your JS file to use a TS extension and start writing TS code.

## Using Typescript in dependant module like silverstripe/asset-admin
You just need to replicate the changes you did in `silverstripe/admin`.

On extra thing to keep in mind, is that when importing classes via the `expose-loader` in a TS file, TS will not understand where this file is coming from. So you may need to tell TS to ignore that line with `// @ts-ignore`.

# PRs
* [ ] https://github.com/silverstripe/webpack-config/pull/33
* [ ] https://github.com/silverstripe/eslint-config/pull/6
* [ ] https://github.com/silverstripe/silverstripe-admin/pull/846
* [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/946

# Some instructional video
I recorded two videos that explains how TS will affect JS development.
* [High level overview of the benefit of TS](https://youtu.be/PXb-K9wTAbc) (23 min)
* [How the SilverStripe TS implementation works](https://youtu.be/bd5Gm6faI3s) (10 min)

**Comment by maxime-rainville** [comment]
CC @silverstripe/core-team

**Comment by wilr** [comment]
> On extra thing to keep in mind, is that when importing classes via the expose-loader in a TS file, TS will not understand where this file is coming from. So you may need to tell TS to ignore that line with // @ts-ignore.

In practise wouldn't this be written quite a large amount of the time?

**Comment by flamerohr** [comment]
> On extra thing to keep in mind, is that when importing classes via the expose-loader in a TS file, TS will not understand where this file is coming from. So you may need to tell TS to ignore that line with // @ts-ignore.

tsconfig has a similar concept with expose-loader with `compilerOptions => paths`, but it is relative paths, which you can point to a folder inside node_modules

> In this example, TS will complain bonjour doesn’t exists on keypairs: let keypairs = {hello: 'world'}; keypairs.bonjour = 'monde';

this is actually a good thing - it's the same as "variable does not exist", if you want to access bonjour then it's better practice to define an interface with bonjour as an optional property.

> TS only understands types from libraries if the library exposes a type definition file.

Always check the `@types` npm namespace for a library which doesn't have type definitions, there's a huge library of supported libraries for definitions.

> TS can create that type definition file for you, but only if your project is entirely written in TS.

You can define type definitions as you transition from JS to TS, tsconfig has options `compilerOptions => composite` and `compilerOptions => declarationMap` if set to true, you can reference one compiled file for all your available type definitions in your library package.json `"types": "index.d.ts"`

**Comment by maxime-rainville** [comment]
> > On extra thing to keep in mind, is that when importing classes via the expose-loader in a TS file, TS will not understand where this file is coming from. So you may need to tell TS to ignore that line with // @ts-ignore.
> 
> In practise wouldn't this be written quite a large amount of the time?

That's only going to be an issue when you reference a class from `silverstripe/admin` in `silverstripe/asset-admin`. That's a quirk of the somewhat unusual way our JS libraries reference each .other. 

> You can define type definitions as you transition from JS to TS, tsconfig has options `compilerOptions => composite` and `compilerOptions => declarationMap` if set to true, you can reference one compiled file for all your available type definitions in your library package.json `"types": "index.d.ts"`.
> Reference for what I mean https://stackoverflow.com/a/56371055/695842

Goody, I'll have to try that one.

**Comment by robbieaverill** [comment]
I think most of the time you'd be using Injector to reference admin classes rather than directly. Injector will become a standalone package soon, and with that you'd maybe have limited cases where you'd do that maybe

**Comment by unclecheese** [comment]
A couple more points:

* We should deprecate `prop-types` over time, as strongly typed components via TS are a much more robust solution. You get prop type checking in real time (or at the very least compile time) instead of runtime. There are a number of code generation plugins available that do this automatically for you.

* `Injector` will be a real sticking point. We have the same issue in framework, but we get around it with escape hatches like `@method` declarations for `create`. We can't do that with injector since `get` is just a single instance factory, so by definition, `Injector.get()` an `any`. Would be curious if TS has shims like `@var MyClass $myVar`. To help this along.

* There is a [monorepo](https://github.com/DefinitelyTyped/DefinitelyTyped) for types that we should be using

* We should keep type definitions out of components. I'm a fan of the `declarationMap` file that @flamerohr brought up. Though it would be good to keep some structure around that rather than massive dumping ground.

* Types will need to be exposed by Injector, presumably, unless we build our own shared npm package of types. I don't know what implications that has for `Injector` since at the moment i's rather React-biased.

**Comment by maxime-rainville** [comment]
# Proptypes

You can still use prop-types in TS, but it's kind of an anti-pattern. You're essentially just [declaring a `public static` variable on your TS class](https://github.com/silverstripe/silverstripe-asset-admin/blob/f13a34efe42d7e9c7106005803d06f419060705e/client/src/containers/ThumbnailView/ThumbnailView.tsx#L186).

[Lyft as a tool](https://github.com/lyft/react-javascript-to-typescript-transform) that can quickly convert a React JS class to a TS class, but I haven't tried out.

# Injector

I was thinking we would just do the same thing we do in PHP and explicitly cast our Injector result to a specific class/interface. In that scenario, we would have to define `Injector.get` as returning `any`.
```ts
const service: MyServiceInterface = Injector.get('MyServiceInterface');
```

The nice thing about using TS, is that we'll be able to define interfaces. So a third party could do their own implementation of `MyServiceInterface`.

Unfortunately TS doesn't have any construct like `::class` for interfaces, so we'll have pass those interface names as actual string

**Comment by maxime-rainville** [comment]
Just a quick update. We had internal dev architecture last week and talk about TS a bit:
* The current PR's inability to share type definition between module was seen as problematic.
* There's was some concern about making it even more difficult for people to contribute to our front end code.
* We would like to see it working on a smaller scale example first 
* We would like to have some discussions with the community and see how much exposure/interest they have to TS.

On my hack day Friday, I spent some time trying to address the "sharing type definition between module" part of this problem. I think I've got a way to make this work. https://github.com/maxime-rainville/webpack-config/commit/20bccec27121b50ccf0c739c0aeabf827ba25d09

Basically, this involves using the `path` options in the `compilerOptions` of your `tsconfig.json` file. You define a wildcard for the the other module you need to use. This allows TypeScript to find those files and get their type definition.

```json
{
  "compilerOptions": {
    "paths" : {
      "*" : [
        "client/src/*",
        "../admin/client/src/*",
        "../cms/client/src/*"
      ]
    },
    "strict": true
  },
}
```

I've also workouted a way to extend a generic `tsconfig.json` file. I've documented how this would work https://github.com/maxime-rainville/webpack-config/blob/experiment/ts-module-resolution/docs/configuring_typescript.md

Next hack day, I'll try to do some simple front end module as a demonstration project. I'll also try to get the conversation started around TypeScript with the community.

**Comment by maxime-rainville** [comment]
We had some more discussion about this internally. We decided it wasn't possible to achieve this in the current release line.

**Comment by robbieaverill** [comment]
Hopefully for SilverStripe 5? :)
