### ISSUE TITLE
LeftAndMain.admin_themes should be moved to YAML

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-admin#915]
It’s currently set in PHP:

https://github.com/silverstripe/silverstripe-admin/blob/f4913c5e52d1cf9cd87700bf5f4698eab827a5c1/code/LeftAndMain.php#L184-L187

That makes it impossible to insert a custom admin theme _before_ the default ones, except by using PHP `Config::modify()`.

## PR
- https://github.com/silverstripe/silverstripe-admin/pull/1461

**Comment by michalkleiner** [comment]
Enhancement by @ntd merged. Will be in the next minor release.
