### ISSUE TITLE
Top level in breadcrumb inside file tab not working

### ISSUE THREAD

**Issue by ichaber** [silverstripe/silverstripe-admin#917]
You can't click the root (first) element of the breadcrumb in the file section of the CMS, but only if you're in a folder on level 3 or greater.

The result is, that you can only click the root element in the breadcrumb, if you're in a folder on level 2.

**Comment by michalkleiner** [comment]
It's an asset-admin issue, I saw it as well. Thought I created an issue there already but can't find it, so probably was just in my head.

**Comment by ScopeyNZ** [comment]
It's an `admin` issue. You can reproduce it in the storybook:

https://silverstripe.github.io/silverstripe-admin/?knob-status=default&knob-maxSize=200&knob-tags=%5B%7B%22key%22%3A%22justKey%22%7D%2C%7B%22key%22%3A%22KeyPair%22%2C%22value%22%3A%22123%22%7D%2C%7B%22key%22%3A%22KeyLabel%22%2C%22label%22%3A%22Some%20label%22%7D%2C%7B%22key%22%3A%22KeyPairLabel%22%2C%22label%22%3A%22Some%20label%22%2C%22value%22%3A%22123%22%7D%5D&knob-pill=true&knob-message=Hello%20World&knob-Number%20of%20levels=First&knob-value=&knob-focusable=true&knob-label=&knob-dataKey=HelloWorld&knob-Search=true&selectedKind=Admin%2FBreadcrumb&selectedStory=Breadcrumb&full=0&addons=1&stories=1&panelRight=0&addonPanel=kadira%2Fjsx%2Fpanel

Make sure to use the "knobs" tab to enable more than one level. There's some super janky css going on here with ellipsis overflows and right to left text direction. Might be related to #699 . The ellipsis overflow doesn't actually seem to work correctly - try adjusting the width of your browser on the storybook to see it in action.

**Comment by ScopeyNZ** [comment]
This is fixed by #925 .
