### ISSUE TITLE
Banner block link broken

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#918]
This issue captures the remaining issues from the banner block that I'm aware of.

- [ ] The linking ability of the banner block doesn't seem to work at all
- [ ] The enlarging of the image should only be there is links are included, also add an additional line of css for when hovered and there is a working link `transform: translateY(-2px);`
- [ ] Colour contrast of the gradients need to be darker (happy to work through this with a dev).

**Comment by robbieaverill** [comment]
Do you want to move this to https://github.com/silverstripe/silverstripe-elemental-bannerblock/?

**Comment by chillu** [comment]
Issue moved to [silverstripe/silverstripe-elemental-bannerblock #28](https://github.com/silverstripe/silverstripe-elemental-bannerblock/issues/28) via [**ZenHub**](https://www.zenhub.com/)
