### ISSUE TITLE
Link colour selection is not working with the colour picker 

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#919]
When attempting to change the link colour in the colour picker nothing happens.

Personally, I don't think we need to demo this change so one option could be to remove it from the theme colour selectors, or fix the issue?

![image.png](https://images.zenhubusercontent.com/574b650dbf93871ccd9bc88f/b6c95d70-698f-4bb9-827d-5469bbff4777)

**Comment by robbieaverill** [comment]
Suggest moving to https://github.com/silverstripe/silverstripe-theme-colorpicker

**Comment by clarkepaul** [comment]
Yeah soz, I thought a bunch of issues were being raised int he theme
