### ISSUE TITLE
Bring over accessibility fixes from Watea

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#920]
Bring over the accessibility improvements currently going into Wātea to Bambusa (select ones which are most relevant)
To be ported over once functionality is added:
- [ ] https://github.com/silverstripe/cwp-watea-theme/pull/96 (Language selector)
- [ ] https://github.com/silverstripe/cwp-watea-theme/pull/97 (Search)
- [ ] https://github.com/silverstripe/cwp-watea-theme/pull/92 (Indicators)
- [ ] https://github.com/silverstripe/cwp-watea-theme/pull/99 (Colour picker work)

**Comment by ScopeyNZ** [comment]
Is this issue supposed to be on `bambusa` instead of `admin`?
