### ISSUE TITLE
Insert link into TinyMCE, labels of links inconsistent with designs

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#93]
The link titles for insert link functionality in TinyMCE are inconsistent with the designs provided.
See designs here: https://projects.invisionapp.com/share/BGAYOTRFY#/screens/224873109

Link titles in provided design:
![image](https://cloud.githubusercontent.com/assets/555033/26564630/79a27072-4537-11e7-940e-89594865a53c.png)

Current link titles (should match designs):
![image](https://cloud.githubusercontent.com/assets/555033/26564639/a111def4-4537-11e7-9207-104274feb065.png)

Modal heading provided in design:
![image](https://cloud.githubusercontent.com/assets/555033/26564645/b42ccc92-4537-11e7-9001-3084c54d2a7e.png)

Current modal heading (should match design):
![image](https://cloud.githubusercontent.com/assets/555033/26564650/cd4d589a-4537-11e7-8ac4-d29619e723c8.png)

**Comment by flamerohr** [comment]
I have created a commit to address this in this work https://github.com/silverstripe/silverstripe-framework/issues/6743
