### ISSUE TITLE
ModelAdmin: Allow querystring deep-linking to search

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-admin#938]
Many search UIs embed search queries in the URL, meaning that specific results pages can be deep-linked to.

ModelAdmin doesn't allow for this, as searches are internally triggered with post requests.

It would be nice if querystring parameters corresponding to searchable_fields would open that search result set by default.

Challenges to be aware of: watch out for nested gridfields.

**Comment by unclecheese** [comment]
Related: https://github.com/silverstripe/silverstripe-framework/issues/9080

**Comment by stephenmcm** [comment]
Duplicate of #814 
This makes updating past 4.2 a no-go for any model admin heavy site.

**Comment by unclecheese** [comment]
I've started a fix for it. It's quite complex and yucky.

https://github.com/silverstripe/silverstripe-admin/pull/939/files

**Comment by sminnee** [comment]
Righto closing if it's a duplicate.
