### ISSUE TITLE
Homepage movement warning trigger a loop

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-admin#953]
After trying to move the home page then accidentally clearing the modal, repeating the same action will cause a loop of movement success messages, and the site tree does not update appropriately.

![image](https://user-images.githubusercontent.com/778003/64659316-2bb1df80-d48f-11e9-945c-1cd317ae06d1.png)

1. Move homepage to a sub-page (e.g. `About us`)
2. Dismiss warning (I clicked the vignette/silk screen)
3. Move homepage to the same sub-page (i.e. `About us` as per step 1)
4. 👀 Observe that the Home page shows as draft under the `About us` page twice, and there are many `Reorganised the site tree successfully.` toast messages (that keep appearing continuously).

Hard reload the page.
Notice that the Homepage was successfully moved, even though the action was to dismiss the modal.

**Comment by brynwhyman** [comment]
This looks pretty related to: https://github.com/silverstripe/silverstripe-cms/issues/2474

**Comment by emteknetnz** [comment]
I'm going to assume this was fixed by https://github.com/silverstripe/silverstripe-cms/issues/2474
