### ISSUE TITLE
TinyMCE text-align don't seem to work

### ISSUE THREAD

**Issue by mgb16nz** [silverstripe/silverstripe-admin#966]
Have noticed in SS442 and SS444 (not tried SS443) in the cms that the tinymce text-align - left / center / right / justify are not working when wish to use them. 

If try to center a text, the text stays on the left. When check the code, you can see it says `<p class="text-center"></p>`, the same happens when wish to place the text on the right, it stays on the left

Used composer to install SilverStripe 442 and 444 and with the simple theme for testing. Have done 3 websites with SS442 and was picked up on the last website by a client

**Comment by kinglozzer** [comment]
Thanks @mgb16nz, this is being tracked in https://github.com/silverstripe/silverstripe-framework/issues/8785
