### ISSUE TITLE
HtmlEditorField JavaScript error

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe/silverstripe-admin#967]
**Affects:** v4.4
**Browser:** IE11
**Steps to reproduce:** Type text into an HtmlEditorField
**Expected:** I can type some text.
**Actual:** The HtmlEditorField dissapears.

Here's a screenshot of the console error:

![Screenshot from 2019-10-11 14-42-05](https://user-images.githubusercontent.com/878176/66618638-50d47200-ec36-11e9-9f56-310b4f589c60.png)

Which looks like it maps to somewhere around here:
https://github.com/silverstripe/silverstripe-admin/blob/1/client/src/components/HtmlEditorField/HtmlEditorField.js#L103

**Comment by Cheddam** [comment]
Hey @flashbackzoo, thanks for the report! Are you able to replicate this in the most recent version of CMS (4.4.4)? We made a fix for this [a while back](https://github.com/silverstripe/silverstripe-cms/issues/2459).
