### ISSUE TITLE
Expose available reactstrap components in Pattern Library

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-admin#988]
The Pattern Library should be considered a 'source of truth' for our full library of components, and serves as a 'one stop shop' for developers looking to add elements to the UI (if there's no example in the PL, they'll likely create a new one).

At the moment we only expose reactstrap components in the Pattern Library when they're used in a custom component. As these form a pretty integral part of our UI, it would be best to present them in the Pattern Library so that a developer looking to add new UI elements is aware of their existence, and less likely to create duplicates.

**Comment by robbieaverill** [comment]
I think the argument in the past has been that we should expose our own fields, but reactstrap (or whatever other frontend library you want to use when customising the cms) is not something we would include. What examples do you have that aren’t already there?

**Comment by Cheddam** [comment]
I don't think we should encourage use of other frontend libraries that don't match our established design patterns, as that could result in mismatched and awkward looking interfaces - hence the overall intention to expose more default options for developers.

However... I've reviewed the reactstrap library, and it turns out that aside from `Button`s (which we have [a PR](https://github.com/silverstripe/silverstripe-admin/pull/968) open to expose already) there aren't actually any components we'd be likely to recommend using that we're not already effectively exposing in the Pattern Library, so I'm going to close this out.
