### ISSUE TITLE
React 17 warning about async rendering and deprecated lifecycle hook

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#989]
React 17 will deprecate a bunch of life cycle hooks like to make way for something called "async rendering".
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

React 16 has started warning us about those deprecated API.

As a first step, we should stop using the deprecated life cycle hook in new code ... mostly componentWillMount. We can pre-adopt the the new APIs now and future proof our code.

As a second steps, we should update existing usage to squash those warnings. Updating to the new API doesn't look massively difficult, but it's not trivial either. IT requires a bit of thinking.

**Comment by Cheddam** [comment]
Note: Marking this as `type/enhancement` for the time being, as it's not a breakage. It'll need to be addressed before we adopt React 17 (whenever that releases), otherwise it'll need to be re-labelled as `type/bug`.

**Comment by maxime-rainville** [comment]
It does make debbuging JS kind of painful thought because it's spit lots of warning in the console. Might be worthwhile identifying the most common one and fixing them just to make it easier to debug regular work.

**Comment by GuySartorelli** [comment]
We're using react 18 in CMS 5 and have addressed this
