### ISSUE TITLE
Drop main modalAdmin tabs for smaller screens

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#99]
Requires https://github.com/silverstripe/silverstripe-admin/issues/100 to be done first. 
Part of the Responsive CMS set of issues https://github.com/silverstripe/silverstripe-framework/issues/6267

< 768px Drop the top right set of UI tabs to sit beneath the breadcrumbs/header toolbar in order for them to fit the given space (left aligned). [~2pt]
![image](https://cloud.githubusercontent.com/assets/555033/20582913/409b9978-b24a-11e6-9c28-abadf2af9ccd.png)

## Pull request

- [ ] https://github.com/silverstripe/silverstripe-admin/pull/107

**Comment by tractorcow** [comment]
Approved, merge https://github.com/silverstripe/silverstripe-admin/pull/107 on green.
