### ISSUE TITLE
Filters get reset when loading a different page from the pagination.

### ISSUE THREAD

**Issue by jamieduck** [silverstripe/silverstripe-admin#994]
@maxime-rainville 

(The code below seems to not be formatting correctly)

The issue here is that when you select a filter and click search the page loads the correct values, but when you change the page to page 2 or any other page from the pagination options it drops the filters. The page_length does not work on this issue either.

Here is the searchableFields function (DataObject):

```php
    public function searchableFields()
    {
        return [
            'Title' => [
                'filter' => 'PartialMatchFilter',
                'title' => 'Title',
                'field' => TextField::class,
            ],
            'DateStart' => [
                'filter' => 'GreaterThanOrEqualFilter',
                'title' => 'Date Start',
                'field' => DateField::class
            ],
            'DateUntil' => [
                'filter' => 'LessThanOrEqualFilter',
                'title' => 'Date To',
                'field' => DateField::class,
            ]
        ];
    }
```

Here is the filters function (DataObject):

```php
public function defaultSearchFilters() {
    foreach ($this->searchableFields() as $name => $spec) {
        if (in_array($name, [ 'DateStart', 'DateUntil' ])) {
            continue;
        }
        if (empty($spec['filter'])) {
            $filters[$name] = 'PartialMatchFilter';
        } elseif ($spec['filter'] instanceof SearchFilter) {
            $filters[$name] = $spec['filter'];
        } else {
            $filters[$name] = Injector::inst()->create($spec['filter'], $name);
        }
    }

    return $filters;
}
```

Here is the getList function (ModelAdmin):

```php
public function getList(){
    $list = parent::getList();
    $requestFilter = $this->getRequest()->requestVar('filter');
    $filters = [];
    if (isset($requestFilter['DataObject']['DateStart']) and ! empty($requestFilter['Item']['DateStart'])) {
        $filters['Date:GreaterThanOrEqual'] = $requestFilter['Item']['DateStart'];
    }
    if (isset($requestFilter['DataObject']['DateUntil']) and ! empty($requestFilter['Item']['DateUntil'])) {
        $filters['Date:LessThanOrEqual'] = $requestFilter['Item']['DateUntil'];
    }

    return $list->filter($filters);
}
```

**Comment by maxime-rainville** [comment]
Just clarifying what this is about. I had a chat with @jamieduck and it looks like the specific configuration DataObject he has outlined above, the search pagination stop workings. Basically, you get the first page of results, but once you try navigating to the second page you loose your search parameter.

It seems to be specific to this data object.

**Comment by maxime-rainville** [comment]
I had a chat with with Jamie and reviewed some sample code from his project. The root of the problem was that they were reading filter parameters from the HTTP request and updating the the DataList query in their ModelAdmin's getList() method.

This works for the initial request, however filter parameters are stored in the GridState on follow up requests, so they weren't getting any filtering parameters.

The solution was to move their custom filtering logic to custom search context. The filtering criteria would be provided by the GridField which would handle the GridState logic.
